### ISSUE TITLE
How can I integrate this with back-end?

### ISSUE THREAD

**Issue by egucciar** [MrSwitch/hello.js#1]
Everything here is great. However, I don't want the client to receive the response directly.

 I first want to send my response (redirect uri) to the Server running the client. Then can I send a response back to hello.js once the server has received this information directly from the authorization end point?

 The issue I have with Client-side only communication is that there is no way for our server to authorize Client access to their own data from our server unless our Server initiates the authentication itself. But if we can initiate the authentication from the client, and give the response to the server, then the server could process that response and send it back to our client, then no one but the OAuth2 provider is giving our Server the OK to send stuff back to our client.

**Comment by krunal2212** [comment]
> 

> 

> 

> 

> 

> 

> 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] @

**Comment by krunal2212** [comment]
I am using PHP Language, I am trying to integrate Hello.js with PHP can any one help me out ?
@MrSwitch

**Comment by andrisi** [comment]
The requirement of server side validation of the user, and in turn the tokens is a common use case. Backends shall not trust the client to say who they are. Would be nice to eaither refer this to in the doc and suggest a server side package. Something similar to hello.js but server side, or even better, make hello.js work under node too... Thanks for all your efforts, great work regardless of this.
