### ISSUE TITLE
Issues with Dropbox and Google Drive

### ISSUE THREAD

**Issue by Arkan** [MrSwitch/hello.js#110]
Hi there,

I'm having a hard time trying to figure out issues with Dropbox & Google Drive. It's probably my fault ;-)
But basically I have an AngularJS application communicating with a backend written in Go.
The idea is to allow the user to create an account, then he can add multiple accounts(Dropbox, Google Drive, etc...). The accessTokens/RefreshToken will be sent to the backend from the AngularJs application. My backend needs to have long access token(or at least refresh tokens) in order to make actions without the need of the user to be present on the application.

The issue with dropbox is that my backend  needs an oauh2 accessToken ... Is there a way to easily get one from a oauh1 token with hello.js ? Or better having direct support for oauh2 for Dropbox. I want to avoid doing that server side.

The issue with Google Drive, is that I don't always get a RefreshToken, this is pretty annoying especially when the user remove/add the service. The second time, I don't have the refreshToken in the response.
I also don't have any information to identity the user - no uid, no email, nothing .... 

Thanks for your help,

**Comment by MrSwitch** [comment]
v1.8.1 supports the switch to Dropbox OAuth2
