### ISSUE TITLE
Flickr auth popup closes itself without asking for login

### ISSUE THREAD

**Issue by trisle** [MrSwitch/hello.js#134]
I noticed that the other guy in this forum has the same issue as mine for his Yahoo.

For me my **Flickr authentication just doesn't work correctly** even though I checked that everything is configured correctly. My Flickr auth popup window would just close itself without asking for any login at all.

However, the same code works for my Facebook auth (on the same page, in the same context), so I think it's probably something to do with the Flickr setup itself and proxy or anything like that in the project.

What do you think? I appreciate your help and thanks in advance :)

**Comment by riddhithaker** [comment]
hey I'm having same issue with Flickr. When I call login('flickr'), I receive the following error: Invalid API Key (Key has invalid format) and i also check my keys. Any idea??
Thanks in advance.

**Comment by MrSwitch** [comment]
@riddhithaker are you using the proxy https://auth-server.herokuapp.com/ ?

**Comment by lfcj** [comment]
Hi @MrSwitch, I am using  https://auth-server.herokuapp.com/ too (although for twitter), but it says *Page not Found*. Here is the code:<br> 
`hellojs.init({` 
    `facebook : '855540421169752',`
    `google  : '23079439365-b1ndmtcn4cscdm6jjoeisvm1ttubv2qp.apps.googleusercontent.com',` 
    `twitter   : 'jqz88xl5oSdihbKtDvO8q3pOm'`
    `},{redirect_uri:'',` 
       `oauth_proxy  : ' https://auth-server.herokuapp.com/proxy',`
       `scope        : 'publish_actions'`
      `}`
);

**Comment by MrSwitch** [comment]
@lfcj please initiate a new issue if you still have problems
