### ISSUE TITLE
AccessTokens should be encrypted before storing in the localStorage

### ISSUE THREAD

**Issue by vamsibolloju** [MrSwitch/hello.js#136]
I could get the "hello" data stored in localSorage in the browser , and set the hello data in another application . Then i could get acces  to the user details to whom the access token belongs to.

 I think some encryption can be done before storing in localSorage.

**Comment by jdolearydl** [comment]
@MrSwitch What about XSS?
https://auth0.com/docs/tokens/guides/store-tokens#don-t-store-tokens-in-local-storage
Why not store the token in a cookie instead?
