### ISSUE TITLE
Add support for Authorization header

### ISSUE THREAD

**Issue by hajekj** [MrSwitch/hello.js#167]
I have a custom OAuth provider (university server) and it can only receive the access token through Authorization header, for example:
Authorization: Bearer ACCESS_TOKEN

More information can be found here: http://tools.ietf.org/html/draft-ietf-oauth-v2-bearer-20#section-2.1

Any chance it could be implemented into the library?

**Comment by si458** [comment]
sorry to post in old issue but im having this issue and the solution @MrSwitch listed isnt working :(
if i add in the Authorization header the request seems to change to an OPTIONS request instead of a GET, any ideas why this happens?

**Comment by hajekj** [comment]
That is fine, it is a CORS pre-flight request where browser checks whether it can or not send the request to the server. I suggest reading up on CORS - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by si458** [comment]
@hajekj oh great, is the no way of bypassing this without setting options in firefox?
sadly the oauth2 server we use is just returning 404 error when doing OPTIONS and they only support GET or POST

**Comment by hajekj** [comment]
I think CORS is implemented on the browser level which is then consumed client-side from browser. Do you host the authentication server yourself or it's a 3rd party one?

**Comment by si458** [comment]
sadly its a 3rd party :(

i think the only thing i can do now is pass a command from users browser to our backend server (where the secret does it auth etc) then from there to the oauth server and return reply to the users browser

**Comment by hajekj** [comment]
What exactly are you trying to do? The client_secret should never be exposed to the client's browser.

**Comment by si458** [comment]
1. user goes to a webpage and logs in with the 3rd party auth server (got all that working)
2. i have to use a local oauth_proxy because the 3rd party REQUIRES a client_secret
3. clients browsers gets it Auth token without issue (all works)
4. sadly clients browser cant call the 3rd partys API with the AUTH token as its required in the Headers and stupid firefox/chrome keeps blocking the command because of the CORS
if that made ANY sense 😆

**Comment by hajekj** [comment]
That sounds really weird and obscure. Well, if you already have an oauth proxy in place, I would just stick to using it for API as well...

**Comment by si458** [comment]
ok so after stripping the hello.js and node-oauth-shim to pieces
it turns out the proxy wouldnt of even re-directed the headers that was included anyways proxy.js:81
```
if (header.match(/^(x-|content-type)/i)) {
options.headers[header] = req.headers[header];
}
```
