### ISSUE TITLE
Login in facebook from app and logout from facebook causes error

### ISSUE THREAD

**Issue by Danieler** [MrSwitch/hello.js#174]
If i make a login from facebook and later i logout from facebook
when i make a hello( "facebook" ).getAuthResponse(); it continues given me data from the session
and if i try to logout from my app with hello( 'facebook' ).login({force:true})
give me the following error:
Refused to display 'https://www.facebook.com/' in a frame because it set 'X-Frame-Options' to 'DENY'.

when i make  hello( "facebook" ).getAuthResponse(); not recognize that its logged out from faceboook??

the example code:

       <button onclick="hello( 'facebook' ).login({force:true})">FB</button>

       <button onclick="logOutFacebook()">Logout FB</button>

       hello.init({
            facebook : 'myid'
        });
        hello.on('auth.login', function(auth){

            // call user information, for the given network
            hello( auth.network ).api( '/me' ).then( function(r){
                // Inject it into the container
                var label = document.getElementById( "profile_"+ auth.network );
                if(!label){
                    label = document.createElement('div');
                    label.id = "profile_"+auth.network;
                    document.getElementById('profile').appendChild(label);
                }
                label.innerHTML = '<img src="'+ r.thumbnail +'" /> Hey '+r.name;
            });
        });

        function logOutFacebook(){
            hello( "facebook" ).logout({force:true}).then( function(){
                alert("Signed out");
            }, function(e){
                alert( "Signed out error:" + e.error.message );
            });

        }

**Comment by jyotigupta007** [comment]
Hello,

I am also facing the same issue. It shows me :- 
**error**:
code:100
fbtrace_id:"ERgeGdEt12x"
message:"API calls from the server require an appsecret_proof argument"
type:"GraphMethodException"
