### ISSUE TITLE
'http://adodson.com/hello.js/redirect.html' stays open in PhoneGap

### ISSUE THREAD

**Issue by AWoelfel** [MrSwitch/hello.js#183]
Hi, 

i just tried to run the 'hellojs-phonegap-demo' demo using PhoneGap on my Nexus4 (Lollipop).
While the demo is running flawless in a local webserver i get a javascript exception in hello.js inside the redirect_uri page (http://adodson.com/hello.js/redirect.html.

The error is : 
"Scripts may close only the windows that were opened by it."

in hello.js:1544 (window.close();)
and inside the catch block
hello.js:1551 (window.close();)

The login worked and i got a token from facebook.
the hellojs-phonegap-demo hangs while waiting for the popup to close.

edit - 2015-01-17 21:27 :
i want to point out that access-origin is set to "*" and the in-app-browser plugin is installed

**Comment by MrSwitch** [comment]
Please debug do some further debugging regarding. 

> The error is : "Scripts may close only the windows that were opened by it."

Regarding your comment
>... inside the catch block "hello.js:1551 (window.close();)"

Please take a second look at (https://github.com/MrSwitch/hello.js/blob/v1.4.1/src/hello.js#L1551) and you'll see this is not inside a catch block.
