### ISSUE TITLE
Yahoo Login Porblem

### ISSUE THREAD

**Issue by DeepBlue1** [MrSwitch/hello.js#184]
When signing in with yahoo, I get the following message in the popup:
"Oops. Yahoo is unable to process your request.
We recommend that you contact the owner of the application or web site to resolve this issue. [95033]"

However when I click the button again, I find my self already signed in, with authorize app message, after that everything works fine.

What is the problem?

**Comment by DeepBlue1** [comment]
Problem solved, the problem was in the redirect path, when I put absolute path it doesn't work, but when I put relative path it works! although absolute path worked for windows and google APIs.

**Comment by MrSwitch** [comment]
@DeepBlue1 that shouldn't make a difference, can you debug `hello.login` and see how the `redirect_uri` is composed?

**Comment by trideepgogoi** [comment]
Might have been a part of a general Yahoo API failure's I was having anyways.

**Comment by MrSwitch** [comment]
Can you close this issue?
