### ISSUE TITLE
Check authentication for with multiple networks

### ISSUE THREAD

**Issue by Gkenn** [MrSwitch/hello.js#186]
Firstly thanks for a wonderful library! Its exactly what I needed.

I wish to offer multiple networks for the user to authenticate in my phonegap app. I need to verify that the current access token is still valid before they are allowed to do anything, or they will be redirected back to the login page. I understand you can do something like this.

var google = hello('google');
// Set force to false, to avoid triggering the OAuth flow if there is an unexpired access_token available.
google.login({force:false}).then(function(){
	google.api('me').then(handler);
});;

However this assumes that the user is logged in with google. (What if they are authenticated with facebook/twitter etc?)

Is there a function to check the validity of the token for the current session in Hellojs?

Will using

Object.keys(hello.utils.store());

get the name of the current network the user is authenticated with?

**Comment by MrSwitch** [comment]
@Gkenn 

Sorry for the belated response, yeah you can check the validity of the token.

```javascript
var session = hello('facebook').getAuthResponse();
session.expires > (new Date).getTime()/1000; // returns true if token has not expired.
```
