### ISSUE TITLE
How get signed_request from facebook api

### ISSUE THREAD

**Issue by bcomdevel** [MrSwitch/hello.js#187]
Hi,
I tried hello.js and want to get more data from api's response data (signed_request).
Thanks for your answer

**Comment by MrSwitch** [comment]
Need more info (pardon the irony)

**Comment by bcomdevel** [comment]
Yeah sorry not to be More specific. With facebook api by using SDK JS there is a function FB.getLoginStatus and it return me an oject like this : 
{
    status: 'connected',
    authResponse: {
        accessToken: '...',
        expiresIn:'...',
        signedRequest:'...',
        userID:'...'
    }
}
source : https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus?locale=fr_FR
So i wish to get the signedRequest value with Hello.js.

**Comment by MrSwitch** [comment]
Does `hello('facebook').getAuthResponse()` help. You are expected to determine whether the token has expired yourself.

I prefer to set `hello.on('auth.logiin', handler)` on page load for GET requests.

But for other actions which are generated via a user click action, i.e. post activitty etc. Then to wrap the call in an unforced login (this checks the validity of the token, scope and expiry, and will return an existing token or prompt the user to resignin)

i.e.
```javascript
hello('facebook').login({force:false, scope:'publish' }).then(function(r){
    // make api call i.e.  hello('faceebok').api(...);
}, errorHandler);
```

This has the benefit of not having to worry about expired tokens, additional scope etc... and keeps your user requirements permissions to the feature they are using.

**Comment by bcomdevel** [comment]
Hi thanks for your answer. And sorry not to be clear. I need the signedRequest to verifiy that the data i receive is really from facebook. (https://developers.facebook.com/docs/plugins/registration/v1.0?locale=fr_FR)

hello('facebook').getAuthResponse() don't have the signedRequest.
