### ISSUE TITLE
can't make instagram working

### ISSUE THREAD

**Issue by sunsgs** [MrSwitch/hello.js#189]
instagram is not working  error as below

{"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered             redirect URI"}

**Comment by MrSwitch** [comment]
Please read the error message "Redirect URI does not match registered redirect URI"

**Comment by sunsgs** [comment]
i don't understand how to fix it. the redirect URI is the main url of the web app.

**Comment by MrSwitch** [comment]
Example config

```javascript
hello.init({
    'instagram' : 'e47d210f864c4b1ca94225ddab97205a'
},{
    redirect_uri : 'https://adodson.com/hello.js/redirect.html'
});
```


![image](https://cloud.githubusercontent.com/assets/947163/5960441/47875652-a7cd-11e4-9711-9d889244881c.png)

**Comment by sunsgs** [comment]
i have done exactly as you said....not working, always the same error

**Comment by sunsgs** [comment]
is working, but if i set the redirect uri then facebook and twitter are not working

**Comment by MrSwitch** [comment]
... @sunsgs then you need to update the redirect_uri you registered with facebook and twitter.
