### ISSUE TITLE
"Could not find the credentials that match the provided client_id. Register your app credentials by visiting https//auth-server.herokuapp.com"

### ISSUE THREAD

**Issue by siddmegadeth** [MrSwitch/hello.js#196]
Hi,

I am using Yahoo OAuth . i am using the the hello.js provided from the site.

I am getting the following error.

Before Page load i am setting 
hello.init(
{
    "yahoo" : "dj0yJmk9dnpWeGM4cEp6WDFYJmQ9WVdrOVRUQkdXalYwTjJrbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0wZA--"
},
{
  redirect_uri:'http://stagingd11.dream11.com/',
  oauth_proxy: "https://auth-server.herokuapp.com/proxy"
  //https://auth-server.herokuapp.com/   https://auth-server.herokuapp.com/proxy
});

and on click i am adding this line

hello("yahoo").login().then(function()
    {
        // Get Profile
        return hello("yahoo").api('me');
    }).then(function(p)
    {
      console.log(p.name);

    }).then(null, function(e){
        console.error(e);
    });

I have also registrred  using
https://auth-server.herokuapp.com/#manage-apps

 Also it would be kind of u if you can explain the
https://auth-server.herokuapp.com/#manage-apps parameters and field value.

 
I am getting the issue.

Please help

**Comment by MrSwitch** [comment]
The only client_id i can see for that domain is "dj0yJmk9WGJDUHpwMkxBNUxEJmQ9WVdrOU4xcFBZVUo1TldrbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1jMw--"

The one you have provided above is not registered.

Can you please check, thanks.

**Comment by siddmegadeth** [comment]
i have changed that and created a new app. but still its not working

**Comment by siddmegadeth** [comment]
dj0yJmk9WGJDUHpwMkxBNUxEJmQ9WVdrOU4xcFBZVUo1TldrbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1jMw

**Comment by MrSwitch** [comment]
The db has this (with two hyphens at  the end) 
> dj0yJmk9WGJDUHpwMkxBNUxEJmQ9WVdrOU4xcFBZVUo1TldrbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1jMw--

**Comment by siddmegadeth** [comment]
hi,

those 2 hyphens are generated as a consumer key from YDN. should it be removed.
Even after removing from both project and https://auth-server.herokuapp.com/#manage-apps. the error is still the same. dont know what to do

**Comment by MrSwitch** [comment]
Your comment earlier had left them out, which is why I brought it up. The client id needs to match verbatim.

**Comment by siddmegadeth** [comment]
Hi,

Thanks I am able to login now. But i am not getting email infromation about the current user
Is there any other way to get the email info as our primary key is email. and its coming null.

    hello("yahoo").login().then(function()
    {
        // Get Profile
        return hello("yahoo").api("me");
    }).then(function(p)
    {
      console.log(p);
      userData.name = p.name;
      userData.id = p.id;
      userData.email = p.email;
      userData.birthYear = p.birthYear;
      userData.guid = p.guid;
      userData.displayAge = p.displayAge;
      userData.nickname = p.nickname;
      userData.gender = p.gender;
      userData.ageCategory = p.ageCategory;
      console.log(userData);

      //Add these data to Database
    
    }).then(null, function(e)
    {
        console.error(e);
        alert("Error : "+e);
    });


Not able to get the info as required.

**Comment by siddmegadeth** [comment]
please help

**Comment by MrSwitch** [comment]
You should see the email come through as expected.

FYI: not all services return an email, but those that do will have the property `email` ... or at least they should.

**Comment by siddmegadeth** [comment]
hi,


$(".btnYahooClick").click(function () 
{
    
   hello( "yahoo" ).login().then( function(e)
   {
      

         hello( "yahoo" ).api("me").then(function(json)
         {
           alert("Your name is "+ json.email);
           console.log(json);
         }, function(e){
        alert("Whoops! " + e.error.message );
        });
      
  
}, function( e )
{
    alert("Signin error: " + e.error.message );
});


 });

This is the function i have written. I have taken it from your souce code only.
On analysis i see that your code for login return the email


http://adodson.com/hello.js/#event-subscription

hello( "yahoo" ).api("me").then(function(json){
	alert("Your name is "+ json.email);
}, function(e){
	alert("Whoops! " + e.error.message );
});

its display the email. but it does nto work in my code. please help.


please walk us through on this as its very urgrent.

**Comment by siddmegadeth** [comment]
hello.init({
    'yahoo' : "consumer key"
},
{
    
    redirect_uri:'http://stagingd11.dream11.com/IN/',
    oauth_proxy: "https://auth-server.herokuapp.com/proxy"
});

**Comment by MrSwitch** [comment]
Hi @siddmegadeth 
I hope you can figure this out on your own by inspecting the response. I can't provide individual support i hope you understand.

**Comment by siddmegadeth** [comment]
Hi,

I do understand your concern. The problem is that one of teh junior resource opted for your solution
for oAuth it worked flawlessly for all including google,linkedin,fb. 
yahoo
but has got issue with Yahoo. Your site shows the email id on your it but same code does not.
I am not asking for individual support for your help as why it is happening like this and what we could do to resolve this. 

We dont have any other means. it would be best we remove all hello.js from our project.

Please  help

**Comment by siddmegadeth** [comment]
Thanks able to solve it. While creating the App select edit/read/write private data fro profiles. 
it works.
