### ISSUE TITLE
hello takes over error handling

### ISSUE THREAD

**Issue by cfjedimaster** [MrSwitch/hello.js#200]
I found something that - if I understand it right - is a deal breaker for me using this library. Once hello.js has done anything, if your JS code has an error, then the error is silently swallowed by hello.js and ignored. This makes debugging fairly difficult. Imagine this code:

    function startFetchingRepositories(path) {
        console.log('um');

        if(path.length && path.indexOf('https://api.github.com/') >= 0) {
            path = path.replace('https://api.github.com/','');   
        }
        console.log('fetching with '+path);
        hello('github').api('/user/repos').then( function(r){
            console.log("repos");
            console.dir(r);
            if(r.paging.next) {
                total++;
                if(total > 3) throw new Error("foo");
                startFetchingRepositories(r.paging.next);   
            }
        });

    }

I've got an error in there some place, I think the replace, but I don't see it in console because hello.js hides it. I know this because I added a breakpoint at the console, added a line like so:

    notafunction();

and when that line is executed, I don't get a normal error. I see the code enter hello.js. I'm going to switch to the non-minimized version to see if I can track it down.

**Comment by cfjedimaster** [comment]
Ah, it is failing in the resolver:

    var resolver = function (cb, next, method) {
		return function (value) {
			if (typeof cb !== "function")                            /*  [Promises/A+ 2.2.1, 2.2.7.3, 2.2.7.4]  */
				next[method].call(next, value);                      /*  [Promises/A+ 2.2.7.3, 2.2.7.4]  */
			else {
				var result;
				try { result = cb(value); }                          /*  [Promises/A+ 2.2.2.1, 2.2.3.1, 2.2.5, 3.2]  */
				catch (e) {
					next.reject(e);                                  /*  [Promises/A+ 2.2.7.2]  */
					return;
				}
				resolve(next, result);                               /*  [Promises/A+ 2.2.7.1]  */
			}
		};
	};

Specifically the reject. And now it makes some sense.

**Comment by MrSwitch** [comment]
Yes this is a problem. This method is triggered in a try/catch from the redirect_uri popup.

**Comment by cfjedimaster** [comment]
How would I work around it? Besides not having any issues. ;)

**Comment by MrSwitch** [comment]
@cfjedimaster , you need to catch errors in your Promise chain.

```javascript
hello('github').api('/user/repos').then( function(){
    throw Error();
}).then(null, handleError);
```

Does that help?

**Comment by cfjedimaster** [comment]
Ok, thanks.
