### ISSUE TITLE
 "Login has been cancelled" with google

### ISSUE THREAD

**Issue by Andyhasit** [MrSwitch/hello.js#202]
Hi, 

I get  "Signin error: Login has been cancelled" with the following.
I have no idea where the problem might be: if it is with the way I have configured the app in google developer console, or if I'm not calling hello.init() properly?
I'm running it on localhost, and the google pop-up opens fine, even sends an sms to my phone, but going by the callbacks it seems I'm being kicked out.

I don't think it's necessarily an issue with hello.js but wondering if you had any pointers as I'm not getting much from google..

    <body style="background:url('stars.png'); ">        
    <button onclick="Login()">Login</button>
    <button onclick="testMe()">Count Contacts</button>

    <script src="hello.all.js"></script>
    <script src="myApp.js"></script>
    <script>
      function Login(){
        hello.login("google")
        .then( function(){
          alert("You are signed in to google");
        }, function( e ){
          console.log(e.error);
          alert("Signin error: " + e.error.message );
        });
      }

      function testMe(){  
       //  hello.api({'me/contacts')
       hello( "google" ).api("me").then(function(json){
          alert("Your name is "+ json.name);
        }, function(e){
          alert("Whoops! " + e.error.message );
        });
      }

      hello.init({
        google : 'xxxxxxxxxxxxxxxx'
      },{
        redirect_uri: '/index.html',
        scope:'email'
      });
    </script>
  </body>

**Comment by MrSwitch** [comment]
"cancelled" occurs if a user closes the popup prematurely or its closed by another script. Your sample code above looks fine, i suggest the problem lies with a conflicting script.

**Comment by Andyhasit** [comment]
Thats's exactly the pointer I needed. It turns out I wasn't redirecting to the page I thought I was, but would have taken me ages to figure out that's what was causing the error message.
Many thanks!
