### ISSUE TITLE
Twitter signin seems broken

### ISSUE THREAD

**Issue by evankikie** [MrSwitch/hello.js#203]
On the hello.js latest version, twitter signin seems not working properly.

It was working fine previously. As of Mar 6, I noticed that it's stopped working.

Steps to reproduce:
Signin by calling hello('twitter').login(..).then(function () {...});

Expected:
Pop-up windows to sign in to appear and upon successful (after oauth_proxy handshake etc), it goes to redirect page and closed.

Actual:
The pop-up window remains on the page, and it's displaying the user's timeline.

I'm not sure what happened here. Is the oath_proxy changed, or the twitter oauth1 impl has changed.

Thanks.

**Comment by MrSwitch** [comment]
@evankikie 

This appears to be a change in the Twitter API. I've tweeted @TwitterDev hoping to get the issue resolved.

What we're seeing is Twitter not honoring the oauth_callback see attached
![twitter login error](https://cloud.githubusercontent.com/assets/947163/6544163/01fa1610-c596-11e4-9b75-0809582dbcdb.png)

**Comment by MrSwitch** [comment]
I've mentioned it in the forum https://twittercommunity.com/t/oauth-callback-ignored/33447?u=setdata
please "watch" it so that it given more attention

**Comment by MrSwitch** [comment]
The //auth-server has been patched to work with twitter.

**Comment by evankikie** [comment]
Thanks for the quick patch @MrSwitch. I confirmed that it's now back in working state.
Similarly, I am still hoping for another solution as you mentioned in the other thread.
