### ISSUE TITLE
Module for QQ

### ISSUE THREAD

**Issue by MikeB2012** [MrSwitch/hello.js#204]
Is anyone working on a module for QQ?  Writing my own seems a bit beyond my abilities at the moment, but I did some digging and came up with a QQ javascript SDK: http://wiki.connect.qq.com/js_sdk使用说明  The Google translation makes it seem like the right library to be looking at.  Any thoughts or advice?

**Comment by MrSwitch** [comment]
Sorry, not familiar with QQ, but please have a look at how hellojs modules are  created in `src/modules/*` hopefully you will create one for QQ? :)

**Comment by MrSwitch** [comment]
inactive
