### ISSUE TITLE
Auth Server Problems?

### ISSUE THREAD

**Issue by jonnyquizzical** [MrSwitch/hello.js#205]
Hi, as of yesterday (or perhaps before), all the apps I've stored on https://auth-server.herokuapp.com have been erased. I'm also unable to add any back. Are there any known issues?

**Comment by MrSwitch** [comment]
The server appeared to have stalled, its back up now and serving requests.

**Comment by MrSwitch** [comment]
//auth-server has memory leaks.

**Comment by jonnyquizzical** [comment]
Thanks MrSwitch
