### ISSUE TITLE
Twitter pop-up redirecting to twitter.com and not back to the app

### ISSUE THREAD

**Issue by UltimateBrent** [MrSwitch/hello.js#206]
This all worked last time I tried it, maybe a week or so ago, and I have not changed the code. Now when you auth with twitter, it says "Redirecting back to application", but the pop-up window just redirects to twitter.com. This *does* actually connect, and I can do /me requests etc, but the popup just stays there.

I'm worried Twitter changed something.

Anyone else having this issue?

**Comment by MrSwitch** [comment]
Yes twitter did change something, you'll need to upgrade node-oauth-shim to
version 0.2.1 which contains a fix

This ticket duplicates #203

Andrew Dodson | Freelance Web Developer | +61 (0) 452 411 861 |
https://adodson.com

**Comment by UltimateBrent** [comment]
Ah, that did it! Sorry I didn't see the other ticket.
