### ISSUE TITLE
Facebook Login 2.x advanced permission handling

### ISSUE THREAD

**Issue by wimpyprogrammer** [MrSwitch/hello.js#207]
Firstly, I love HelloJS and its elegance.  Thanks for making OAuth so accessible!

Like many HelloJS users, I've been upgrading my app to Facebook Graph `2.x`.  The newer Facebook Login allows users to selectively opt-out of the permissions requested by the application.  With this are some request parameters for seeing which permissions were rejected, and re-requesting them.  As far as I can tell these parameters were not supported by HelloJS, but they were easy to add.  I will submit some Pull Requests.

I'm guessing these requests don't conform to the normal OAuth spec, but are extra features of Facebook Login.  The only way that I could support them was to edit `hello.js`, but if there's a way to isolate these changes to `facebook.js` then please let me know.

**Comment by MrSwitch** [comment]
Thanks
