### ISSUE TITLE
Updating hello.js

### ISSUE THREAD

**Issue by jgrocha** [MrSwitch/hello.js#210]
Hi,

I was using hello.js with success, but after updating it today, authentication no longer works.

hello:297 Uncaught TypeError: Cannot read property 'response_type' of undefined

```
		//
		// Response Type
		//
		var response_type = provider.oauth.response_type || opts.response_type;
```

Since the error is related to response_type, I added it as a option, but without success.

```
         hello(button.itemId).login({
            scope: "email",
            response_type: "token"
        }, function () {
            console.log('hello("' + button.itemId + '").login');
        });
```

I was using a version from Oct, 30, 2014.

Regards

**Comment by MrSwitch** [comment]
Your provider is undefined. The value of `button.itemId` describes a module that has not been included.

**Comment by jgrocha** [comment]
This is the same code for the old hello (from Oct. 2014) and for the last version. button.itemId can be one of the 3 providers I use: facebook, windows or google. I don't think the name of the providers have changed. I'm logging the name of the provider and it is defined, as expected. I'll do some more debugging to see where is my mistake.

**Comment by MrSwitch** [comment]
It could be your using the core library without the modules, use [dist/hello.all.js](http://adodson.com/hello.js/dist/hello.all.js)

**Comment by jgrocha** [comment]
Yes! Using dist/hello.all.js the autentication is working again.

I also changed:
```js
hello(auth.network).api("me").success(api_me).error(api_me_error);
```
to:
```js
hello(auth.network).api("me").then(api_me, api_me_error);
```

Thank you Andrew.

**Comment by MrSwitch** [comment]
Sorry you had to scratch your head over this. 

Sorry the API spec changed, i hope you prefer Promises, they are here to stay.

Glad you sorted it.
