### ISSUE TITLE
Logout from the provider only if the login was initiated from my app

### ISSUE THREAD

**Issue by jgrocha** [MrSwitch/hello.js#212]
Hi,

I would like to distinguish two situations:

i) the user was already logged in the social network before logged in my app. After logging out from my app, I want that he remains authenticated in the social network.

ii) The user wasn't authenticated before. The user entered his credentials when I initiated the login process. When he logout from my app I also want to finish his authentication from the provider `logout({force: true}, ...`

Does this makes sense? Is it possible to know if the user only started the authentication when we call hello.login?

I tried `hello.getAuthResponse` before `hello.login` but it returns `null` even if the user is already authenticated in the provider. It only works after autentication.

Best regards!

**Comment by MrSwitch** [comment]
@jgrocha i dont think there is a way to do this. And certainly not a standard approach to signing out at all. But your not alone, see #18.

I suggest notifying a user after signout from your app, with a link to facebook and something like, "Click here to also signout from Facebook.com"

Hopefully service providers will take note and stop starting sessions for their main web sites when a user signs-in through a thirdparty app.
