### ISSUE TITLE
Yahoo login problems

### ISSUE THREAD

**Issue by reintroducing** [MrSwitch/hello.js#214]
Thank you for this fantastic library, it has saved me pulling my hair out many times over.  That being said, I'm having issues with Yahoo login.  I see that it's working correctly when I log in on your site but when I try to implement it myself on my own site it's not working.  I get a 404 from GET https://social.yahooapis.com/v1/me/contacts?callback=_hellojs_3dgiabak 

This is my setup: 
Test page lives here: http://dev.reintroducing.com/2015/hellojs/
As you can see Google and Windows works fine, Yahoo does not.

Yahoo app settings have my callback domain set to 'www.reintroducing.com'. I'm not sure if this is correct or not but it would not let me set it to the full URL my "app" lives at like the other services did.

This is my init setup:

```
hello.init({
    google: '***',
    windows: '***',
    yahoo: '***'
}, {
    redirect_uri: 'http://dev.reintroducing.com/2015/hellojs',
    scope: 'friends'
});
```

This is the login:

```
$btnYahoo.on('click', function(evt) {
    hello('yahoo').login({
        force: false
    }).then(requestContacts('yahoo'));
});

function requestContacts(network) {
    hello(network).api('/me/contacts').then(function(r) {
        switch (network) {
            case 'google':
                showGoogleResults(r.data);
                break;

            case 'windows':
                showWindowsResults(r.data);
                break;

            case 'yahoo':
                showYahooResults(r.data);
                break;
        }
    });
}
```

I can't figure out what I'm doing wrong here.  Any help you could offer would be extremely appreciated.

**Comment by reintroducing** [comment]
Just a quick note that right after posting this I realized Yahoo api path is /me/friends and changed it accordingly.  This gave me a 401 Unauthorized from GET https://query.yahooapis.com/v1/yql?q=select%20*%20from%20social.contacts(0)…0guid=me%20limit%20100%20offset%200&format=json&callback=_hellojs_bnpnwfpl 

(if you go to my test link the other services probably won't work because they normally use /me/contacts rather than /me/friends for my purposes but i changed the code above just to test yahoo specifically)

**Comment by MrSwitch** [comment]
Your calling `requestContacts('yahoo')` immediately, you should use bind. e.g.

```javascript
hello('yahoo').api('me/contacts').then( requestContacts.bind(null, 'yahoo') )
```

**Comment by reintroducing** [comment]
@MrSwitch Thanks but that does not seem to have helped. I have actually simplified the code a bit as it was trying to run the requestContacts method twice so I moved that into the 'auth.login' event which solved another issue I was having. That being said, Yahoo doesn't error now but it pops up a window that does nothing and closes right away with no response at all.

If you view source on my test page you can see the new code.  There is a log inside of the requestContacts method that never gets hit for Yahoo.  

Really appreciate your help.

**Comment by MrSwitch** [comment]
Ahh, it might be scope issues. Yahoo's OAuth1 developer apps have to be scoped per app in the registry. See the interface where you were assigned your client id and secret.

Besides that,  I really don't know. Perhaps you can make it available to me.

**Comment by reintroducing** [comment]
I'll take a look at the scope items later today (on train to work now).

When you say make it available to you what exactly do you mean?

**Comment by reintroducing** [comment]
So I changed the app to have permission to all their APIs (because you can't edit it once you create the app and I'd rather not create a new app each time) and I'm still getting the same thing.

I'd be more than happy to make it available to you if you let me know what exactly you mean by that. FTP access?  The whole source code is inline if you view source so you could even test it with your own keys and put it up on a server of your choosing and I'm assuming it would yield the same result, though.

This is really frustrating, I feel like YDN is not helpful at all and half of the time their documentation pages error out.

**Comment by reintroducing** [comment]
Sorry, I don't mean to spam the comments here, but I keep coming across things I want to articulate to you :)

I got it to a different point now.  I explicitly set the redirect_uri for the Yahoo login call to be "http://www.reintroducing.com" and that got me to the popup where I can accept the app and it then redirected me over to my page, except it's my site that lives at www.reintroducing.com opened in the popup which stays open.  When I manually close it I then get an error logged with code: "cancelled" message: "Login has been cancelled".

I suppose you could say thats progress but now I'm wondering how can I automatically close that popup like the other services do and get the data back into my app that I'm wanting in the end.

**Comment by MrSwitch** [comment]
The callback (redirect) page should contain hello.js, and its best if this
is not a heavy page.

Here is an example page http://adodson.com/hello.js/redirect.html please
view the source.

Andrew Dodson | Freelance Web Developer | +61 (0) 452 411 861 |
https://adodson.com

**Comment by reintroducing** [comment]
I got it! that was the key.  Thank you so much @MrSwitch, truly appreciate you helping me out in this and for the fantastic library that normalizes this giant mumbled mess by all providers :)
