### ISSUE TITLE
Better documentation of the oauth proxy flow.

### ISSUE THREAD

**Issue by atrauzzi** [MrSwitch/hello.js#217]
I'm looking to handle the proxy flow for twitter on my own server, but am having difficulties figuring out what exactly hello.js wants in terms of lifecycle.

Is there anywhere that this is better documented, or is there any chance this can be documented if it isn't already?

**Comment by MrSwitch** [comment]
Have you looked at https://github.com/MrSwitch/node-oauth-shim yet?

**Comment by atrauzzi** [comment]
I have, but it seems to skip over detailing important steps such as:

"The OAuthShim signs the client request and redirects the user to the providers login page defined by [OAUTH_AUTHRIZATION_URL]."

That signature process I assume is something I'm going to have to replicate on my end.  Right now all I have my server doing is generating temporary credentials (twitter) and forwarding to the authorization URL.  This appears to succeed, but I'm unclear as to two main things:

 - Where things should be forwarding next
 - What was I supposed to do with the state data?  Hold it on my end, or round trip it via twitter?

**Comment by atrauzzi** [comment]
I've been muddling around and I've got things so far as where I redirect back to my page with hello.js, and it appears to be capturing the state I pass back to it.

Unfortunately, I'm getting back "The authentication was not completed" in my completion handler.  Not entirely sure as to why though as it just gives me that message and nothing else.

**Comment by MrSwitch** [comment]
What language are you using. if your opensourceing it perhaps I could help.

**Comment by atrauzzi** [comment]
I'm using laravel and PHP.  It's a private project sadly, but I think it might be simple enough to know that I have things up to a point where twitter is redirecting directly back to my page with hellojs.  This redirect currently has the parameters `state`, `oauth_token` and `oauth_verifier`.

Is it perhaps that I need to unpack `callback` from state as another get parameter?

**Comment by atrauzzi** [comment]
Also, I noticed that no `_hellojs_*` callbacks are being registered in my originating script.  Have you ever encountered this when hellojs is being used as an NPM module?

**Comment by atrauzzi** [comment]
Alright, more digging and it looks like the callback is getting hit, but it's getting passed "false".  Does that sound like something you might know the cause of?  I'm still tracing through all the code, but I'm having a difficult time isolating where that "false" value is being pulled from.

**Comment by MrSwitch** [comment]
inactive
