### ISSUE TITLE
daily limit for unauthenticated use exceeded. continued use requires signup.

### ISSUE THREAD

**Issue by YairHadari** [MrSwitch/hello.js#220]
Hi,

Thanks for great tool!!!

I"m running the tool from a web browser and getting the following error
"
daily limit for unauthenticated use exceeded. continued use requires signup.
"

When invoking the following lines:
	hello( "google" ).api("me").then(function(json){
		alert("Your name is "+ json.name);
	}, function(e){
		alert("Whoops! " + e.error.message );
	});
Can you please assist?

**Comment by MrSwitch** [comment]
Please refer too https://developers.google.com/+/domains/getting-started#quota

**Comment by YairHadari** [comment]
I solved the issue by registering the application at https://auth-server.herokuapp.com/#-auth-server

Thanks
