### ISSUE TITLE
Adding custom scopes

### ISSUE THREAD

**Issue by jgbarah** [MrSwitch/hello.js#230]
I'm using hello.js with GitHub for getting an OAuth token, and then reading/writing some files. The problem is that i find no way of specifying the realm I need (public_repo), without modifying the code of the github.js module itself. Am I missing something, or really there is no way of specifying other scopes than those in the scope object? (which in the case of GitHub includes only "" and "user:emal").

If I'm right, I wonder if a call could be included in hello.js API to add an arbitrary scope, or maybe an argument to specify an arbitrary scope to hello.login(). I could prepare a pull request, if that would be convenient.

**Comment by MrSwitch** [comment]
Hi @jgbarah 
Sorry for the belated response, HelloJS has always supported custom scopes. 
http://adodson.com/hello.js/tests/specs/?grep=hello.login%20options%20should%20permit%20custom%20scope%20in%20%60options.scope%60%20which%20are%20unique%20to%20this%20service

``javascript
hello('github').login({scope:'public_repo, user:email')
```
