### ISSUE TITLE
Enable hello.js in a Google Chrome extension

### ISSUE THREAD

**Issue by RichardLitt** [MrSwitch/hello.js#233]
I am trying to get hello.js to work in a Chrome extension. It is breaking because the `init()` function requires a `redirect_uri`, but there's [no redirect url](https://developer.chrome.com/extensions/tut_oauth) in the Oauth2 dance for a Google Extension. 

I'm not sure how to change the application name, either. Has anyone else tried implementing hello.js in an extension?

**Comment by MrSwitch** [comment]
I have not, you could use your extension to open up a login page, and use your extension to grab the token after authentication flow.

**Comment by julegatti** [comment]
Oh, I'm wondering the same thing. Did you have success @RichardLitt?

**Comment by RichardLitt** [comment]
Not yet. I'm having issues with the `redirect_uri` field - the response I am getting on load of the popup is a 400 error. Due to encapsulated world issues, I'm using this script to try and make this work. You'll see the `redirect_uri`: however, I get another url back as an error from Chrome.
```js
var el = document.getElementById('hello-google')
el.addEventListener('click', hello('google').login(), false)

hello.init({
  google: 'redacted'
}, {redirect_uri: 'http://www.google.com/robots.txt'});

hello.on('auth.login', function(auth){

  // Call user information, for the given network
  hello( auth.network ).api( '/me' ).then( function(r){
    // Inject it into the container
    var label = document.getElementById( 'profile_' + auth.network );
    if (!label){
      label = document.createElement('div');
      label.id = 'profile_' + auth.network;
      document.getElementById('profile').appendChild(label);
    }
    label.innerHTML = '<img src="' + r.thumbnail + '" /> Hey ' + r.name;
  });
});
```

And the error message: 

```js
scope=https://www.googleapis.com/auth/plus.me profile
response_type=token
redirect_uri=chrome-extension://cmanihjhjdpbdpdgjhbndmpicmkgfdga/content/web/viewer.html?file=http%3A%2F%2Fwww.pnas.org%2Fcontent%2F112%2F5%2F1265.full.pdf
state={"network":"google","display":"popup","callback":"_hellojs_2tuf08l6","state":"","redirect_uri":"chrome-extension://cmanihjhjdpbdpdgjhbndmpicmkgfdga/content/web/viewer.html?file=http%3A%2F%2Fwww.pnas.org%2Fcontent%2F112%2F5%2F1265.full.pdf","scope":"basic"}
display=popup
client_id=undefined
```

I've got no idea why the redirect_uri is being replaced with my chrome extensions URL. I think it might have to do with the PhoneGap support stuff here: https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L1210

**Comment by MrSwitch** [comment]
@RichardLitt not sure if what you wrote was a copy and paste error, because it should look like...

```javascript
...
el.addEventListener('click', function(){hello('google').login();}, false)
...
```

**Comment by RichardLitt** [comment]
![](http://i.ytimg.com/vi/2hlu0qd1Huc/hqdefault.jpg)

Well, that works. Now the pop up is redirected to the page I put in, `robots.html`. I can't see any console logs inside of the watch on `auth.login` - where would I see those?

**Comment by RichardLitt** [comment]
Hmm. So, currently using this code:

```js
var el = document.getElementById('hello-google')
el.addEventListener('click', function () {
  hello('google').login().then(function () {
    alert("You're logged in!")
  })
}, false)

hello.init({
  google: '832850147593-mg2vg2j8j65t3djpsifme57pljgimbl9.apps.googleusercontent.com'
}, {redirect_uri: 'http://www.google.com/robots.txt'})

setInterval(function () {
  var gl = hello('google').getAuthResponse()
  console.log('gl', gl)
}, 3000)
```

The login() and getAuthResponse() functions don't work. My thinking is that I should host a static site somewhere - maybe GitHub pages, or something else - whose only function is to call hello('google').login(), and then send a token somehow back to my extension. I might be wrong in thinking this - how would I grab the token? What do you think? It'd be great to have a flow all set up for future people who might have extensions.

**Comment by MrSwitch** [comment]
I think this environment is a little different from the browser. According to https://developer.chrome.com/apps/app_identity#non it suggests using `chrome.identity.launchWebAuthFlow` to invoke a popup which like in PhoneGap the app has to pick up the `access_token` from a change in the popup's URL.

**Comment by julegatti** [comment]
I though about Identity API, and it should work with OAuth2 non-google providers. In my case I need to work with Twitter API and it still uses OAuth1. Do you think I could use that API somehow @MrSwitch?

**Comment by MrSwitch** [comment]
Hellojs would need to be retro fitted to detect being opened in a chrome
extension and then switch out window.open with the alternative method. Feel
up for it?

**Comment by julegatti** [comment]
Considering your comment and that you're far away better programmer than me, I guess it's not as easy

**Comment by RichardLitt** [comment]
@julegatti `chrome.identity` doesn't work with non-Google providers. They suggest using the `launchWebAuthFlow`, as @MrSwitch pointed out. You can see their documentation on it [here](https://developer.chrome.com/extensions/app_identity#how).

**Comment by julegatti** [comment]
`launchWebAuthFlow` method is part of the `chrome.identity` api.

**Comment by RichardLitt** [comment]
Just reread that section: fair point.

**Comment by RichardLitt** [comment]
@MrSwitch I'm not sure I understand the problem well enough. I've been trying to get OAuth working in my thing for weeks, and the fact that I haven't gotten it yet probably means I shouldn't go around applying patches.

**Comment by MrSwitch** [comment]
See initial hellojs chromeapp demo https://github.com/MrSwitch/hellojs-chromeapp-demo

**Comment by RichardLitt** [comment]
Cool. I ended up going with another Oauth library, but I'll see if I can
check this out at some point.

On Fri, Jul 17, 2015 at 8:56 AM, Andrew Dodson <notifications@github.com>
wrote:

> See initial hellojs chromeapp demo
> https://github.com/MrSwitch/hellojs-chromeapp-demo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSwitch/hello.js/issues/233#issuecomment-122266317>.
>



-- 
Richard | @richlitt <https://twitter.com/richlitt> | burntfen.com
<http://www.burntfen.com>

**Comment by julegatti** [comment]
thanks @MrSwitch! I'll check it out

**Comment by julegatti** [comment]
I can't avoid CSP, it keeps telling:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-Lr9yt-bp6MeRZtE5f6tGEbgywjzlJaxxgI5tV_dqiR0='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by MrSwitch** [comment]
@Julegatti please refer to the chromeapps documentation for how to handle your specific error.

**Comment by julegatti** [comment]
I'd come from there..................................................
