### ISSUE TITLE
Re-authentication - enable switch user

### ISSUE THREAD

**Issue by katysovas** [MrSwitch/hello.js#234]
It seems like re-authentication currently is not supported in hello.js. https://developers.facebook.com/docs/facebook-login/reauthentication

We should be able to re-request permissions if a user denies them. Here is an example case in SO: http://stackoverflow.com/questions/29826881/how-to-re-request-fb-permissions-in-hello-js?noredirect=1#comment47942622_29826881

Also, some prefered scenarios how to handle new FB errors: http://www.adweek.com/socialtimes/facebook-login-errors-best-practices/619364

**Comment by MrSwitch** [comment]
Thanks @katysovas 

I've changed the title to be more generic and apply to all services.

**Comment by MrSwitch** [comment]
Facebook - [auth_type=reauthenticate](https://developers.facebook.com/docs/facebook-login/reauthentication)
Google - [approval_prompt=force](https://developers.google.com/identity/protocols/)
Twitter - [force_login=true](https://dev.twitter.com/oauth/reference/get/oauth/authenticate)
Linkedin - n/a
Windows - doubtful
