### ISSUE TITLE
Linkedin auth(The request is unrecognised)

### ISSUE THREAD

**Issue by VasiliyKomarov1992** [MrSwitch/hello.js#238]
There was a problem.
On the local machine everything works fine.
I can not understand what the problem is.
Browser: Chrome.

![trouble](https://cloud.githubusercontent.com/assets/7386411/7471237/36223566-f32d-11e4-8782-b054458423aa.jpg)

**Comment by MrSwitch** [comment]
Please include the URL of the popup. Thanks

**Comment by VasiliyKomarov1992** [comment]
Request URL:https://auth-server.herokuapp.com/proxy?code=AQTYhXZv--o9IUjc_tkeJaHo1EBeaEjB8_ZV3kbtS_snuZTNRGM6-dPDoyijYoxk0HrcVQgJdnao6_Co1NyeTJN5eI8nUXApIQE-WblDOAPHrSAlZpg&state=%7B%22client_id%22%3A%2277mcgoafggvn3o%22%2C%22network%22%3A%22linkedin%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_3ctnxam%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2F86borders.com%2Fdssb%2FoAuth2SocialNetwork%2Flinkedin%22%2C%22scope%22%3A%22friends%2Cemail%2Cbasic%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22response_type%22%3A%22code%22%2C%22auth%22%3A%22https%3A%2F%2Fwww.linkedin.com%2Fuas%2Foauth2%2Fauthorization%22%2C%22grant%22%3A%22https%3A%2F%2Fwww.linkedin.com%2Fuas%2Foauth2%2FaccessToken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&redirect_uri=https%3A%2F%2F86borders.com%2Fdssb%2FoAuth2SocialNetwork%2Flinkedin

**Comment by VasiliyKomarov1992** [comment]
I really need your help..

**Comment by MrSwitch** [comment]
Hi, i just had a chance to look into this. And the reason was a bad deployment which didn't allow digits in the `redirect_uri`.

Very sorry for the inconvenience you've gone through. This should now be working as expected and the updated tests will prevent it reoccurring again.

**Comment by justinh00k** [comment]
Believe I had this issue trying to use a custom schema as well.
