### ISSUE TITLE
Doesn't work in firefox?

### ISSUE THREAD

**Issue by LIDJungle** [MrSwitch/hello.js#239]
I have my code set up, and oAuth works as advertised in IE and Chrome.

However, with firefox, the callback keeps coming to the pop-up box, with no login information. I never see the auth.login callback fire.

I have a test of this code at: http://shineemc.com/auth2/index.php

It should be as simple as Try it in Chrome and Firefox.

Any suggestions on what I've gotten wrong?

	'use strict';
	hello.init({
		facebook: '1651482XXXXXXXX',
		windows: '00000XXXXXXXX',
		google: 'XXXXXXXXXX-XXXXXXXXXXXXXXXXX.apps.googleusercontent.com'
	}, {redirect_uri: 'http://shineemc.com/auth2/index.php'});

	var app = angular.module('app', []);
	app.service('ngHello', [])
	.provider('hello', function () {
		this.$get = function () {
			return hello;
		};
	})

	app.controller('appCtrl', function ($scope, hello) {
		$scope.userInfo = {name: '', thumbnail: '', authNet: '', loggedIn: false};
		$scope.logmein = function(provider) {
			console.log('provider', provider);
			hello(provider).login();
		}
		$scope.logmeout = function() {
			console.log("logging out of "+$scope.userInfo.authNet+"!");
			hello($scope.userInfo.authNet).logout();
		}
		hello.on('auth.login', function(auth) {
			console.log('we have trapped a logon event.');
			hello(auth.network).api('/me').then(function(r) {
				$scope.$apply(function(){
					$scope.userInfo = {name: r.name, thumbnail: r.thumbnail, authNet: auth.network, loggedIn: true};
				});
			});	
		});
		hello.on('auth.logout', function(auth){
			console.log("We have a logout event.");
			$scope.$apply(function() {
				$scope.userInfo = {name: '', thumbnail: '', authNet: '', loggedIn: false};
			});
		})
	});

**Comment by LIDJungle** [comment]
Error message:

    "Error: u.oauth is undefined
    .login@http://shineemc.com/auth2/js/hello.min.js:1:2042
    $scope.logmein@http://shineemc.com/auth2/js/controller.js:20:4

**Comment by MrSwitch** [comment]
Use `dist/hello.all.min.js``

**Comment by LIDJungle** [comment]
Still not working using hello.all.js

    "provider" "google" controller.js:19:3
    "Error: provider.oauth is undefined
    .login@http://shineemc.com/auth2/js/hello.all.js:298:7
    $scope.logmein@http://shineemc.com/auth2/js/controller.js:20:4

Firefox 37.0.2

**Comment by LIDJungle** [comment]
I've been working with this for a bit... And when I run the demo on your site in Firefox, it works.

The URL returned is correct. If I copy/paste that back into my browser, I'm logged in.

I set my app to use HTTPS, and now I'm getting: 
    
    Error: Permission denied to access property "_hellojs_cqgfye2m"   hello.all.js:1697:0

This looks like a CORS error.

I thought... Maybe it's my Angular stuff getting in the way...

So I slimmed down my code to just:
        'use strict';
	hello.init({
		facebook: '16514XXXXXXXXXXX',
		windows: '0000XXXXXXXXXXXX',
		google: 'XXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com'
	}, {redirect_uri: 'http://shineemc.com/auth2/index.php'});
	hello.on('auth.login', function(){console.log('We have trapped a logon event outside controller.')});

I still get the "Permission denied to access property JSNode" message. It does not get to the point where the console.log message gets written.

---------------------------------------------
When I pipe the URL returned to the popup window, Console messages are as expected.

I know your demo works... But I still can't figure out what I'm doing wrong. Firefox is the only one giving me grief. Thank you.

**Comment by LIDJungle** [comment]
Annnddd.... It works. I had to use the redirect page instead of having the callback come to my index page.

**Comment by MrSwitch** [comment]
Ahh sorry. Your not the fisrt to get caught out by this. I should make a video intro or something.

**Comment by LIDJungle** [comment]
No problem. Even with this hiccup, I'm up and working in half a day (And 37 lines of code!). Considering I've done oAuth before and it's a giant pain... You, sir, are a golden god. Awesome library. The next guy who skims docs like I do will hopefully see this here and David Byrne himself upside the head.
