### ISSUE TITLE
Testing Twitter login on localhost

### ISSUE THREAD

**Issue by shubham-evive** [MrSwitch/hello.js#241]
Is there a way to test twitter login on localhost?

**Comment by MrSwitch** [comment]
Run https://www.npmjs.com/package/oauth-shim in a local nodejs webservice.

**Comment by shubham-evive** [comment]
Will try and see!

**Comment by shubham-evive** [comment]
I am getting a 401 error. Am i missing something?

Server Code 

```
var oauthshim = require('oauth-shim'),
        express = require('express');
 
var app = express();

oauthshim.init({
  'key' : 'secret'
});

app.all('/oauthproxy', oauthshim);

var server = app.listen(3000, function () { console.log('Server Up!'); });
```

Client Code

```
<script src="http://adodson.com/hello.js/dist/hello.all.js"></script>
<script>
	var log = console.log;

	function login(network){
		// Twitter instance
		var twitter = hello(network);
		// Login
		twitter.login().then( function(r){
		    // Get Profile
		    return twitter.api('me');
		}, log )
		.then( function(p){
		   // Put in page
		  document.getElementById('login').innerHTML = "<img src='"+ p.thumbnail + "'  width=24/>Connected to "+ network+" as " + p.name;
		}, log );
	};

	hello.init({
	    'twitter' : 'key'
	},
	{
	      redirect_uri:'/',
	      oauth_proxy: 'http://localhost:3000/oauthproxy'
	});
</script>

<div id="login"></div>
<button onclick = "hello('twitter').login()" >twitter</button>

```

**Comment by MrSwitch** [comment]
Hmm... that should work, accept.

```html
<button onclick = "hello('twitter').login()" >twitter</button>
```
... should be 
```html
<button onclick = "login()" >twitter</button>
```

**Comment by shubham-evive** [comment]
Nope. It doesn't work. The twitter login window just opens and closes immediately.

**Comment by MrSwitch** [comment]
Oh well that's returned something atleast.

What does the error say? print this out like so...

```javascript
function login(){
    hello('twitter').login().then(null, console.log.bind(console));
}
```

**Comment by shubham-evive** [comment]
Here is the error:

```javascript
Object {error: Object, error_message: "401 could not authenticate", state: "", client_id: "twitter-key", network: "twitter"…}
client_id: "twitter-key"
display: "popup"
error: Object
error_message: "401 could not authenticate"
network: "twitter"
oauth: Object
oauth_proxy: "http://localhost:3000/oauthproxy"
redirect_uri: "http://localhost:8000/"
scope: "basic"
state: ""
__proto__: Object
```

**Comment by VasiliyKomarov1992** [comment]
It may be the case in your proxy server? Try to use a default ('https://auth-server.herokuapp.com/proxy'), then you will need to register your application there.

**Comment by shubham-evive** [comment]
@VasiliyKomarov1992 

[https://auth-server.herokuapp.com/proxy](https://auth-server.herokuapp.com/proxy) requires the app to be live, that is a domain name.

I just want to test it on localhost.

**Comment by MrSwitch** [comment]
> https://auth-server.herokuapp.com/proxy requires the app to be live, that is a domain name.

That's not correct, you can use any valid URI address, all its doing it redirecting the browser. So yes you can use //localhost, //localhost:1234, //myprivatedomain/, as well as typical domains, etc...

**Comment by shubham-evive** [comment]
Tried. Still same error.

**Comment by MrSwitch** [comment]
What is the client_id you have added?

**Comment by shubham-evive** [comment]
Its the **Consumer Key (API Key)** in Application Settings of my twitter app.

**Comment by MrSwitch** [comment]
@shubham-evive that's correct. If you wanted me to check what you have inputted to [//auth-server](//auth-server.herokuapp.com) then please let me know the consumer_key/client_id of your application.

I've also documented an [example implementation](https://github.com/MrSwitch/node-oauth-shim/#example) which you can run if you fork [node-oauth-shim](https://github.com/MrSwitch/node-oauth-shim).

**Comment by pdewouters** [comment]
@MrSwitch I also run into the same error.

my client ID is J1jqqO50tcLtLx8Js0VDitjZW

**Comment by MrSwitch** [comment]
@pdewouters the `client_id` exists in //auth-server. Please provide the error message

```
function login(){
  var tw = hello('twitter');
  tw.login().then(console.log.bind(console), console.error.bind(console));

**Comment by pdewouters** [comment]
It says "Could not find the credentials that match the provided client_id. Register your app credentials by visiting https//auth-server.herokuapp.com"

My code

````
  var tw = hello('twitter');
  tw.login().then(console.log.bind(console), console.error.bind(console));

    hello.init({
        'twitter' : 'J1jqqO50tcLtLx8Js0VDitjZW'
    },
    {
          redirect_uri:'/',
          oauth_proxy: 'https://auth-server.herokuapp.com/proxy'
    });
````

**Comment by MrSwitch** [comment]
@pdewouters 

Please confirm, you are calling `hello.init` and setting the client id. Before calling `hello.login`.
Thanks

**Comment by pdewouters** [comment]
thanks for helping me out :) 
if I do 
````

    hello.init({
        'twitter' : 'J1jqqO50tcLtLx8Js0VDitjZW'
    },
    {
          redirect_uri:'/',
          oauth_proxy: 'https://auth-server.herokuapp.com/proxy'
    });

  var tw = hello('twitter');
  tw.login().then(console.log.bind(console), console.error.bind(console));
````

I get

````
Object {error: Object, error_message: "401 could not authenticate", state: "", client_id: "J1jqqO50tcLtLx8Js0VDitjZW", network: "twitter"…}client_id: "J1jqqO50tcLtLx8Js0VDitjZW"display: "popup"error: Objecterror_message: "401 could not authenticate"network: "twitter"oauth: Objectoauth_proxy: "https://auth-server.herokuapp.com/proxy"redirect_uri: "http://localhost:8000/"scope: "basic"state: ""__proto__: Objecthello.utils.extend.Promise.s @ hello.all.min.js:2hello.utils.extend.Promise.i @ hello.all.min.js:2
````

**Comment by MrSwitch** [comment]
What is Object in the context of  `error: Object` ?

**Comment by MrSwitch** [comment]
@pdewouters 
I tried with your token, i got "Desktop applications only support the oauth_callback value 'oob'" from the response body. Looks like you didn't complete all the fields with twitter app registration.

For more information see https://twittercommunity.com/t/desktop-applications-only-support-the-oauth-callback-value-oob-oauth-request-token/252/10

**Comment by MrSwitch** [comment]
@pdewouters 

I just patched //auth-server, so the error message body is returned. Hopefully the next person will have better transparency over what is going on.

**Comment by pdewouters** [comment]
@MrSwitch thank you for your help, really appreciate it. Adding a callback URL did the trick!

**Comment by mzahidriaz** [comment]
we just need to fill the "Callback URL: " input box in the settings. then things will work fine

**Comment by junal** [comment]
@MrSwitch https://auth-server.herokuapp.com/ is down? Not working. Can't register.

**Comment by MrSwitch** [comment]
Thanks @junal it looks to be an issue with Cloudflare i've contacted their customer support. I'm deleting your comment because it has nothing to do with this thread.
