### ISSUE TITLE
Auth-server (application error)

### ISSUE THREAD

**Issue by VasiliyKomarov1992** [MrSwitch/hello.js#244]
together with this "https://github.com/MrSwitch/hello.js/issues/238" problem has another.
Just here "https://auth-server.herokuapp.com/#manage-apps" Have all the applications that I recorded.
Apparently this error occurs as a consequence of the lack of an application on the proxy server, but when I try to re-add, nothing happens. Notification of successful addition does not appear.
![error](https://cloud.githubusercontent.com/assets/7386411/7511630/07c5e6bc-f4af-11e4-884e-ba6c3c6cde43.jpg)

Url: https://auth-server.herokuapp.com/proxy?code=AQQa-L2StF0iU9R_4Xmi4rHThJHphYDV0mnIhxo1v9xeBHipPwjt9xIg5pn5_p16KhwVyRiHpIYK6td3toSkpQHLUu7u-Jw_kgO99mNXG8CaawUI4Eg&state=%7B%22client_id%22%3A%22XXXXXXXXXXXXX%22%2C%22network%22%3A%22linkedin%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_26ukpnlo%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fuat.86borders.com%2Fdssb%2FoAuth2SocialNetwork%2Flinkedin%22%2C%22scope%22%3A%22friends%2Cemail%2Cbasic%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22response_type%22%3A%22code%22%2C%22auth%22%3A%22https%3A%2F%2Fwww.linkedin.com%2Fuas%2Foauth2%2Fauthorization%22%2C%22grant%22%3A%22https%3A%2F%2Fwww.linkedin.com%2Fuas%2Foauth2%2FaccessToken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&redirect_uri=https%3A%2F%2Fuat.86borders.com%2Fdssb%2FoAuth2SocialNetwork%2Flinkedin

When I try to add application.
![error2](https://cloud.githubusercontent.com/assets/7386411/7511745/03482fe0-f4b0-11e4-8e95-a9560b3e82a6.jpg)

**Comment by MrSwitch** [comment]
Service is down, looking to restore it soon

**Comment by VasiliyKomarov1992** [comment]
Thank you very much for your reply.
If you have time, please see "https://github.com/MrSwitch/hello.js/issues/238".

**Comment by MrSwitch** [comment]
//auth-server was refreshed 12 hours ago, so far so good.
