### ISSUE TITLE
Application has not been authorized for the scope "r_fullprofile"

### ISSUE THREAD

**Issue by VasiliyKomarov1992** [MrSwitch/hello.js#246]
When we open for authorization is not loaded form of authentication.
Returns this url: 

https://86borders.com/dssb/oAuth2SocialNetwork/linkedin?error=invalid_scope&error_description=Your+application+has+not+been+authorized+for+the+scope+%22r_fullprofile%22

Locally, too, did not work, but yesterday everything was fine.
The application allowed access to this field.

hello.js(linkedin):
		scope : {
			basic	: 'r_fullprofile',
			email	: 'r_emailaddress',
			friends : 'r_network',
			publish : 'rw_nus',
			contact_info : 'r_contactinfo'
		},

	hello.init({ 
			linkedin   : 'CLIENT_ID'
		},
		{
			scope : ['contact_info','email'],
			redirect_uri: 'https://86borders.com/dssb/oAuth2SocialNetwork/linkedin'
		}
	);
If the 'scope' add 'basic', nothing will change.

![error](https://cloud.githubusercontent.com/assets/7386411/7607192/23d7f936-f968-11e4-8fec-d6bd387bff09.jpg)

**Comment by VasiliyKomarov1992** [comment]
Oh .. I found the reason. If we uncheck "r_fullprofile" and "r_contactinfo", they will disappear. Apparently linkedin changed access to the fields. 
You will probably need to improve 
		scope : {
			basic	: 'r_basicprofile',    // 'r_fullprofile'
			email	: 'r_emailaddress',
			friends : 'r_network',
			publish : 'rw_nus',	
		},

![error](https://cloud.githubusercontent.com/assets/7386411/7607834/3c62cca6-f96d-11e4-81af-e556ba7092f9.jpg)

**Comment by jblandry** [comment]
Made a PR #247

**Comment by totymedli** [comment]
For people searching by the error message: Default Application Permissions changed so **`r_basicprofile` has to be used instead of `r_fullprofile`**.

**Comment by adil26** [comment]
How can I add or change this permissions from linkedin app?
