### ISSUE TITLE
me/share picture

### ISSUE THREAD

**Issue by FunnyDevs** [MrSwitch/hello.js#248]
I have to upload a state, inserting message and photo and i have a photo in base64; is possibile to upload it (not using me/albums)????

Thanks

**Comment by MrSwitch** [comment]
Yes but your mileage may vary and `me/share` a media flle hasn't been implemented with other providers besides twitter. See http://adodson.com/hello.js/tests/#hello-x-api-path--method--data--callback--

**Comment by MrSwitch** [comment]
Close due to inactivity
