### ISSUE TITLE
Auth-server (Unable to add the application.)

### ISSUE THREAD

**Issue by VasiliyKomarov1992** [MrSwitch/hello.js#249]
Hi.
I can not add an application to this address "https://uat-useast.starpoundtech.net/dssb/". Notifications about success does not appear.
However, the application with this address "https://uat.86borders.com/dssb/" successfully added.

**Comment by MrSwitch** [comment]
Can you have a look at the browser console, there should be error messages in the POST response.

**Comment by VasiliyKomarov1992** [comment]
Yes no problem.
![error](https://cloud.githubusercontent.com/assets/7386411/7880557/63a80342-0603-11e5-9c99-29b68069d6c9.jpg)

**Comment by MrSwitch** [comment]
I've removed the length restriction issue on //auth-server field.
