### ISSUE TITLE
Twitter access token & secret?

### ISSUE THREAD

**Issue by gRoberts84** [MrSwitch/hello.js#253]
Hi there,

It's early here and I really need coffee, so sorry if this makes no sense or I'm being stupid.

When successfully logging into Twitter using `hello('twitter').login()...` the response back only contains the access_token, however I need an access_secret.

Basically I am writing an app that uses the stream however I want to be able to use the customers account without them having to create an app and insert the consumer and access keys etc.

Is it possible to return the access_secret from your oauth proxy?

Thanks

Gav

**Comment by VasiliyKomarov1992** [comment]
Maybe I'm wrong, but "access_token = access_secret + client_id". In fact it is the terms of use protocol Oauth.

**Comment by gRoberts84** [comment]
Hmmm, I suppose the issue I have is whether I can authenticate the Twitter Streaming API using the access_token instead of the Consumer & Access key/secrets that you get from dev.twitter.com.

**Comment by MrSwitch** [comment]
I'm not familiar with the Twitter Streaming API, the quick look i took didn't say it was different from any other OAuth1 request.

**Comment by gRoberts84** [comment]
Hey @MrSwitch, thanks for getting back to me,

Basically the streaming API needs the consumer key/secret and access token/secret. 

What a spooooon I am... Just noticed the following:

access_token: "xxxx-xxxx:xxxx" which is access_token:access_secret.

Sorry, I didn't look at it close enough. With this, I can use my consumer key details and the customers access details to authenticate :)

Thank you

**Comment by infernalmaster** [comment]
Now access_token (tested for twitter) looks like that "access_token:access_secret@somehting_else".

It would be nice if that fact was mentioned in **documentation**. My use case is very simple: get acces token and send it to backend.

**Comment by MrSwitch** [comment]
@infernalmaster Its actually the old oauth1 spec so... `oauth_token:oauth_token_secret@consumer_key`. It is used by [oauth-shim](https://github.com/MrSwitch/node-oauth-shim) please add it to the README. Thanks

**Comment by jmgamboa** [comment]
So there is a prefix to the access token "xxxx-xxxxxx" where the first part is the client id. is that part of the access token itself or are you concatenating the id with the actual access token.

**Comment by gRoberts84** [comment]
From what I recall, it's:

I.e.

TOKEN:SECRET@CONSUMER_KEY

**Comment by jmgamboa** [comment]
@gRoberts84 after looking at my own access token in the twitter api tool, i think its ok to assume that the prefix on the access token which is "clientid-" is also part of the raw access token 

so
access_token = "clientid-token"
