### ISSUE TITLE
IE10:  Popup window non-resizeable, no scrollbars, user cannot accept or decline authorization

### ISSUE THREAD

**Issue by cookch10** [MrSwitch/hello.js#254]
I am using `hello.js` (dist) version 1.6.0 and am seeing an issue in Internet Explorer 10 (IE10) where the popup window (authenticating with Google) does not allow resizing, and also does not have scroll bars, preventing the user from clicking the "Cancel" or "Accept" buttons.  See the following screenshot:

![2015-05-22_1255](https://cloud.githubusercontent.com/assets/6051695/7775640/d658d050-0082-11e5-945d-4f0d48c45283.png)

I found that making the following change to `hello.js` solves the issue by adding vertical scroll bars to the popup window (line 1325 - 1329):

current code:
```javascript
var popup = window.open(
    url,
    '_blank',
    'resizeable=true,height=' + windowHeight + ',width=' + windowWidth + ',left=' + left + ',top=' + top
);
```

code that fixes the issue:  add a `scrollbars` parameter in the call to `window.open`, which adds vertical scrollbars to the popup window:
```javascript
var popup = window.open(
    url,
    '_blank',
    'resizeable=true,scrollbars,height=' + windowHeight + ',width=' + windowWidth + ',left=' + left + ',top=' + top
);
```

**Comment by anuradhag** [comment]
Same behavior in firefox too
