### ISSUE TITLE
bool is not defined

### ISSUE THREAD

**Issue by constellates** [MrSwitch/hello.js#256]
I'm trying to use hello.js for the first time to authenticate with google OAuth2 and although everything seems to be functionally working I'm getting "bool is not defined" logged to the console every time google redirects back to my application. I believe this error is logging through the first catch block of the following globalEvent function.

	// Global Events
	// Attach the callback to the window object
	// Return its unique reference
	globalEvent: function(callback, guid) {
		// If the guid has not been supplied then create a new one.
		guid = guid || '_hellojs_' + parseInt(Math.random() * 1e12, 10).toString(36);

		// Define the callback function
		window[guid] = function() {
			// Trigger the callback
			try {
				bool = callback.apply(this, arguments);
			}
			catch (e) {
				console.error(e);
			}

			if (bool) {
				// Remove this handler reference
				try {
					delete window[guid];
				}
				catch (e) {}
			}
		};

		return guid;
	},

Let me know if you have an idea what could be causing this or if there's further information I could provide regarding this issue.

**Comment by MrSwitch** [comment]
I can't see any thing like that (tested on Chrome), please check your implementation with something like the demo http://adodson.com/hello.js/demos/google.html.

**Comment by constellates** [comment]
Thanks for the response. I believe I found the issues and it is due to how I was bringing hello.js into my app. I'm using browserify and ES6 and was trying to pull the library into my app using the following syntax.
    import hello from '../path/to/hello.js';

If I remove that line and just include hello through a script tag in my index.html the error goes away. So it looks like the way I was importing hello.js was probably not including some parts. Let me know if you happen to know how or if I can incorporate this library using browserify/require/import syntax otherwise I'm sure I can figure it out now that I know what the issue is. 

Thanks.

**Comment by MrSwitch** [comment]
The dist/` folder contains hellojs packs which are bundled to be compatible with CommonJS format, if this isn't working for you then it would be good to know the problem. Thanks
