### ISSUE TITLE
Hello.js Dropbox access_token is stripped from download links

### ISSUE THREAD

**Issue by ThomasBird1984** [MrSwitch/hello.js#257]
When a request is made to Dropbox method `me/files`, in file `hello/src/modules/dropbox.js` on `line 201` the:

`req.query.access_token` is undefined even though I have explicitly passed the token from the request. 

The reason is that in `hello/dist/hello.js` in the `formatUrl()` method the access_token is being deleted from the object on `line 2118`.

This is causing the return object from the `me/files` api request to return back unsigned download links.

**Comment by MrSwitch** [comment]
Sorry for the belated response. This was a bug in the property it was getting the token from. Thanks for bringing it to our attention.

**Comment by ThomasBird1984** [comment]
Awesome thanks for the help!
