### ISSUE TITLE
Сan't authenticate linkedin internet explorer.

### ISSUE THREAD

**Issue by VasiliyKomarov1992** [MrSwitch/hello.js#259]
It appears popup. Next we enter data for authorization. Then the popup loads the page (redirect_uri), although it should send the data to us on the page and close. In other browsers everything works fine.
url popup: ‎
https://uat.86borders.com/dssb/authLinkedinInfo?code=AQSHOVDz73XnzdxSDg4VoYQ0vcGAD3UIZaPzeI4rddTJAybB6usEbF6t6D6A8H342ahviR5wwveZsgBn7jGp_cZiuRvJud-orqwKbzlfIyJEOn4bTL8&state=%7B%22client_id%22%3A%22XXXXXXXXXXXXXX%22%2C%22network%22%3A%22linkedin%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_ls67yx9%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fuat%2E86borders%2Ecom%2Fdssb%2FauthLinkedinInfo%22%2C%22scope%22%3A%22email%2Cbasic%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22response_type%22%3A%22code%22%2C%22auth%22%3A%22https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fuas%2Foauth2%2Fauthorization%22%2C%22grant%22%3A%22https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fuas%2Foauth2%2FaccessToken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server%2Eherokuapp%2Ecom%2Fproxy%22%7D

There is a problem as well and on the local machine. (also only in Internet Explorer)

URL popup: 
http://vkomarov:5050/dssb/authLinkedinInfo?code=AQRZ1i2giU-I3VReCNWnPRUHKUXyd7dG1qKUDbE9EKnb8cC_JsIKlvwonzGMlNksDr6lQaUMh32N7jCRB4MFiZM4AFitWOZF07s4r9KeGLb5JSHouJI&state=%7B%22client_id%22%3A%22XXXXXXXXXXXXXX%22%2C%22network%22%3A%22linkedin%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_5jb7fbl0%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22http%3A%2F%2Fvkomarov%3A5050%2Fdssb%2FauthLinkedinInfo%22%2C%22scope%22%3A%22email%2Cbasic%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22response_type%22%3A%22code%22%2C%22auth%22%3A%22https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fuas%2Foauth2%2Fauthorization%22%2C%22grant%22%3A%22https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fuas%2Foauth2%2FaccessToken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server%2Eherokuapp%2Ecom%2Fproxy%22%7D

**Comment by VasiliyKomarov1992** [comment]
I apologize, as I wait for the answer you need to wait? Just over a month has passed.

**Comment by MrSwitch** [comment]
@VasiliyKomarov1992 sorry you haven't had a prompter response. I just tried and had no problems and managed to signin to your uat site using IE 11.

**Comment by VasiliyKomarov1992** [comment]
@MrSwitch 
Yes, I see now it works.
 Can I ask you to try here? Https: //86borders.com/dssb/

 Sign up and go to Edit Profile.
 There is a button IMPORT WITH LINKEDIN. If you try to go to the login linkedin, it is what I wrote.

**Comment by VasiliyKomarov1992** [comment]
There is also a problem with mac os safari.
When we click on the button, and the login window appears for authentication, then an error in the console.

![screen shot 2015-07-07 at 9 51 01 am](https://cloud.githubusercontent.com/assets/7386411/8547583/8fed9b4a-24c8-11e5-9a97-9b0a2af23c80.png)

**Comment by VasiliyKomarov1992** [comment]
Hello. I will appreciate if you can help me.
The problem still remains.
When a popup window, and I enter the password and login to linkedin, it can not be closed and no data are obtained. There is an error in the log of the pop-up window. (in other browsers everything works well.)
![sss](https://cloud.githubusercontent.com/assets/7386411/12053468/7ee0dd8e-af2a-11e5-8d24-53c52af1c5ce.jpg)

**Comment by MrSwitch** [comment]
Please update to the latest version of HelloJS. FYI: There has been a lot of changes in LinkedIn API permission, for instance the 'friends' or as LinkedIn refers to it as "connections" is no longer an available without being whitelisted by LinkedIn. Since my app wasn't whitelisted i'm unable to maintain this part of the LinkedIn API.

**Comment by VasiliyKomarov1992** [comment]
@MrSwitch 
Thank you very much, it helped me.
