### ISSUE TITLE
Using hello.js with react-router

### ISSUE THREAD

**Issue by tiffting** [MrSwitch/hello.js#260]
I'm trying to switch my React project to use [react-router](https://github.com/rackt/react-router) instead of [director](https://github.com/flatiron/director), but in the process, it seems that hello.js no longer works. Something appears to affect how hello.js sets the client_id in the Instagram API call. The errors I'm getting look like this:
* Facebook: `2500: An active access token must be used to query information about the current user.`
* Instagram: `{"code": 400, "error_type": "OAuthException", "error_message": "Invalid scope field(s): "}`

**Comment by MrSwitch** [comment]
So i'm not sure about the React Router looks like its failing to authenticate. Can you share your code.

ps: sorry for belated response.

**Comment by tiffting** [comment]
We were able to resolve the issue by refactoring our code. Thanks!
