### ISSUE TITLE
identify whether user logged in or not on page load...

### ISSUE THREAD

**Issue by uidev547** [MrSwitch/hello.js#263]
Hi first of all Thanks for the wonderful library.

is there any way to identify whether user is logged with any of the accounts( google, facebook, or etc )  on page load?
or 
is there any way of identifying by which network he is logged in?

Thanks

**Comment by nop33** [comment]
You can use `getAuthResponse` (check [here](http://adodson.com/hello.js/#hellogetauthresponse))
```javascript
if(hello.getAuthResponse(network)) {
    // User is logged in 
}
```
where `network` is the string name of the service

**Comment by uidev547** [comment]
thanks for the reply. but how do we know by which network user logged in.
do we need to check each and every network the hello.js supports?
( dropbox, facebook, flickr, foursquare, github, google, instagram, linkedin, soundcloud, twitter, windows, yahoo )

Thanks

**Comment by nop33** [comment]
It depends, are you using all of these on your application? You only need to check which out of the hello.js services that you are using has the user used to login. If they are really so many perhaps you could create a list of services and loop over them to find the one the user used to login.

I am not aware of any other way to check with service the user used, can’t find anything in the docs.

**Comment by uidev547** [comment]
Ok thanks. i could see some info in the localStorage even after the logout ( i did not see which info it is ). I'll try to read the localStorage data and check if any info available regarding the network.

Thanks

**Comment by MrSwitch** [comment]
Please see the demo https://adodson.com/hello.js/demos/login-events.html
