### ISSUE TITLE
Typing a hashtag into the tweet message breaks the tweet at the hash

### ISSUE THREAD

**Issue by sudheesh001** [MrSwitch/hello.js#269]
eg.
API : /me/share

message : Checking if the test breaks because of a hahtag , #ThisIsATest Did you see a hashtag ?

Actual result https://twitter.com/sudheesh001/status/611794814879813632

**Comment by prasht63** [comment]
A possible solution is to escape the message before Posting it
eg.
var tweet=escape(message);
then post the tweet as
..
{
message:tweet
}
..

**Comment by sudheesh001** [comment]
This issue is not with respect to the implementation with `escape()` or `encodeURIComponent()` but rather that the hello.js api test interface itself should allow for tweets with hashtags to be posted by default from that application.

**Comment by MrSwitch** [comment]
Thanks @sudheesh001
