### ISSUE TITLE
Hello-JS For Hybrid Application

### ISSUE THREAD

**Issue by murliatdure** [MrSwitch/hello.js#273]
Hello,
First-of all thanks for serving a nice library for easing the social interaction automation.

I tried the same for social login - 
My application is hybrid using phone-gap.

1. I am able to achieve the same using the PG build
2. The same code is not working for the web version 
The control goes to the redirect URL, but this won't close. Whenever I tried to close this manual/js the operation get cancelled.

Please assist me on this.
Thanks,

**Comment by murliatdure** [comment]
![image](https://cloud.githubusercontent.com/assets/7137859/8371231/2edcd368-1bf2-11e5-97b5-9c1677f67c09.png)

**Comment by MrSwitch** [comment]
Can you share the URI parameters of the page it is hanging on without closing?

**Comment by murliatdure** [comment]
I tried to provide the absolute URL (http://www...index.html), It works.
Thanks alot.
