### ISSUE TITLE
Support explicit flows during popup

### ISSUE THREAD

**Issue by atrauzzi** [MrSwitch/hello.js#279]
Whenever I do the explicit flow from a popup, I end up with a page that contains my server's JSON success output.

Is there a way, or wouldn't it make more sense, to have hellojs to capture those values and return them to the calling script (the one that created the popup)?  At that point the flow could likely be considered complete because the redirect has already hit my server.

**Comment by MrSwitch** [comment]
Your suggestion is what HelloJS expects to happen. The issue is therefore why is your sever returning JSON. The node-oauth-shim will return error messages in JSON, perhaps that is what you are seeing.

**Comment by atrauzzi** [comment]
I'm not using the node server as my project is PHP.  I've got most things working, but in this case I appear to be tracing it down to the state variables, specifically `page_uri` not making it back to my server.

**Comment by atrauzzi** [comment]
(this is a new combination, as I was using the non-popup flow up until facebook and google forced their own frame recently)

**Comment by atrauzzi** [comment]
(also, I'm noticing that `page_uri` isn't really mentioned much in the docs, do you have any detailed information about it?)

**Comment by MrSwitch** [comment]
https://adodson.com/hello.js/demos/login.html#hellologin-displaypage

**Comment by atrauzzi** [comment]
Is it possible that this isn't being round-tripped during the `popup` flow?

**Comment by MrSwitch** [comment]
This is ignored in the popup flow, only relevant if `display=page`

**Comment by atrauzzi** [comment]
Ah... So when my popup gets redirected to my server, would you happen to know of anything I can use to infer that the request originated from hellojs and that it needs to receive information to pass back to the initial instance of hellojs?

Or should I be getting the social provider to redirect to that page via `redirect_uri` with the code and then manually send the code to the server?

**Comment by atrauzzi** [comment]
Perhaps this could be solved by including `page_uri` during `popup` flows?

**Comment by MrSwitch** [comment]
It sounds like you want the access_token on the server to perform federated authentication please see comments on this issue https://github.com/MrSwitch/hello.js/issues/22

Otherwise i recommend not rehashing this in PHP if your stumbling. And instead register your keys at https://auth-server.herokuapp.com/ OR create your own instance of that nodejs service and redefine the `oauth_proxy` option using `hello.init(creds, options)`.

**Comment by atrauzzi** [comment]
Running nodejs is not an option for me, and I'd prefer to not have to use a 3rd party service at present.

I've got a pretty workable Laravel-Socialite-based PHP implementation so far which I'm more than happy to release as a package once things are sorted out.  My hope though is to get as many of these situations covered.

Given that many social login providers added `X-Frame-Options` to `DENY`, I suspect some `page` based flows are broken right now.  As a result, I'm trying to come up with something equivalent via popups.

**Comment by atrauzzi** [comment]
Sorry, just to be clear -- is there a reason why `page_uri` couldn't be used during `popup` flow?  I'm not trying to circumvent any security measures.  It would give me the needed value to then redirect back to hellojs in the response my generates for the popup, which would then give hellojs the opportunity to close the popup and return a success.

**Comment by MrSwitch** [comment]
In the popup flow the Page uri is redundant, the popup closes once the page returns to the redirect uri upon completing the authorization flow. 

Page uri's intention is to resolve the issue created using 'display=page' whereby the browser remains on the redirect uri page after login. The page_uri gives the hello.js script running on redirect uri page the chance to flow the user on to a more meaningful page which pertains to the initial login event.

I hope that makes sense, it is not for the server to worry about it is a feature of the javascript library.

**Comment by atrauzzi** [comment]
It all makes sense in the end.  I'm probably not quite as confused as you're thinking - although slightly none the less.

The use case you've described here could equally apply as a way to allow both `redirect_uri` and `page_uri` to be used during a popup flow though, could it not?

```
Page
    \----> Popup ---> Facebook ---> My Server
```

In this sloppy diagram, the interaction between `Page` and `Popup` is hellojs (we know this).  Why not allow `page_uri` to be present during these flows so that `My Server` in this case can redirect back to the URI of `Popup`?  I guess the problem might be that there has to be some agreed upon payload that `My Server` includes in the redirect to `Popup` to make this happen?

At the end of the day, what you're saying is `redirect_uri` should be set to my page hosting hellojs, and I should ferry the code back to the server myself.  Which sounds pretty normal and I can totally do.

Anyway, that flow above there might be a neat feature one day, but perhaps redundant.

**Comment by MrSwitch** [comment]
> Why not allow page_uri to be present during these flows so that My Server in this case can redirect back to the URI of Popup

I said...
> the popup closes once the page returns to the redirect uri
btw: i say page, i mean that interchangeably with 'window', so to save confusion the above statement should probably be better written."the popup closes once it is returned to the address defined by redirect_uri."

If you want the popup to remain open and again go to another page then why not just launch a popup manually which loads hello.js and initiates the auth-flow from there using 'display=page'

**Comment by atrauzzi** [comment]
Nono, I want it to close.  But my `redirect_uri` for the example above was my server, not my popup.

**Comment by MrSwitch** [comment]
> was my server, not my popup

I dont understand

**Comment by atrauzzi** [comment]
Instead of redirecting back to the page hosting hellojs, I was redirecting to my server to complete the flow.
