### ISSUE TITLE
Infinite loop (localStorage)

### ISSUE THREAD

**Issue by joeltello** [MrSwitch/hello.js#281]
I randomly get my app looping/refreshing without stopping. In order to fix it I have to clear the "hello" key from my localStorage. I am not sure what could be causing this, I have been testing it and trying to find the cause but nothing so far. 

Something to consider is that hellojs runs inside an iframe. This iframe has the authentication process and is the one that gets refreshed every 2 seconds until I clear the localStorage.

Any ideas?

**Comment by joeltello** [comment]
I think I found the issue. The problem is that inside "hello" key the library stores the access token (I assume the reason is for checking that the session is valid). For facebook the token expires in 1 hour, when that happens my iframe starts looping like crazy.

**Comment by MrSwitch** [comment]
I dont know what the reason could be. Perhaps loading HelloJS library more that once might be causing it?

**Comment by joeltello** [comment]
But this only happens when the access_token stored in localStorage has expired, if you remove it the refreshing/looping will stop.

**Comment by joeltello** [comment]
I wonder if the library tries to refresh that token after it expires, and since it is running inside an iframe it fails causing an infinite loop

**Comment by MrSwitch** [comment]
Please debug this, FYI the refresh is triggered on this line https://github.com/MrSwitch/hello.js/blob/v1.7.2/src/hello.js#L1576

**Comment by MrSwitch** [comment]
inactive
