### ISSUE TITLE
Get my Facebook wall posts

### ISSUE THREAD

**Issue by IrvinDominin** [MrSwitch/hello.js#285]
I'm using Hello.Js to get my Facebook wall posts. To doing so I have registered my demo app on developer.facebook.com (using a localhost url).

My hello.js setup is the following:

    hello.init({
        facebook: '<mykey>'
    },
    {
        redirect_uri: 'redirect.html',
    });
and this is the Facebook login:

    var onFacebookError = function (e) {
        $facebookEl.text(e.error.message);
    };

    // Facebook instance
    var facebook = hello('facebook');

    // Login
    facebook.login().then(function (r) {
        // Get Profile
        facebook.api('me').then(function (p) {
            $facebookEl.html('<span><img src="' + p.thumbnail + '" width=50 class="roundedAvatar" />    <span style="margin-left: 15px;">Connected to Facebook as ' + p.name + '</span></span>');
        }, onFacebookError);
    }, onFacebookError);
The OAUth connection is working fine, but when I try to get my wall post, using:

    // Facebook instance
    var facebook = hello('facebook');        

        facebook.api('facebook:/me/share', function (r) {
        var posts = [];
        for (var i = 0; i < r.data.length; i++) {
            var o = r.data[i];
            posts.push({ social: 'facebook', text: o.text });
        };
    });
I get and empty r.data result.

What can the issue be? Do I have to enable other permissions on the Facebook app?

Ref: http://stackoverflow.com/questions/31333751/get-my-facebook-wall-posts

**Comment by MrSwitch** [comment]
Facebook changed this endpoints scope, for a restricted scope `user_posts`, see https://developers.facebook.com/docs/apps/changelog. 

I've just requested access because its now broken for HelloJS site.

**Comment by IrvinDominin** [comment]
Hi Drew, 

thanks for the support, just a question, how do I have to make the request for `user_post` permission on my account?

**Comment by MrSwitch** [comment]
For now ...

```javascript
hello('facebook')
.login({scope:'user_post'})
.then(handleResponse);
```

**Comment by IrvinDominin** [comment]
I tried but I get:
![image](https://cloud.githubusercontent.com/assets/1533624/8648766/b85d105c-2963-11e5-8d50-501586b4e4d3.png)

The code is:

    facebook.login(({ scope: 'user_post' })).then(function (r) {
        // Profile
        facebook.api('me').then(function (p) {
            $facebookEl.html('<span><img src="' + p.thumbnail + '" width=50 class="roundedAvatar" /><span style="margin-left: 15px;">Connected to Facebook as ' + p.name + '</span></span>');
            }, onFacebookError);
        }, onFacebookError);

Where is my issue, or am I missing something?

Many thanks.

**Comment by MrSwitch** [comment]
Sorry "user_posts" with an 's' on the end.

**Comment by IrvinDominin** [comment]
Oh yes, I RTFM :-) just seen in the facebook doc: https://developers.facebook.com/docs/apps/changelog.
