### ISSUE TITLE
Question: Share Facebook Account between Phonegap and Website

### ISSUE THREAD

**Issue by sabkaraja** [MrSwitch/hello.js#286]
Hi

Thanks for the app. It really makes life easy. However I am stuck in a dilemma. I have a website and an app which has the same FB app id. I want to allow the user to register on the website or on the app and work seamlessly.

However, in the FB app, I have set the redirect url to the domain script (http://doma.in/users/oauth/....)
Now if I set the redirect_uri to redirect.html OR localhost, Facebook throws an error. Am I doing something wrong?

**Comment by MrSwitch** [comment]
>  I have set the redirect url to the domain script (http://doma.in/users/oauth/....)

That sounds right. i.e. you'd write the full path to this in your Phonegap app.

```
hello.init(credentials, {
     redirect_uri: "http://doma.in/users/oauth/redirect.html"
});
```

**Comment by MrSwitch** [comment]
inactive
