### ISSUE TITLE
Be able to post lat, long as additional parameters with the tweet

### ISSUE THREAD

**Issue by sudheesh001** [MrSwitch/hello.js#294]
/me/share POST API for twitter supports adding new parameters
but using
```
lat <floating number>
long <floating number>
```
doesn't post the tweet with the geo information. This is supported by the Twitter API here at
https://dev.twitter.com/rest/reference/post/statuses/update

as optional parameters

**Comment by MrSwitch** [comment]
Do you want to try editing the `src/modules/twitter.js` to accomodate this, and contribute a PR back?

**Comment by sudheesh001** [comment]
@MrSwitch i've given it a shot, Could you review it and let me know if this would work ?

**Comment by MrSwitch** [comment]
FYI: can run the `npm install -l` followed by `grunt test` to see where its failing the build.

**Comment by sudheesh001** [comment]
@MrSwitch I guess its fine now with the new rebased commit. Looks like `long` being a reserved work was creating an issue in dot notation.
