### ISSUE TITLE
"Protocols must match" Security error on cordova app when token refreshed

### ISSUE THREAD

**Issue by dospiau** [MrSwitch/hello.js#298]
In version 1.7.2. To reproduce:
1. You must have google refresh_token first, so login using oauth proxy
2. Change expires date stored in hello.js localStorage
3. Run ```hello.init``` : there is interval which is checking if token expired and tries to run ```hello.login(name, {display: 'none', force: false});``` to refresh it as a result 
4. Uncaught SecurityError: Blocked a frame with origin "https://mysite.com" from accessing a frame with origin "file://".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.

Am I missing some cordova settings? Allow origin is set to "*"

**Comment by MrSwitch** [comment]
FYI: you can probably recreate this by simply running. 

```
hello.login('network', {display: 'none', force: false});
```

I dont think this feature is correctly implemented. There was a proposal along to not use an iframe and instead use "hidden=true" into `window.open(.., .., options)`. Sorry, that could have done with more attention to testing different platforms etc...

Lets revisit this here.

**Comment by dospiau** [comment]
Here is what I found out testing refresh token and OAuth on different versions of hello.js on desktop and cordova:

From version 1.7.0 hello.js do not store data in localStorage, which means that refresh_token is valid as long app is running, is it intentional? In 1.6.0 it was stored.

In 1.6.0 refresh works fine on Chrome but does not work on Cordova. Funny thing as cordova usually has less strict security settings. I tried with different configurations of cordova-white-list plugin.

**Comment by dospiau** [comment]
I was testing some solutions on version 1.6.0.

I changed line with ``` this.append('iframe' ..``` to ``` window.open(src,'_blank','hidden=yes');``` no security error but no luck with updating token, can You point me to code where new token is obtained? I am having trouble finding it.

**Comment by dospiau** [comment]
I managed to patch version 1.6.0, but I am having some problem with building project, minified version is borken, but works fine if I use different minifier, I can create PR from our fork for You to check it.

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm <x-apple-data-detectors://2> I keep my lights
on!
We have really cool stuff!
Have a good weekend!

On Thursday, July 30, 2015, dospiau <notifications@github.com> wrote:

> In version 1.7.2. To reproduce:
> 1. You must have google refresh_token first, so login using oauth proxy
> 2. Change expires date stored in hello.js localStorage
> 3. Run hello.init : there is interval which is checking if token expired
> and tries to run hello.login(name, {display: 'none', force: false}); to
> refresh it as a result
> 4. Uncaught SecurityError: Blocked a frame with origin "https://mysite.com"
> from accessing a frame with origin "file://". The frame requesting access
> has a protocol of "https", the frame being accessed has a protocol of
> "file". Protocols must match.
>
> Am I missing some cordova settings? Allow origin is set to "*"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSwitch/hello.js/issues/298>.
>


-- 
Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052

**Comment by MrSwitch** [comment]
[Released v1.9.0](https://github.com/MrSwitch/hello.js/releases/tag/v1.9.0)
