### ISSUE TITLE
http status codes are muted by util.request method of helloJS

### ISSUE THREAD

**Issue by Deminem** [MrSwitch/hello.js#299]
We can see that for XHR callbacks, the http status codes are return back through headers in the callback. But the http error codes are not return for other fallback methods such as (JSONP and Form post) and also for error conditions.

Can you please not mute the http status codes in all the above scenarios? Thanks.

**Comment by MrSwitch** [comment]
Could you propose a code change via a PR?

Thanks

**Comment by MrSwitch** [comment]
inactive
