### ISSUE TITLE
Accessing "raw" API response / using redirect=false

### ISSUE THREAD

**Issue by jonathanazulay** [MrSwitch/hello.js#304]
Hello
I would like to use `redirect=false` in order to know if a Facebook user uses the default profile picture.  But the normalized hello.js response does not include the `is_silhouette` attribute.

Is there a way to access the original response from the API? Or any other way of solving this problem?

This is the query I'm using
`/me?fields=picture&redirect=false`

If this is not possible, one idea would be to simply add the raw data to the callback (as a feature). I think it could be useful

    hello('facebook').api('/me?fields=picture&redirect=false')
    .then(function (json, raw) {
        console.log(raw);
    }

**Comment by MrSwitch** [comment]
Hi @jonathanazulay. 

The response handler tweaks the response, which as you say is overriding the existing raw response when `picture` is returned as an object.

FYI: you can write it like this...
```javascript
hello('facebook').api('me', {fields: 'picture,name,email,gender'}).then(console.log.bind(console))
```

# Comments
> I would like to use redirect=false 
So your suggestion sounds reasonable. The flag name `redirect` is a bit misleading. Perhaps 'response=raw' might be better.

> add raw response to the callback
So the function `.then` can only ever yield a single response as per the Promise A+ spec (citation needed).

# Alternative solution
The method has got a rather obsolete completeEvent handler which doesn't have the same limitations as the success and error handlers which handle the Promise response. It might be good to apply the unformatted results there. i.e. `hello('facebook').api('me', completeEvent).then(successHandler, errorHandler)`

However the caveats to returning both raw and tweaked resultsets might be one of poor performance with having to clone large resultsets. And having to hold effectively twice as much in memory.

**Comment by MrSwitch** [comment]
To use the new flag, you'll need to pass the options in as a key=>value hash, i.e...

```
hello('facebook').api({
    path: 'me',
    query: {fields: 'picture,name,email,gender'},
    formatResponse: false
}).then(console.log.bind(console), console.error.bind(console));
```

Please checkout v1.8.2

**Comment by jonathanazulay** [comment]
@MrSwitch Cool! That should do it.
