### ISSUE TITLE
RequireJS/AMD loader compat.

### ISSUE THREAD

**Issue by hagen** [MrSwitch/hello.js#310]
Cool lib. I'm enjoying using it. Getting hung up on it's usage in AMD, single page application application. Typically, I don't have any script tags throughout the application code base; module declarations like this:
```javascript
define(['jquery', 'hello'] , function ($, hello-auth) {

    return function () {};
});
```

take care of that, in this architecture. Any plans to build compat. for this?

**Comment by MrSwitch** [comment]
The amd loader is included in the bundled files in the `dist/` directory. E.g. http://adodson.com/hello.js/demos/amd.html
