### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'pagination' in Oops, an error occurred.

### ISSUE THREAD

**Issue by cheemengs** [MrSwitch/hello.js#312]
This occured when i'm trying to login to instagram to a clientid and then liking a post.

    hello.init({
            instagram: '88cb91ab722f4f9588fd2d01652162a7'
        },{
            scope : 'comments+likes'
        });
            var ig = hello('instagram');

            ig.login({scope:'comments likes'}).then(function() {
                likeIgPost(ig, postId);

            }, function(e) {
                alert('Instagram Signin error: ' + e.error.message);
            });

After clicking on a button, 

     ig.api( 'me/like', 'post', { id : postId } ).then(function( r ){
                if(r.meta.code === 200){
                    pic.user_has_liked = method === 'post';
                    img.className = ( pic.user_has_liked ? 'liked' : '' );
                }
            });

It occurs in hello.all:4619

    function paging(res) {
        if ('pagination' in res) {
            res.paging = {
                next: res.pagination.next_url
            };
            delete res.pagination;
        }
    }

**Comment by MrSwitch** [comment]
Thanks, whilst investigating this is looks like this endpoint and any POST/DELETE operation has been closed down for consumer facing API's and a granted access to enable the demos is pending.

See https://help.instagram.com/contact/185819881608116 if you to need to request access to this endpoint.

In the interim I can put a catch to format these errors.
