### ISSUE TITLE
Create Google/Microsoft, Docs/Sheets/Slides

### ISSUE THREAD

**Issue by PsyGik** [MrSwitch/hello.js#313]
How do I create a new Google/Microsoft Doc/Sheet/Slide? Is it supported in your API? I know that we can upload files using "me/files" (POST). However, I'm not able to find any method to create new Google/Microsoft Docs/Sheets/Slides.

**Comment by MrSwitch** [comment]
HelloJS is a thirdparty library with many endpoints standardized and many more omissions. If you find features on a providers RESTful endpoint which you would like to use in HelloJS then please try forking the project and make the necessary changes, remember to create a PR back so everyone can see. Alternatively open a ticket and cite the documentation for the endpoints your trying to resolve and perhaps someone can help.

**Comment by PsyGik** [comment]
I did write a simple (very ugly) snippet to create new file in Google Drive. I'll do a PR if I can write one for MS also.


```javascript
if (p.method === 'post') {
            if (p.data.type) { //if there is a mimetype included, create a new file
                p.data = {
                    title: p.data.name,
                    parents: [{
                        id: p.data.parent || 'root'
                    }],
                    mimeType: type
                };
            } else { //no mimetype, continue with the regular stuff
                p.data = {
                    title: p.data.name,
                    parents: [{
                        id: p.data.parent || 'root'
                    }],
                    file: p.data.file
                };
            }
        } 
```

The Mimetypes for Google are:

Google Docs:
```
application/vnd.google-apps.document
application/vnd.google-apps.kix
```
Google Presentations:
```
application/vnd.google-apps.presentation
```
Google Spreadsheets:
```
application/vnd.google-apps.spreadsheet
```
Google Drawing:
```
application/vnd.google-apps.drawing
```
