### ISSUE TITLE
Support login_hint for refreshes with multiple Google accounts

### ISSUE THREAD

**Issue by josschne** [MrSwitch/hello.js#314]
When logged in with multiple Google accounts, refreshing a token displays an account chooser that the user must interact with. 

Google supports a "login_hint" query string param that takes the email address of the account you'd like Google to auto-select. In practice, you can set this to the most-recently-used account to avoid the popup.

Currently hello.js does not support login_hint. I'd like to see support added. Thanks!

**Comment by MrSwitch** [comment]
I have been thinking about this. I'm considering allowing custom arguments, passing through automatically properties which are unknown. So this would then work... `hello(google).login({login_hint:'hello@gmail.com'})`. However if you called another service with this it could break the login. Currently `hello.login` is very strict on what it actually passes through, however that as you have realized becomes quite inflexible, when services have special features like this login_hint.

The alternatives are too bake this this into the google module so it applies it by default and users use the "force" property of `hello.login`.

I dunno how familiar with this you are or if you have a your own preference. Either way i'd like to hear your ideas. Thanks

**Comment by josschne** [comment]
Hey, sorry I've been silent on this. I see you've got an implementation already, which is great!  I can't speak to the implementation at all, but the interface in the test looks reasonable. I think this would solve it - and it appears to clean up a special case already included in the Facebook portion of the code.

**Comment by MrSwitch** [comment]
[Released v1.9.0](https://github.com/MrSwitch/hello.js/releases/tag/v1.9.0)
