### ISSUE TITLE
Unable to upload files to OneDrive in Demo page.

### ISSUE THREAD

**Issue by PsyGik** [MrSwitch/hello.js#315]
I tried the me/files POST in demo page. It is not working. I get the following error.

    {
    "error": {
    "code": "request_body_invalid", 
    "message": "The request entity body has an incorrect value in the 'Content-Disposition' header. The expected format for this value is 'Content-Disposition: form-data; name=\"file\"; filename=\"[FileName]\"'."
    }
    }
![screen shot 2015-09-02 at 12 46 45 pm](https://cloud.githubusercontent.com/assets/5432911/9625098/bdf5865e-5170-11e5-96aa-b5aafec71f19.png)

It works for other providers. Only 'windows' is throwing this error. Can you verify the same?

**Comment by MrSwitch** [comment]
Works for me. Which browser are you working with?

**Comment by PsyGik** [comment]
I'm using Google Chrome Version 45.0.2454.99 (64-bit) on a Mac.
