### ISSUE TITLE
Modules xhr is by default off

### ISSUE THREAD

**Issue by gjdev** [MrSwitch/hello.js#320]
When defining a module, and not setting the xhr property during it's initialization, xhr will not be used for that module. The documentation suggests that in such case xhr should be used, as the xhr property is documented as defaulting to true.

The reason hello.js is effectively defaulting to disabling xhr is that on hello.js:1807: https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L1807 xhr is always made a property of variable p. The check on hello.js:1947 therefore finds a p.xhr property (although initialized to undefined), which results in variable cors being undefined.

**Comment by MrSwitch** [comment]
Good catch, thanks
