### ISSUE TITLE
Hello.js on Chrome + iOS9

### ISSUE THREAD

**Issue by mrjohnjin** [MrSwitch/hello.js#321]
In iOS9 and Chrome, the popup doesn't get any event listeners bound to it because `addEventListener` is `undefined`.

Around line 1400...

    var popup = window.open( ... );
    if (popup && popup.addEventListener) {
        // bind all events, but never runs in iOS9/Chrome
    }

The demo http://adodson.com/hello.js/demos/profile.html doesn't work on an iPhone6 with iOS9 and Chrome but works fine on other browsers I've tested.

Has anyone else run into this issue?

**Comment by MrSwitch** [comment]
The popup.addEventListener is used on phonegap/cordova. So it's expected not to be triggered in normal browser scenario. Which begets the question what the problem is. Is Safari on iOS9 affected?

**Comment by mrjohnjin** [comment]
Ah, I did not know that. Safari on iOS9 works fine on my device.

**Comment by mrjohnjin** [comment]
I think I might have found something.

The issue is in the way `hello.utils.responseHandler()` called.

When this is called:

    hello.utils.responseHandler(window, window.opener || window.parent);

In Chrome, `window.parent` actually refers to itself instead of the parent. So when we try to call the callback, it doesn't exist.

**Comment by MrSwitch** [comment]
I've not heard of that. And can't see it mentioned anywhere. You?

**Comment by mrjohnjin** [comment]
I don't see it documented anywhere, but window.parent.location is the same as window.location (from the popup).

**Comment by mrjohnjin** [comment]
I ended up using local storage to get around it and so far it works for Facebook and Twitter.

We're using an older version of hello.js, so the line numbers might not match up exactly...

Looks for authResponse in local storage set in the popup.

    // ~line 550
    var timer = setInterval(function() {
        if (!popup || popup.closed) {
            clearInterval(timer);

            var authResponse = utils.store('authResponse');
            if (authResponse && authResponse.length && callbackId in window) {
                utils.store('authResponse', '');

                window[callbackId](authResponse);
                return true;
            }

            if (!promise.state) {

                var response = error('cancelled', 'Login has been cancelled');

                if (!popup) {
                    response = error('blocked', 'Popup was blocked');
                }

                response.network = p.network;

                promise.reject(response);
            }
        }
    }, 100);

Sets local storage for case 1. I haven't hit this piece of code, so not 100% sure it works, but is similar to the next bit...

    // ~line 1570
    // API call, or a cancelled login
    // Result is serialized JSON string
    else if (p.callback) {

        // Trigger a function in the parent
        var res = 'result' in p && p.result ? JSON.parse(p.result) : false;

        // Trigger the callback on the parent
        if (p.callback in parent) {
            parent[p.callback](res);
        } else {
            // possible chrome error!
            hello.utils.store('authResponse', JSON.stringify(res));
        }

        closeWindow();
    }

This is the bit of code that FB seems to hit.

    // ~ line 1620
    // Call the globalEvent function on the parent
    if (cb in parent) {

        // It's safer to pass back a string to the parent,
        // Rather than an object/array (better for IE8)

        try {
            parent[cb](str);
        }
        catch (e) {
            // Error thrown whilst executing parent callback
        }
    } else {
        hello.utils.store('authResponse', str);
    }

Not sure if this will work in all cases and we haven't tested it thoroughly, but so far, it looks pretty good.

Let me know what you think or if you think there is a better workaround.

**Comment by MrSwitch** [comment]
So not sure what version you are on, but the code has been refactored since... 

But your right, rather than deleting the callback from the session response https://github.com/MrSwitch/hello.js/blob/v1.8.4/src/hello.js#L1462, first detect it exists and if not just store in the popup and close. The localstorage is monitored on all instances of hellojs and can trigger the callback from there instead see https://github.com/MrSwitch/hello.js/blob/v1.8.4/src/hello.js#L1564

**Comment by mrjohnjin** [comment]
Oh, good to know!

In case anyone else needs it, this change worked just fine for iOS9 + Chrome (starting https://github.com/MrSwitch/hello.js/blob/v1.8.4/src/hello.js#L399)

    var timer = setInterval(function() {
        if (!popup || popup.closed) {
            clearInterval(timer);

            if (!promise.state) {
                // START CHANGE
                var authResponse = hello.utils.store(p.network);

                if (authResponse && !authResponse.error && callbackId in window) {
                    window[callbackId](JSON.stringify(authResponse));
                    return true;
                }
                // END CHANGE

                var response = error('cancelled', 'Login has been cancelled');

                if (!popup) {
                    response = error('blocked', 'Popup was blocked');
                }

                response.network = p.network;

                promise.reject(response);
            }
        }
    }, 100);
