### ISSUE TITLE
Rebooted: Facebook app defaulting to 2.4 + missing email

### ISSUE THREAD

**Issue by rajkotecha** [MrSwitch/hello.js#322]
Despite the recent fix to force FB to use v2.3 API (which returns email as part of a default set of profile fields), the fix no longer helps people creating new facebook apps, because there doesn't seem to be a way to force 2.3 from the UI **and Facebook is sunsetting 2.3 in 24d (Oct 15, 2015)**

>![image](https://cloud.githubusercontent.com/assets/839040/10037008/cfdf5864-617d-11e5-8e09-cfa0603cebd8.png)

**FIX from 1.8.2:**
```
// API Base URL
base: 'https://graph.facebook.com/v2.3/',
```
**Would a change along the lines of the following be appropriate:** (worked for my needs)
```
.
.
.
// Map GET requests
get: {
	   	me: 'me?fields=email,name,first_name,last_name,id',
		'me/friends': 'me/friends',
		'me/following': 'me/friends',
		'me/followers': 'me/friends',
.
.
```

**Comment by optikalefx** [comment]
+1 here. Is there anything in Hello.js that allows us to specify these fields?
