### ISSUE TITLE
Denied responses are not handled if state param is missing

### ISSUE THREAD

**Issue by ioanlucut** [MrSwitch/hello.js#323]
As an example, Slack, does return only _error_ parameter. See below:

> Slack: denied Requests
> If the user denies your request, Slack redirects back to your site with an error parameter.
_http://yourapp.com/oauth?error=access_denied_

So the following code does not apply:
```
	             // Error=?
			// &error_description=?
			// &state=?
			else if (('error' in p && p.error) && p.network) {

				p.error = {
					code: p.error,
					message: p.error_message || p.error_description
				};

				// Let the state handler handle it
				authCallback(p, window, parent);
			}
```

**Comment by MrSwitch** [comment]
Can you post your slack module here and i'll have a play around? Alternatively a PR would be good too.

**Comment by ioanlucut** [comment]
```(function (hello) {
    'use strict';

    hello.init({

        slack: {
            name: 'Slack',
            oauth: {
                version: 2,
                auth: 'https://slack.com/oauth/authorize',
                grant: 'https://slack.com/api/oauth.access'
            },
            refresh: false,
            scope: {
                identify: 'identify'
            },
            scope_delim: ' ',
            base: 'https://slack.com/api/',
            get: {
                me: 'auth.test'
            },
            xhr: function (p, qs) {
                qs.token = p.query.access_token;
                return true;
            },
            form: false,
            jsonp: false
        }
    });

})(hello);```

and 

```       // ---
            // Initialize HELLO.
            // ---
            hello
                .init({
                  slack: ENV.OAUTH2_CLIENT_IDS.SLACK
                }, {
                    redirect_uri: ENV.redirectUri,
                    oauth_proxy: myCustomGrantUrl
                });```

I will submit a PR soon. Thanks Andrew.

**Comment by MrSwitch** [comment]
See demo https://adodson.com/hello.js/demos/slack.html

Andrew Dodson | Freelance Web Developer | +61 (0) 452 411 861 |
https://adodson.com

**Comment by ioanlucut** [comment]
Demo looks indeed really good. Thank you for it!

Just one question.. The handling of the denied answer you've done at https://adodson.com/hello.js/redirect.html?error=access_denied is not from hello.js, right ?

**Comment by MrSwitch** [comment]
That's the response from Slack, and it should contain `state` too. Their implementation of OAuth2 is, for want of a better word, rather slack!

There is a workaround. On your redirect_uri page. After embedding HelloJS do something like...

```html
<script>
if(window.location.search,match('error')) window.onload = function(){window.close();}
</script> 
```

However, do you want to reach out to their dev ops team to fix this? The state parameter is pretty important, its a reliable way to identify what sessions/errors to trigger from a particular event. And Its unreliable to use the parent/opener window and any child popup window relationship in some devices (Chromeapps/Old Windows Phone/Old Androids). Anyway state parameter is pretty important.

If you have any reference number to their issue tracking please post it here. Also share this bug with them too. Thanks.

**Comment by ioanlucut** [comment]
I've already raised an issue with Slack. So far, the support team told me they'll check with the dev team. No answer since then.

But, actually, having this workaround which fixes denied flow works for me too. 

Thanks a lot for explanations & workaround.
