### ISSUE TITLE
How to ensure a particular user is logged in?

### ISSUE THREAD

**Issue by xlc** [MrSwitch/hello.js#331]
I am using Google's API Client Library for JavaScript (gapi) and want to migrate to hello.js but I feel it may not be flexible enough to fit my needs.
In particular, I need to allow user to open their file in Google Drive. I have their Google User Id and Google Drive file id, so I need a method like `hello('google').login({user_id: google_user_id})` which will ensure the user authorised the correct account. If the user were autologin with a different account, a popup should be shown to ask user to authorise.

With gapi, I can just add extra parameter `user_id` to `gapi.auth.authorize` method call. How can I add this parameter with hello.js?

**Comment by MrSwitch** [comment]
Have you tried what you have suggested? It should work.

**Comment by xlc** [comment]
Ah... I never know that extra parameters are passed to the query string directly. Thanks.
