### ISSUE TITLE
iOS doesn't detect aborted login

### ISSUE THREAD

**Issue by rajkotecha** [MrSwitch/hello.js#338]
The following code works fine in Chrome but not iOS (haven't tested in Android)

Running on iOS 9.1, iPhone 5s

Problem: I'm currently running a progress spinner during login. If the user aborts, the spinner stays active and the app is effectively non-responsive.

Workaround: I'll have to remove the spinner ...

```
login: function (options, callback) {
      var self = this;
      var authority = options.authority;
      hello(authority).login({scope: 'email'}, function(r){
        if(!r || r.error) {
          console.log("aborted!");
          callback("aborted");
          return;
        }
```

**Comment by MrSwitch** [comment]
Inactive

@rajkotecha sorry you didn't get an answer. I'll reopen this if this is still an issue. fyi: try using Promises.
