### ISSUE TITLE
hello.api not works on android

### ISSUE THREAD

**Issue by immigrationanytime** [MrSwitch/hello.js#341]
Hello MrSwitch,

I use **hello.all.min.js** in PhoneGap App.
On my Android, **hello.api** open and fast close login screen.  Error says: **could not get resource**
On my iOS, all is fine.  This my code is:

                hello('facebook').login({ display: 'popup', scope: 'email,basic' }).then(function (auth) {
                    hello(auth.network).api('/me', { display: 'popup', scope: 'email,basic' }).then(function (json) {
                        alert(json.first_name);
                    }, function (e) {
                            alert("hello.api:" + e.error.message);
                    });
                }, function (e) {
                    alert("hello.login:" + e.error.message);
                });

Could you please help?
Thank you very much for your help.

Hossein

**Comment by MrSwitch** [comment]
Hmm, i wonder if its a setting like InAppBrowser

**Comment by albertonaperijr** [comment]
+1

**Comment by MrSwitch** [comment]
Changes have been made to improve the Phonegap experience. Closing this as fixed.
