### ISSUE TITLE
Login problem ionic app with hello.js

### ISSUE THREAD

**Issue by iiitmahesh** [MrSwitch/hello.js#343]
How slove this problem

login with google: in my hybrid app 

Error : Invalid Request

Invalid parameter value for redirect_uri : Missing authorotiy: file:///android-asset/www/index.html

**Comment by albertonaperijr** [comment]
+1

**Comment by MrSwitch** [comment]
The example https://github.com/MrSwitch/hellojs-phonegap-demo/blob/master/index.html#L56 is set to the callback url I gave when registering the app with the thirdparties.

**Comment by elhamsarikhani** [comment]
I tried to use
          `redirect_uri : 'http://adodson.com/hello.js/redirect.html'`
but after login it gave me the message: " please close this window to continue"

**Comment by iiitmahesh** [comment]
@elhamsarikhani  yeah taht was right. I correcteed it. anyways thank you

**Comment by elhamsarikhani** [comment]
Could you tell us what was the issue and how you solved it? :)

**Comment by iiitmahesh** [comment]
@elhamsarikhani  Problem was : I have not included redirect_uri : 'http://adodson.com/hello.js/redirect.html' instead of  I have used redirect url : localhost:8100/siginsuccuess.html in both source code and  redirected url of settings of social login developer webApp (Currently I am using Facebook and google).

After changing urls in both places {redirect_uri : 'http://adodson.com/hello.js/redirect.html' } then it is working. But there was issue it won''t work in browser in developer mode(in ionic serve), it will work in output mobile app ( android apk file). If wann use broswer then we have to use use redirect url is localhost"8100/signin in both places 

(Both places : 1 @source code and 2@ develoepr app account settings )  

My explanation skills not good. Hopefully you might understand my problem and solution #157

**Comment by elhamsarikhani** [comment]
Thanks so mine was different I set the redirect url in both places, in app as well as in app manager of provider, but still, when I was using
redirect_uri : 'http://adodson.com/hello.js/redirect.html'
after login it gave me the message: " please close this window to continue".
I tried http://localhost/   instead

**Comment by iiitmahesh** [comment]
Previously I've got same kind problem  


// app.js config
.config(function($stateProvider, $urlRouterProvider, $httpProvider, helloProvider) {
	helloProvider.init({
	google : '.............',
	facebook : '.......'
	},{ redirect_uri : 'http://adodson.com/hello.js/redirect.html'});  
   redirect_uri : 'http://adodson.com/hello.js/redirect.html'});}


// LoginCtrl
$scope.fbLogin = function () {
           hello( 'facebook' ).login( function() {
  	token = hello(  'facebook' ).getAuthResponse().access_token;
	console.log('facebook Auth Token : '+token);}


//add ngHello .js  to index.html or add this directive to your app
(function (hello) {
    angular.module('ngHello', [])
        .provider('hello', function () {
            this.$get = function () {
                return hello; };
            this.init = function (services, options) {
                hello.init(services, options);
            }; }); })(hello);


//  Then add this app module 
angular.module('wmApp', ['ionic','ngMockE2E','LocalStorageModule', 'ngHello', 'ionic-http-auth.controllers'])
}

(contact me@https://twitter.com/iiitmahesh)

**Comment by elhamsarikhani** [comment]
Thanks Mahesh,
I've got a question regarding your code snippet . I followed the steps but I assume that in the line 

         angular.module('wmApp', ['ionic','ngMockE2E','LocalStorageModule', 'ngHello', 'ionic-http-auth.controllers'])

you meant to inject 'ngHello' right? I don't have the rest of these dependencies. but result is the same.
