### ISSUE TITLE
Staying online after authentication

### ISSUE THREAD

**Issue by elhamsarikhani** [MrSwitch/hello.js#344]
Hi,
I want to implement some sort of notification with the app and I was wondering if it's possible to use hello JS for authentication part. I would like to stay online after authentication.  while the app is running in the background. is that possible?
I have already set the token refresh to true but that still lead to token expiration as the app is closed.

**Comment by MrSwitch** [comment]
What version of HelloJS are you on?

**Comment by elhamsarikhani** [comment]
This is the line at the top of the library:
hellojs v1.9.6 | (c) 2012-2015 Andrew Dodson |

**Comment by MrSwitch** [comment]
Good, just checking. How have you set token refresh to true?


HelloJS monitors for expired tokens and refreshes the token in the background when it can. However providers typically fall into two camps in regard to how this is achieved.

# Official refresh_token
OAuth2 has the notion of a `refresh_token` which when used in conjunction with the 'client_secret' can be used to request a new `access_token` without a browser session being required. The refresh_token is typically only returned when the OAuth2 Authorization Code flow is adopted i.e. `hello(x).login({response_type: 'code')` this is true with Google for example.

In this situation hellojs will make a login request via the `oauth-proxy` service with the refresh_token. And shall return a new auth response containing an access_token.

# Unofficial Implied
There is another approach which is where some modules have `refresh: true` in their module definition - e.g. https://github.com/MrSwitch/hello.js/blob/v1.9.6/src/modules/facebook.js#L37 . This flag tells HelloJS that the provider allows the login flow to be initiated in an iframe (i.e. does not block via a [X-FRAME-OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options)) and will continue without asking the user to re-authorize the application.

There is more information on this http://adodson.com/hello.js/#refresh-access-token

I should probably update the docs as this is quite a common requirement.

**Comment by elhamsarikhani** [comment]
Thank you!  I have added this provider:
         (function(hello) {

    hello.init({
        Foo: {
            name: 'foo',
            oauth: {
                version: 2,
                auth: 'https://start.foo.com/api/oauth2/auth',
                grant: 'https://start.foo.com/api/oauth2/token'
            },		
	    refresh: true,
            base: 'https://start.exactonline.com/api/'
        }
    });
    })(hello);

I guess I have to change this to use the official refresh token but don't know what should I do. just set the response_type: to 'code' when I call the login function?

**Comment by MrSwitch** [comment]
FYI: This is generic OAuth2 language `code` is shorthand for Authorization Code and triggers the Explicit Grant flow.

`client_secret` is stored in a service - not in your clientside code - please see https://github.com/MrSwitch/hello.js/#oauth-proxy

**Comment by elhamsarikhani** [comment]
I want to register my app using  https://auth-server.herokuapp.com/ but there is no documentation how to fill the fields on registration part and how to fill it. What is domain? is it the sample that had in my previous code for example.
