### ISSUE TITLE
Strange behaviour of auth.login

### ISSUE THREAD

**Issue by elhamsarikhani** [MrSwitch/hello.js#345]
I have the following lines to handle the page to load whether the user is logged in or not

    `.run(function($ionicPlatform, $state, hello) {
      $ionicPlatform.ready(function() {

      hello.on('auth.login', function () {
        $state.go('bella.dashboard');
        
      }).on('auth.logout', function () {
          $state.go('login');
      });

      if(hello.getAuthResponse('exactonline')) {
          $state.go('bella.dashboard');
      }
     
      })
    })`

as I login to provider, I get redirected to my login page but `state.go('bella.dashboard');` won't fire. but as I close the app and open it again, since the session is still valid, 
      `if(hello.getAuthResponse('exactonline')) {
          $state.go('bella.dashboard');
      }`
will cause the state to be shifted to dashboard correctly. 
I'm running the app on an android device.

**Comment by MrSwitch** [comment]
That should work, any luck since?

**Comment by elhamsarikhani** [comment]
no I couldn't solve this one so I shifted the logic of login to a modal in my app so I wouldn't need to use $state.go .... this was a wierd one.
