### ISSUE TITLE
google redirect_uri_mismatch from localhost?

### ISSUE THREAD

**Issue by tony-kerz** [MrSwitch/hello.js#347]
trying to auth against google on localhost

following the quick start guide steps (with code in react/es-next style):

1. registered an app at `console.developers.google.com` like so:
<img width="615" alt="screen shot 2015-11-02 at 10 38 32 pm" src="https://cloud.githubusercontent.com/assets/1223231/10900816/94b5c6f6-81b2-11e5-9117-f0e337cd6b70.png">
  (wasn't sure about javascript-origins vs redirect-uris, so i specified both)

1. included `hello` script(s) where referenced like so:

  ```
  import Hello from 'hellojs/dist/hello'
  import 'hellojs/src/modules/google'
  ```
1. created an 'on-click' handler like so:

  ```
  handleClick = (e) => {
    let provider = Hello('google')
    provider.login({force: false})
    .then((x) => {
      provider.api('me')
      .then((y) => {
        //...
      })
    })
  }
  ```
1. called `init` like so:
  ```
  Hello.init(
    {
      google: '<my-client-id-here>'
    }
  )
  ```
but when i run, i get:

  ```
The redirect URI in the request: http://localhost:8080/ did not match a registered redirect URI.
  ```
  even tho, i did setup that URI (at least without the trailing `/`).

all the setup is in [this file on github](https://github.com/tony-kerz/hello-scratch/blob/tk/hello/app/home.jsx) if it is relevant.

appreciate any guidance!

regards,
tony.

**Comment by MrSwitch** [comment]
The link to your github is broken. I can't see why this wouldn't work.

**Comment by tony-kerz** [comment]
thanks @MrSwitch,

a cautionary tale of leaving links to a branch v a commit, here is [a link with staying power](https://github.com/tony-kerz/hello-scratch/blob/c35e4f03e72ec8033f6ae71c681119dec8ed4ab8/app/session.jsx)

best,
tony.

**Comment by leecrossley** [comment]
I'm having this same issue, did you manage to resolve it?

**Comment by leecrossley** [comment]
**Authorized redirect URIs** needs to have the slash, i.e. `http://localhost:8080/` this fixes the issue.

**Comment by tony-kerz** [comment]
thanks @leecrossley, that worked for me as well. 

i did have to:

1. add the trailing slash
1. update to `1.9.9`
1. logout and login to google

to get it to take tho, so if anyone else is having trouble with just the first step, try the additional steps

**Comment by davidxia** [comment]
There's also a mention of `OAUTHLIB_INSECURE_TRANSPORT` env var [tucked away in these docs](https://developers.google.com/identity/protocols/oauth2/web-server#example).

```
  # When running locally, disable OAuthlib's HTTPs verification.
  # ACTION ITEM for developers:
  #     When running in production *do not* leave this option enabled.
  os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```
