### ISSUE TITLE
/adorn/adorn.js 404 (File not found)

### ISSUE THREAD

**Issue by tawanda** [MrSwitch/hello.js#351]
the folder /adorn is missing from this project

**Comment by MrSwitch** [comment]
Adorn is separate project of mine - see https://adodson.com/adorn/ for its principles.

From your document root directory "git clone git@github.com:MrSwitch/adorn.git adorn" and your away.

Reason: To work offline on my projects like hello.js i needed to point to local assets to add some style. So i assume that the root directory has a folder called /adorn - conveniently this is the same structure as gh-pages.

//localhost/
 - adorn/
 - hello.js/

**Comment by tawanda** [comment]
awesome thanks
