### ISSUE TITLE
How to get a Hi-res profile picture from Facebook?

### ISSUE THREAD

**Issue by flogo1982** [MrSwitch/hello.js#353]
I am trying to get the high-resolution profile picture from Facebook.

The picture returned by the end point 'me' has a very low resolution. Actually I can see the same low res picture on hello.js website as well.

How can I achieve that? 
Thanks!

**Comment by MrSwitch** [comment]
I googled this in a minute https://developers.facebook.com/docs/graph-api/reference/user/picture

**Comment by flogo1982** [comment]
oh! so I can use any Facebook end point directly?

**Comment by MrSwitch** [comment]
You can use any any path, or even full url's. HelloJS will sign the request and apply the default formatting if there is any for a module.

e.g.

```javascript
var fb = hello('facebook);
fb.login().then(function (){
   return fb.api("me/picture", {width:100, height:100});
}, errorHandler)
.then(handleDataResponse, handleAPIError)
```

**Comment by flogo1982** [comment]
First of all thanks a lot for your responsiveness and the example provided.

I tried this:
          ```hello('facebook').api('me/picture', {width:100, height:100}).then(
                function(response) {
                  console.log(response);
                },
                function(error) {
                  console.error(error);
                }
              );```

I got this error:
![image](https://cloud.githubusercontent.com/assets/4402620/11099127/c7bebc28-8866-11e5-94ed-aadc17618580.png)

**Comment by flogo1982** [comment]
I have just tried 'me/picture?redirect=false' instead of 'me/picture' and I got the right data printed in the format function of hello.all.js. And I checked the url and saw the right picture.

However there is still an error:
![image](https://cloud.githubusercontent.com/assets/4402620/11099709/26d569fc-886a-11e5-8c95-1abc1b226839.png)

I will see what I can do to fix it.

**Comment by MrSwitch** [comment]
The facebook module does expects the data property to be an array. I'll patch that shortly. In the meantime please construct your own URL.

**Comment by flogo1982** [comment]
This works:
```javascript
if (o && 'data' in o) {
    var token = req.query.access_token;

    if (typeof o.data !== 'array') {
        var data = o.data;
        delete o.data;
	o.data = [data];
    }
```

Do you want I pull request?

**Comment by MrSwitch** [comment]
... although there docs say data should be an array. I've reported this to facebook https://developers.facebook.com/bugs/1715115008719989/

**Comment by flogo1982** [comment]
Yep I read that too. Weird. 

Thanks a lot for this tremendous work you do on this library. it is huge!

**Comment by MrSwitch** [comment]
No that condition would not work `typeof([]) === 'object'` ... one of the quirks of javascript.

try `o.data instanceof Array`

**Comment by HermesDev** [comment]
This works for me:
```javascript
if (!(o.data instanceof Array)) {
	var data = o.data;
	delete o.data;
	o.data = [data];
}
```

**Comment by imroca** [comment]
```
hello.on('auth.login', function(auth) {
    var url = "/me";
    if (auth.network === "facebook") {
      url = "/me?fields=id,name,email,first_name,last_name,link,bio,birthday,picture,gender,verified,location";
    }

    hello(auth.network).api(url).then(function(r) {
      var profile = parseProfile(auth.network, r);
      window.location.assign("#{basepath}/user?engine=" + auth.network + "&user=" + window.btoa(encodeURIComponent(JSON.stringify(profile))));
    }, function(e) {
      console.log(e);
    });
  });
```
After getting profile picture just concat heigth to provided link:
```
profile.picture + "?height=200"
```
