### ISSUE TITLE
Redirect with code only

### ISSUE THREAD

**Issue by imroca** [MrSwitch/hello.js#355]
I'm struggling with something, so i hope you guys can give me a hand, i'm attempting to implement explicit grant, but on the redirect uri hello.js forces you to exchange the code though the oauth_proxy, 

Popup close giving this error:
"Signin error: The client_id "XXXXXXX" is unknown. Register your app credentials by visiting https//auth-server.herokuapp.com"

I don't want to register my app on heroku, nor install the node shim

I would like to exchange the code for the access token on the server side... how can i achieve this?

**Comment by MrSwitch** [comment]
... re-engineer the functionality of the oauth-shim

**Comment by imroca** [comment]
could you elaborate a little more? maybe with returning code and closing the popup would be enough...

**Comment by MrSwitch** [comment]
Checkout the [OAuth2 spec's](https://tools.ietf.org/html/rfc6749#section-4.1.3) for handling an Authoriztion Code response on your server.

**Comment by imroca** [comment]
handling the code is not the problem, i'm just looking for a way of deal with the popup that doesn't close with the code, looks for the token instead... How could i add an event for code only?

**Comment by MrSwitch** [comment]
```javascript
if (location.search.match("code=")) {
   window.close();
}
```

**Comment by blackotruck** [comment]
Hello, first of all Great library, now, i'm currently on this situation and got a few questions, first of all
```
if (location.search.match("code=")) {
   window.close();
}
```
works for closing the window, but i can get the code param to de father window, it just exists with 
```
error('cancelled', 'Login has been cancelled');
```
On the other hand, using windows.close i'm modifiying the library, so i wont be able to update it via bower, and although i dont really see this as a problem, i know that's not the best way to do things. So the question is, how can i close the window when i get the code, and pass the code to the father, and how could i configure this behavior as an option (this las part i guess should be added later to the library), maybe using an attribute option like 

```
if (opts.response_type === 'code' && !opts.use_oauth_proxy){
    if (location.search.match("code=")) {
      //fulfill promise with authResponse:{code:'le_code'}
      window.close();
   }
}
```

this way people could use the code or the proxy
