### ISSUE TITLE
LinkedIn Friends

### ISSUE THREAD

**Issue by Fintasys** [MrSwitch/hello.js#360]
Hey ho!

I'm struggling with LinkedIn and getting my friends (connections). 
The Demo on you site also not working (Error 403) .

I'm wondering if I have to apply for LinkedIn Partner Program to get access of this API Call or something else is wrong? 

Thank you!

**Comment by MrSwitch** [comment]
They drastically dropped support for their public endpoints. These are the only ones left https://apigee.com/console/linkedin

I've removed the paths as its impossible to support these endpoints.

**Comment by MrSwitch** [comment]
@Fintasys if you are granted access to their partner program please let us know. My request was declined.
