### ISSUE TITLE
assumption that field value is always an array when querying friends with yahoo api

### ISSUE THREAD

**Issue by gbozee** [MrSwitch/hello.js#362]
I ran into this error when running hello('yahoo').api('me/friends').

Uncaught TypeError: (contact.fields || []).forEach is not a function
After digging through the api response, I observed that some one of my contacts field property was an object instead of an array. Debugging through chrome drove me to this section in hello.all.js

    function formatFriend(contact) {
        contact.id = null;
        (contact.fields || []).forEach(function(field) 
            if (field.type === 'email') {
            contact.email = field.value;
        }

**Comment by MrSwitch** [comment]
Hmm weird. What does the object look like? I don't suppose you have seen this in the yahoos developer docs?

Would you like to suggest a fix?

**Comment by gbozee** [comment]
A fix would be to check if `contact.fields` is an object or an array. if it is an object, it should be wrapped inside an array

**Comment by MrSwitch** [comment]
I meant for you to create a Pull Request.
