### ISSUE TITLE
Explicit flow uses 'GET' only?

### ISSUE THREAD

**Issue by curiosity101** [MrSwitch/hello.js#363]
This is more of a question than an issue. But is there any way to configure how you send the data to the oauth_proxy. I had been expecting to POST a JSON to my authentication API (the oauth_proxy). 

We're building the authentication API ourselves so it's not a show stopper but I was also curious why it is a GET rather than a POST?

**Comment by MrSwitch** [comment]
Assuming you are talking about exchanging an Authorization Code for an Access Token. Yes it could very well be a POST.

Can you elaborate as to why POST is preferred?

Thanks

**Comment by curiosity101** [comment]
I am referring to exchanging the Auth Code for an Access token yes. 

To me it would feel more 'correct' as we are effectively submitting the access_code for further processing (ie. into an access token), via additional calls. As opposed to a 'GET' which is what I would expect to use if I were requesting a subset of a resource / specific representation.

**Comment by MrSwitch** [comment]
Well, the Authorisation Code is typically sent via GET to the `redirect_uri`. HelloJS is merely passing this on to a service which can handle it. What i would suggest is you bypass HelloJS with a dynamic `redirect_uri` endpoint. 

If the HTTP request from the provider contains an Authorization Code. Your service should exchange this for an Access Token and redirect the page to a page which contains HelloJS with the new token and any other parameter which was included.

I've got an example. I'll clean it up and post it shortly.

**Comment by MrSwitch** [comment]
Here's an example https://github.com/MrSwitch/hellojs-signin-demo/blob/ad597a80361ef8bc13cf3dc79a4f7ecfa383dfbd/index.js#L75 i hope that helps
