### ISSUE TITLE
Yahoo OAuth1 Authentication has a blank screen.

### ISSUE THREAD

**Issue by ratheeshkannan** [MrSwitch/hello.js#364]
I'm getting empty screens from yahoo server. The user need to close the dialog box and try again. The success rate of getting the authentication dialog is very minimal.

I'm using the main module which is in turn using the current oauth 1.0 setup i assume. The url said v2 but yahoo.js saying v1.0a. I'm not sure which one is going. All I'm doing is specifying my yahoo app id in config file and calling

While inspection I'm getting 401 Unauthorized for the main call.

![yahoo](https://cloud.githubusercontent.com/assets/1396971/11393921/80cbddfa-9388-11e5-8da0-431997078c72.jpg)

**Comment by MrSwitch** [comment]
@saurabhsahni we want to report this issue to Yahoo. Is there any guidance around reporting issues my search on YDN led me too try out this link https://developer.yahoo.com/forums/#/categories/oauth-and-openid which resolves to a 404 page.

**Comment by ratheeshkannan** [comment]
@MrSwitch Sir, I've tried using yahoo branch which was done to move from oauth 1 flow to oauth 2 flow for yahoo. I'm getting proper dialog box but I'm not getting the data. The reason maybe yahoo.js was created 11 months ago but hello.js went to numerous iteration after it. I think the yahoo.js is working fine but the older yahoo.js is not compatible to newer version of hello.js. Any plan to migrating yahoo.js to latest hello.js configurations? It'll be very much helpful.

**Comment by MrSwitch** [comment]
Hi @ratheeshkannan sorry no news on this, i'm closing this, please follow #192
