### ISSUE TITLE
Hellojs not working with Internet Explorer 11.

### ISSUE THREAD

**Issue by jemag** [MrSwitch/hello.js#365]
I have an extremely simple implementation of Hellojs that works on chrome / firefox / opera but won't work on Internet Explorer.
Here is some samples from the really simple code I have : 
![html](https://cloud.githubusercontent.com/assets/7985687/11399910/3514f94e-9358-11e5-9bfd-61964ba38438.PNG)
![init](https://cloud.githubusercontent.com/assets/7985687/11399934/5650bf1c-9358-11e5-95bf-51afc14ec740.PNG)
![test](https://cloud.githubusercontent.com/assets/7985687/11399935/5653b4f6-9358-11e5-9627-6adbc6fc2086.PNG) 

Everything works perfectly when I click on the button for google or facebook on other browsers. On internet explorer I get the following message when the facebook or google page popup appears
![trying to close tab](https://cloud.githubusercontent.com/assets/7985687/11400035/fd25a47e-9358-11e5-9c6d-8bd080995ce4.PNG)
And the following error in the console:
![console error](https://cloud.githubusercontent.com/assets/7985687/11400044/04dedc8a-9359-11e5-8ca2-477c87d2e9ba.PNG)
(SyntaxError: Invalid character at hello.all.js:361:5)

I am not gonna lie, before using hellojs I had implemented my own code for the google and facebook sdk, and the same problem would occur. Internet Explorer would tell me the popup is trying to close itself and it would seem to interrupt my javascript code...

The main reason I am using Hellojs was to fix this problem...

I am not sure what is the problem since with the same Internet Explorer I can use different websites social login just fine. I also implemented the most basic hellojs implementation so I am not sure what the problem is.

**Comment by jemag** [comment]
I decided to test it by deploying the small application to a remote web server and it appears to be working. So apparently this bug only happens in localhost. 

Still quite annoying since I cannot test my applications on internet explorer until I deploy it... Any ideas why that is?

**Comment by MrSwitch** [comment]
I haven't come across this, but then I've always used an alias for localhost because some services like Yahoo for instance doesn't let us register "http://localhost" as a callback domain.

I recommend changing your `hosts` file for testing locally. FYI: here's what mine looks like.
```
127.0.0.1  localhost local.adodson.com
```

**Comment by MrSwitch** [comment]
MSDN says:

> Method 2: Add the website to trusted sites list and check if it helps.
a. Open Internet Explorer, click on Tools and then click on Internet Options.
b. Click on the Security tab. 
c. Now click on Trusted sites and then click on sites button.
d. Type the URL of the website in the text box and click on the Add button.
e. When you’re done, click on close.

There is also a [suggested fix](http://stackoverflow.com/questions/357410/bypass-ie-the-webpage-you-are-viewing-pop-up) for the code which we could incorporate into HelloJS if its a problem in the real world.

**Comment by jemag** [comment]
Thank you for the swift response. I tried changing to hosts file to "local.jemag.com"
I also added localhost and local.jemag.com to trusted sites.

It still didn't work locally but kept working remotely.

I was able to disable that popup by going to Internet Explorer -> Security -> Internet 
and disabling the Enabled Protected Mode (which is activated by default in IE 11). So I guess now I can test locally and since it already works remotely it should be fine.

I am not gonna lie, this is kind of strange and I am not sure what is the root cause; why does this happen specifically on local but not remotely...

**Comment by nmoinvaz** [comment]
It appears that in utils.globalEvent the _str_ parameter is not always a string, sometimes it is an object. Changing the code to conditionally parse the parameter only when it is a string seems to prevent the error from occurring.

```
if (typeof(str) == "string") {
	obj = JSON.parse(str);
} else {
	obj = str;
}
```

**Comment by MrSwitch** [comment]
Please create a PR
