### ISSUE TITLE
Github email not coming through after scope is applied

### ISSUE THREAD

**Issue by alexpchin** [MrSwitch/hello.js#366]
Hello MrSwitch, 

I am implementing HelloJS and have everything working for Facebook, Twitter, Google, Instagram and LinkedIn. However, I am trying to request user emails from all that will allow me access to try to link accounts together.

Github's Oauth should allow me access with the scope of: `user:email` or `user` however, I am currently getting a value of `email=''`.

Have you any ideas? The Github popup does ask me for the correct permissions (read-only email).

Many thanks,
Alex

**Comment by MrSwitch** [comment]
The spec for obtaining github email is here https://developer.github.com/v3/users/emails/ i've updated the demo see https://adodson.com/hello.js/demos/github.html#get-user-email

**Comment by alexpchin** [comment]
Thanks for the swift reply.
