### ISSUE TITLE
Do you support the resource owner flow?

### ISSUE THREAD

**Issue by thj-dk** [MrSwitch/hello.js#367]
Simple question. Can't find any documentation on which grant types is supported. Can you clarify? Thank you.

**Comment by MrSwitch** [comment]
Perhaps is the answer. `hello.login` supports custom parameters, i.e...

```javascript
hello('myoauth').login({
    username: 'bob',
    password: 'bobs_secret',
    grant_type: 'password'
}).then(successHandler, errorHandler)
```

However contrary to [the resource owner spec](https://tools.ietf.org/html/rfc6749#section-4.3) this results in a GET request and assumes the authenticating server will redirect to the redirect_uri with the access_token in the querystring - as per all the other flows.

If the provider adheres to the spec a POST request via `hello.api` and storing the response could work.

```javascript
hello('myoauth').api('https://service/auth', 'post', {username:'bob', password: 'bobs_secret'})
.then(function(authResponse) {
    // manually insert the authResponse
    hello.utils.store('myoauth', authResponse); 
});
```

**Comment by thj-dk** [comment]
Interesting. Without knowing much about how the oauth-shim proxying works, will this post-approach work with that?

**Comment by MrSwitch** [comment]
It would not need an `oauth_proxy`, the spec suggests the Access Token is returned in the response from the POST. aka does not need to sign the request with an application secret.

**Comment by MrSwitch** [comment]
inactive
