### ISSUE TITLE
Alias POST me/share (resharing a message) to me/retweet

### ISSUE THREAD

**Issue by sudheesh001** [MrSwitch/hello.js#370]
Having a POST me/retweet which aliases to POST me/share (resharing a message) would make it better for the developers to use it much more easily and makes it easier to onboard new contributors to the project where this is being used since its easier to understand what is happening.

POST me/share with `id` as parameter, successfully retweets but it'd be best if the same can also be called from POST me/retweet with `id` as parameter.

**Comment by MrSwitch** [comment]
Thanks for your suggestion. The "tweet" and "retweet" are proprietary verbs for Twitter. As such its not an endpoint which easily translates to other providers.

If you do want to explicitly use Twitters language then one option is to tap directly into Twitters API. For example a retweet would look like this ...

```javascript
hello('twitter').api('statuses/retweet/' + retweet_id + '.json', 'post');
```

Does that help?

**Comment by sudheesh001** [comment]
Sounds great :+1: Can that tapping feature also be added to the documentation ? Please Feel free to close this issue. :smile:

**Comment by MrSwitch** [comment]
> A relative path to the modules `base` URI, a full URI or a mapped path defined by the module.

Does that sound right?

**Comment by sudheesh001** [comment]
Sounds great @MrSwitch , I'll be closing this now. Thanks a lot
