### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by albertonaperijr** [MrSwitch/hello.js#371]
Hi,

Thanks for this wonderful library.
I just want to ask if this library is compatible or can be use for SINGLE SIGN ON for mobile (android and ios).

Thanks!

**Comment by MrSwitch** [comment]
Please reference what you mean by "single sign on"

**Comment by albertonaperijr** [comment]
Sorry about that. I think I got a little confused about the word single sign on. So, I'll just close this issue. Thanks.
