### ISSUE TITLE
Hello adds default scope: 'basic'

### ISSUE THREAD

**Issue by pawelszymczyk** [MrSwitch/hello.js#372]
Hi

I would like to ask why Hello always adds default scope 'basic'? In documentation it's information that scope is optional and default is null, but in the code is sth like that:
https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L250

I have a problem with this behaviour, in our company we are switching to new oauth server based on spring-security-oauth, in this case all scopes are stricktly checked and server throws "Invalid scope: myScope, basic", I need to pass only myScope to corretly log-in. 

regards Paweł

**Comment by MrSwitch** [comment]
That's a good point, if its unset it shouldn't send anything. I'll update code, in the interim you might like to set it to empty, e.g...

```javascript
scope: {
     basic:''
}
...

**Comment by pawelszymczyk** [comment]
I think it wouldn't help me now cause basic scope is always append at the end of the scopes, look:

firrsty is set on p.qs: https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L250
and next is appended from p.qs: https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L268

so I have to wait until change goes released.

**Comment by MrSwitch** [comment]
Yes it would. Scope names are then mapped, to the module definition of the `basic` scope - here https://github.com/MrSwitch/hello.js/blob/v1.9.8/src/hello.js#L288

For example this is how VK is defined - https://github.com/MrSwitch/hello.js/blob/v1.9.8/src/modules/vk.js#L18

**Comment by pawelszymczyk** [comment]
Yeah, you are right it works :+1: but still pretty tricky ;)
