### ISSUE TITLE
Google id_token

### ISSUE THREAD

**Issue by BilalYazbek** [MrSwitch/hello.js#373]
Hello, 
Iam trying to retrieve google id_token, but iam unable to get it in any callback, neither r nor s
```javascript
 hello('google').login().then(function(r){
});
  hello('google').api('me').then( function(s){
});
```
i try all the possible scopes but i was unable to get it.
* r output:
  * access_token: xxxxx
  * authuser:xxxxx 
  * client_id: xxxxx
  * expires:xxxxx
  * expires_in:xxxxx
  * hd:xxxxx
  * network:xxxxx
  * prompt:xxxxx
  * redirect_uri:xxxxx
  * scope:xxxxx
  * session_state:xxxxx
  * state:xxxxx
  * token_type:xxxxx
* s output
  * circledByCount
  * displayName
  * domain
  * email
  * etag
  * first_name
  * gender
  * ...

**Comment by MrSwitch** [comment]
My understanding is an **id_token** is supplied as part of OpenID Connect authentication flow only. The HelloJS Google module alike [Google's own Javascript libary](https://developers.google.com/api-client-library/javascript/features/authentication) uses the OAuth2 auth flow, **id_token** is not provided under the spec.

**Comment by MarSoft** [comment]
Not correct. `id_token` will be provided if you request it explicitly with `response_type=token id_token` rather than just default `response_type=token`.
Another question is how to ask Google to include that additional info (username and email etc) in the token. Probably it depends on scopes.
