### ISSUE TITLE
Detect initial "loading" state

### ISSUE THREAD

**Issue by omichelsen** [MrSwitch/hello.js#374]
When users come to my website, I would like to know whether hello.js is working (auto-login), so I can show a loading spinner. Also it would help a lot on pages that require auth, to know whether hello.js is working on auth.

I know I can poke around localStorage myself to see if there is anything saved, but is there an official way - maybe a promise or special event I can listen for?

**Comment by MrSwitch** [comment]
`hello.on('auth.login', handler)` is triggered periodically every second, it relies on `hello.init` having set the clinet_id's.

What are you proposing?

**Comment by omichelsen** [comment]
Well `auth.login` triggers once login is successful, but this might take up to several seconds to complete.

I would like an `auth.init` event as soon as hello.js starts doing auto-login so I can make the UI wait for the action to succeed/fail before loading other parts of the UI. Maybe alternately a callback function on hello.init which tells me whether the user has stored credentials?

**Comment by MrSwitch** [comment]
Hey sorry for the belated response. I think this is a good idea. I can see that several events would need to occur. "auth.refreshing" (init is a bit vague) followed by "auth.failed" or "auth.login".

**Comment by omichelsen** [comment]
I was thinking adding the 'auth.refreshing' event in [line 350](https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L350) would be enough?

```js
if ('login' in provider && typeof (provider.login) === 'function') {
    // Format the paramaters according to the providers formatting function
    provider.login(p);
    emit('auth.refreshing');
}
```

Not so well into the code base yet, so just a suggestion.

**Comment by omichelsen** [comment]
Awesome, thanks man! :+1:

**Comment by MrSwitch** [comment]
Went with 'auth.init' afterall.

**Comment by omichelsen** [comment]
I like it. Could I get you to do a `npm publish` as well?

**Comment by MrSwitch** [comment]
It's only being triggered prior to a HTTP request being sent to create or refresh tokens. It will not fire if the current session is still valid. On page refresh with a valid token you will just get a 'auth.login' event fired.

**Comment by MrSwitch** [comment]
Did `npm publish`, just not showing up on https://www.npmjs.com/package/hellojs

**Comment by Rmannn** [comment]
What is the good way to listen for the hello init ?
When the user is not logged in, what is the good way to listen for the hello init ?
