### ISSUE TITLE
Get Yahoo me/friends does not work

### ISSUE THREAD

**Issue by Syperia** [MrSwitch/hello.js#375]
Got a trouble getting contacts from Yahoo.
Tried demos, did not get any yahoo contacts as well

Steps to reproduce:
1. go to https://adodson.com/hello.js/demos/friends.html#helloapi-mefriends-
2. click 'Get Yahoo me/friends'
3. sign in
4. open dev. tools (F12)
5. expected result, something like in here: https://developer.yahoo.com/yql/console/?_uiFocus=social&q=select%20*%20from%20social.contacts%20where%20guid%3Dme%3B
actual: 
```json
{"query":{"count":0,"created":"2015-12-08T23:45:53Z","lang":"uk-UA","results":null}}
```

**Comment by SkyHacks** [comment]
I'm having the same issue.

**Comment by MrSwitch** [comment]
Your account doesn't have any contacts, otherwise `count: 0` would not be empty.
Is it that you would like a response from the demo, to say something like "0 contacts found" ?

**Comment by Syperia** [comment]
Here is a screenshot with contacts I've got:
![1](https://cloud.githubusercontent.com/assets/6148466/11683321/bc264940-9e72-11e5-8e6e-20ba88c5f4fb.PNG)
Here is YQL Console output:
![2](https://cloud.githubusercontent.com/assets/6148466/11683322/bc27746e-9e72-11e5-8b1a-c53413c86d01.PNG)
Here is Hello.js demo:
![3](https://cloud.githubusercontent.com/assets/6148466/11683323/bc28be0a-9e72-11e5-964d-64261c760afb.PNG)

**Comment by MrSwitch** [comment]
Well that's pretty hard to argue with, it seem there is something wrong with Yahoo as i get results returned.

![image](https://cloud.githubusercontent.com/assets/947163/11683594/b472e4e2-9e63-11e5-8993-8373495d66a7.png)

**Comment by Syperia** [comment]
Tried both my app and hellojs demo via **US proxy**. Get Yahoo me/friends works fine.
Quite strange.

**Comment by MrSwitch** [comment]
... so it works now?

**Comment by Syperia** [comment]
Not really, MrSwitch. Still does not work from my country. Probably there are a lot of people who use hello.js outside US/UK and could face this problem.
Anyway it's not this lib's issue.
I'll go check out yahoo community for now. Thanks

**Comment by MrSwitch** [comment]
Thanks @Syperia. Please include here any links to articles/discussions/issues which you find.

**Comment by SkyHacks** [comment]
My issue is similar. I started with 3 demo contacts and hello.js returned them all in the data array. Once I added a 4th contact, it began paging the results. I followed the steps outlined in the paging example but anytime I pass in the resp.paging.next path to the callback, it returns a null query like the one that Syperia included above.

I have checked that the 'next' path is correct and the callback works for the first contact so I believe that everything is setup correctly. I am recursively calling next to try and get all of the contacts. 

I'm in the middle of trying to debug the issue, but here is the function that I'm working with:
```
getYahooFriends('me/friends')
var friendsArray = []

function getYahooFriends (path) {
  hello(network).api(path, {limit: 100})
  .then(function (r) {
    friendsArray.push(r);
    console.log(path,r);

   if (r.paging && r.paging.next) {
      getYahooFriends(r.paging.next);
    }  else {
      defer.resolve(friendsArray);
    }                          
  }, function (err) {
    console.log(err);
    defer.reject(err);
  });
}
```

**Comment by SkyHacks** [comment]
I just got the same result from the test page --> https://adodson.com/hello.js/tests/#hello-x-api-path--method--data--callback--

The first page returns 3 contacts but the next button returns:
```
{
 query: {
  count: 0,
  created: "2015-12-09T16:11:04Z",
  lang: "en-US",
  results: null
 }
}
```
<img width="540" alt="screen shot 2015-12-09 at 9 12 56 am" src="https://cloud.githubusercontent.com/assets/10717361/11690689/1fab9aec-9e55-11e5-87f1-a00c00cc4985.png">

**Comment by mebibou** [comment]
@Syperia could you explain how you made it work? I have the same problem, and tried using the proxy provided on `https://auth-server.herokuapp.com/proxy` but I still get the same result as you were.

**Comment by amrfayad** [comment]
@Syperia could you explain how you made it work? I have the same problem, and tried using the proxy provided on https://auth-server.herokuapp.com/proxy but I still get the same result as you were.

**Comment by AdrianApan** [comment]
@Syperia Any luck with this? Could you let us know if you found a solution for this issue? Thanks!
