### ISSUE TITLE
Files corrupted when uploading to OneDrive

### ISSUE THREAD

**Issue by PsyGik** [MrSwitch/hello.js#378]
I'm trying to upload SpreadSheet | Word | PowerPoint files to OneDrive. It uploads successfully, however the files do not open in Office Online. I've tried *.docx, *.pptx, *.xlsx.
I'm using     'me/files', 'POST'

P.S: The same files when uploaded to Google Drives, opens perfectly in Google Docs.

**Comment by MrSwitch** [comment]
Sorry for belated response, have you gotten anywhere with this?

**Comment by PsyGik** [comment]
Unfortunately not. The use case on which I was working on was to create a new file in OneDrive, but their API does not support that. So as a workaround I was tried to upload empty files to OneDrive. But it doesn't open in Office Online. 

However I was able to create a *.docx file like so,

        function createNewDoc(name) {
    var htmlString = "<html><body></body></html>";
    var byteNumbers = new Uint8Array(htmlString.length);
    
    for (var i = 0; i < htmlString.length; i++) {
       byteNumbers[i] = htmlString.charCodeAt(i);
        }
        var blob = new Blob([byteNumbers], {type: "text/html"});
        socialAPI.uploadFile('windows', blob, 'name', 'folder.87ash7ashb7a2').then(function (resp) {
            console.log("response for uploading file", resp);
        })
    }

**Comment by MrSwitch** [comment]
:)

Glad you found an alternative. I'm going to close this and revise the Windows module at some point.
