### ISSUE TITLE
Silent refresh - Iframe fail with X-Frame-Options DENY when force is set to false

### ISSUE THREAD

**Issue by mitjacotic** [MrSwitch/hello.js#379]
Hi,

refreshing tokens for google silently fail if using `force=false` with `login` method, it throws the X-Frame-Options DENY error which can not be caught.

I've gone through hello.js code and did these edits:

[here](https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L764):
```javascript
iframe: function(src, cb) {
  var ifr = this.append('iframe', {src: src, style: {position:'absolute', left: '-1000px', bottom: 0, height: '1px', width: '1px'}}, 'body');

  ifr.onload = function () {
    // if same origin fails, we will not be able
    // to access the contentDocument.location
    // this seems to be a only way to find out
    // something went wrong
    try {
      loc = ifr.contentDocument.location
    } catch (e) {
      if('function' === typeof cb) {
        cb('Iframe load failed.')
      }
    }
  }

},
```

[and here](https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L392):
```javascript
if (opts.display === 'none') {
  // Sign-in in the background, iframe
  utils.iframe(url, function (err) {
    if(err) {
      var response = error('blocked', 'Iframe was blocked')
      response.network = p.network;
      promise.reject(response);
    }
  });
}
```

and now the flow works ok. I just need to test it in safari, Oliver's comment says it's not working and linked a workaround which is not accessible any more http://stackoverflow.com/questions/12062081/catch-x-frame-options-error-in-javascript.

I also see that you started to [pass another param into iframe
method](https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#L394) which is currently not used but in the hello version we're using that's not there:)

**Comment by mitjacotic** [comment]
I should probably also say that it's a bit tricky to debug this case, you need to explicitly set a valid refresh token and invalid access token with hello and then in a first (few) tries it fails but then it starts to work.

**Comment by MrSwitch** [comment]
@mitjacotic, The library should handle refresh automatically, but for some services - like Google - it's not always possible to get it, as you've noticed. The google module has this disabled `refresh:false`. And HelloJS knows not to attempt a background refresh unless there is a saved "refresh_token" (which only is returned via the Explicit Grant - rather than the Implicit Grant). Can you tell me the reason for needing control over the refresh, or why HelloJS rules aren't up to scratch?

Good catch btw: it would be good to have this iframe error checking in the library.

**Comment by mitjacotic** [comment]
Our web app among other things allows users to connect with various services so they can attach files from gdrive/dropbox etc and upload files to them.
We have our oauth shim server running which is storing the refresh tokens per user and then send them to the clients when they login. We're doing this because we want to leverage all the things we can to client side (yes, one of those:) and also want clients to have as seamless integration as it's possible without distractions.
After they login we send them the tokens and call `hello.init` with those to store them into localstorage so they don't need to go through 'popup process' in every browser they use. We want to avoid the popups that's why we first call `login` with force=false but then the error doesn't get caught in case auth token is expired and we can't do a popup fallback.
I know this could be solved on server side, but having this error caught with hello would make it even more complete.

**Comment by MrSwitch** [comment]
Interesting scenario - storing and notifying all the clients of the "refresh_token".

It would be great if you could add a test or two and create a PR for your work on the `utils.iframe` error handling.

**Comment by MrSwitch** [comment]
@mitjacotic I ran a little test on your proposed onerror handler. Unfortunately cross-origin access also triggers first to its hard to distinguish.

If you have any more to add please do say, otherwise i'll close this for now.
