### ISSUE TITLE
using plugin for instagram

### ISSUE THREAD

**Issue by cordova-android** [MrSwitch/hello.js#382]
i trying to use hello.js for instagram for cordova android/ios
i insert the clientid in page instagram.html
put i need to set redirect url 
so how i can made redirect url go to other page but in app cordova?

**Comment by MrSwitch** [comment]
The redirect_uri page itself doesn't need to exist in Cordova apps. However the value of the URL does need to be permitted when with the registered client_id.

**Comment by cordova-android** [comment]
so how i can get access token
while this access token is set in query string for redirect_uri  set in instgram

**Comment by jmgamboa** [comment]
@cordova-android you need to register your redirect-uri in the instagram console https://www.instagram.com/developer/. Then go to manage clients. If you do not see your redirect-uri there, that you specify in your hellojs. you need to update it

**Comment by cordova-android** [comment]
@jmgamboa  i set redirect to redirect.html as in hello js folder but it tell me not match
i tried set http://localhost:8200/redirect.html but is didn't open in cordova 
and i just need this page to get access token

**Comment by MrSwitch** [comment]
Have you looked at the [demo page](https://github.com/MrSwitch/hellojs-phonegap-demo), in particular how the `redirect_uri` pertains to the `client_id` and not to the location of the app. https://github.com/MrSwitch/hellojs-phonegap-demo/blob/master/index.html#L56

**Comment by cordova-android** [comment]
you mean i set redirect url to http://adodson.com/hello.js/redirect.html in my Instagram app and in instagram.html to  http://adodson.com/hello.js/redirect.html

but i need to know how i will catch accesstoken from this mentioned page?

**Comment by MrSwitch** [comment]
> but i need to know how i will catch accesstoken from this mentioned page?

In the case of cordova apps this is handled by HelloJS in the app - and does not rely on the page at the redirect_uri at all.

When the auth-flow popup is launched the app will monitor the popups URL, see https://github.com/MrSwitch/hello.js/blob/v1.10.0/src/hello.js#L1287

When the popups URL matches the redirect_uri it will complete the login, taking any parameters like access_token or error as indicative of a success of failure.

**Comment by cordova-android** [comment]
but for redirect url page "http://adodson.com/hello.js/redirect.html"
not close automatic as when i click close it get failed error
"Failed making API request Login has been cancelledFailed making API request Login has been cancelled"

**Comment by MrSwitch** [comment]
And have you followed the setting up guide at https://github.com/MrSwitch/hellojs-phonegap-demo ?

**Comment by cordova-android** [comment]
i double check about set demo but i guess that error for in app browser i use command 
cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git

is there an other plugin for inappbrowser to work correctly?

**Comment by MrSwitch** [comment]
Getting off topic. I'll close this. I'm not an authority, please provide your workaround if you find one.
