### ISSUE TITLE
question: forcing use of sessionStorage?

### ISSUE THREAD

**Issue by tony-kerz** [MrSwitch/hello.js#383]
i tried overriding `hello.utils.store` per @MrSwitch [suggestion on gitter](https://gitter.im/MrSwitch/hello.js?at=566b1e396a17cd3b36dc82ff) to force use of `sessionStorage` for `hello` key, which does seem to do the trick in terms of storing the `hello` key in `sessionStorage`, but... i am witnessing [the `hello` key __also__ being placed in `localStorage` on login](https://gitter.im/MrSwitch/hello.js?at=5689f4af9606b15a055eb620).

any guidance/ideas appreciated!

regards,
tony.

**Comment by MrSwitch** [comment]
Hi @tony-kerz i've left you a comment on Gitter i'll close this here for now and see how we get on there.
