### ISSUE TITLE
Twitter login bypasses popup and goes straight to the shim

### ISSUE THREAD

**Issue by jmgamboa** [MrSwitch/hello.js#384]
I've written my own shim for google and twitter in python.  Google works fine but adding twitter credentials goes directly to my shim and bypasses the popup/page. Any guess as to why it behaves like this? My frontend code is a bit abstracted so Id prefer you do not go off that; just posting it so you get an idea
   
    ServiceProviderModel.addServiceProvider = function(provider){
     hello.login(provider, _.extend(
            Constant.HELLO_JS_PROVIDER_OPTIONS[provider],
            {
                oauth_proxy: [
                    '/auth/shim/web/',
                    provider,
                    '/',
                    encodeURIComponent(LocalStorageFactory.getJwtToken()),
                    '/'
                ].join('')
            }
        ));
    };

    angular.module('ConstantProvider', [])
          .constant('Constant', {
               APP_NAME: 'Test',
               API_URL: '/api/v2/',
               AUTH_REDIRECT: '/home',
               UNAUTH_REDIRECT: 'login',
               YOUTUBE_REGEX: /(?:youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\?(?:\S*?&?v\=))|youtu\.be\/)([a-zA-Z0-9_-]{6,11})/,
               HELLO_JS_INIT: {
                            google: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                           twitter: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                },
               HELLO_JS_PROVIDER_OPTIONS: {
                   google: {
                         scope: [
                            'email',
                            'profile',
                            'https://www.googleapis.com/auth/userinfo.profile',
                            'https://www.googleapis.com/auth/youtube.readonly',
                            'https://www.googleapis.com/auth/yt-analytics.readonly',
                         ].join(',')
                      }
                    }
              });

**Comment by MrSwitch** [comment]
For OAuth1 providers - like Twitter - the authentication request has to be signed. So HelloJS first directs the request for login to your oauth_proxy server. 

Does that help?

**Comment by jmgamboa** [comment]
so your saying this behavior is normal. and my proxy server has to sign a request before the user selects which account they would like to log into. the reason i brought this up because with the example on the hellojs homepage;. it seems as though it goes to twitter first then your authserver after.

**Comment by MrSwitch** [comment]
> with the example on the hellojs homepage;. it seems as though it goes to twitter first then your authserver after.

... yes its pretty quick, but it has to happen that way.

**Comment by jmgamboa** [comment]
>  it goes to twitter first then your authserver after.
> ... yes its pretty quick, but it has to happen that way.

says it goes to twitter first

> So HelloJS first directs the request for login to your oauth_proxy server.

for me implies the proxy server gets hit first, not twitter

**Comment by MrSwitch** [comment]
Sorry if that was confusing. I meant that because it *seemed* like it was just going to twitter initially then the oauth_proxy is very quick.

Basic OAuth1 flow:
 * Create a signed URL (using secret and some cryptography)
 * Send client to that url to grant application
 * Interpret the response and make another signed request server-to-server to get authorization tokens.

I hope that helps

**Comment by jmgamboa** [comment]
@MrSwitch Thank you for for clarifying that up. I was re-reading the oauth flow. This is correct. https://dev.twitter.com/web/sign-in/implementing. Thanks mate. Hope to open source my python shim to have alternative proxy-server options in other languages.
