### ISSUE TITLE
How can I find the service used to log-in from existing sessions?

### ISSUE THREAD

**Issue by SukantGujar** [MrSwitch/hello.js#386]
Hello :),

I have just started using hello for one of my weekend projects. I need your opinion on this...

On my site, I will be providing the user to login via Google and Facebook. But the user will pick anyone only, she will either login via Google or Facebook. Next time when she visits my site, I need to know which provider was she logged-in with. There are several ways to do this, but as hello already persists auth session info in localStorage, I was wondering if I can retrieve it via some API. I came across "getAuthResponse", but it is returning null unless I invoke it by passing the correct provider name.

Is this possible? One way I could think of was to simply keep calling getAuthResponse in a loop for Google, Facebook and anything else which I may support in future.

Thanks!

**Comment by MrSwitch** [comment]
Correct, 

```javascript
for (var x of hello.services) {
    if (hello(x).getAuthResponse()) {
        console.log("Session was once created for " + x);
        break;
    }
}
```

I can see that this could be simplified. I can't see a reason why `hello.getAuthResponse()` shouldn't return the whole lot as an object.

**Comment by SukantGujar** [comment]
Thanks, I am doing the same at present, and I had the same thoughts about the no param version of getAuthResponse.

On a different note, I wanted to plugin bluebird as the promise lib. Do you have any plans to support third party promises? Something like the middleware pattern common across nodejs.... hello.use(Promise) where Promise will be a bluebird Promise instance. I hate to make this discussion polluted, but just wanted to get your thoughts quickly.

**Comment by MrSwitch** [comment]
Nope, but when support for IE<10 is dropped HelloJS will use browsers native Promise API.

**Comment by jimmed** [comment]
@MrSwitch, just saying: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

> Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical supports and security updates.

**Comment by MrSwitch** [comment]
@jimmed good call. Alas Promise API is not in IE11 http://caniuse.com/#feat=promises, i assumed it was. Oh well.

**Comment by SukantGujar** [comment]
I'd very much recommend supporting third party promises, given bluebird is inherently faster than the native ones.
