### ISSUE TITLE
twitter email doesn't received!

### ISSUE THREAD

**Issue by vatex** [MrSwitch/hello.js#387]
http://stackoverflow.com/questions/34695640/doing-twitter-authorization-email-doesnt-received-using-hello-js-library

**Comment by vatex** [comment]
I had enabled email feature in apps.twitter.com

**Comment by MrSwitch** [comment]
Refer to the Twitter API on obtaining this property.

**Comment by jmgamboa** [comment]
@vatex a few gotchas with this. first, a users'  email needs to be made public. this can be done through the twitters profile settings. if the users email is set to private, you cannot retrieve the item.  second is, for some of your app's settings; if you decide to change them, you made need to generate new keys. ie if you had only read access set initially and want to add write access;  you need to generate new keys, after changing this. hope this helps; personally experienced difficulties getting help on the twitter forums.

**Comment by jmgamboa** [comment]
@vatex also ensure you've added read-email to the scope end in hellojs. https://adodson.com/hello.js/#scope
