### ISSUE TITLE
Anyway to over ride your auth server for instagram?

### ISSUE THREAD

**Issue by jmgamboa** [MrSwitch/hello.js#388]
Hi again, quick question. For my hellojs instagram implementation, I don't want to use your authserver. instead, i just want to use my own auth shim I wrote in python. (trying to eventually open source the code). I supply the oauth_proxy with my shims' endpoint. is this not the way to over write the instagram redirect?  
error=invalid_credentials&error_message=The%20client_id%20%2248cd6574b23a4ef486ccb985c74bc82d%22%20is%20unknown.%20Register%20your%20app%20credentials%20by%20visiting%20https//authserver.herokuapp.com&state=%7B%22client_id%22:%2248cd6574b23a4ef486ccb985c74bc82d%22,%22network%22:%22instagram%22,%22display%22:%22page%22,%22callback%22:%22_hellojs_ahj6o3xl%22,%22state%22:%22%22,%22redirect_uri%22:%22http://127.0.0.1:8000/v2/%22,%22scope%22:%22basic%22,%22page_uri%22:%22http://127.0.0.1:8000/v2/%23/settings/service-provider%22,%22oauth%22:%7B%22version%22:2,%22auth%22:%22https://instagram.com/oauth/authorize/%22,%22grant%22:%22https://api.instagram.com/oauth/access_token%22%7D,%22oauth_proxy%22:%22https://auth-server.herokuapp.com/proxy%22%7D

**Comment by MrSwitch** [comment]
I don't think you've set the right property.  Can you copy and paste your implementation to `hello.init`

**Comment by jmgamboa** [comment]
I don't believe its the oauth_proxy param because it works for my other providers.  my hellojs code is convoluted but i'll post it if you want. However, I did learned more about the issue. 

if i'm logged into instagram via the instagram website this issue occurs. if i sign out and click hellojs instagram button, it'll bring me to the instagram login page at the very least.  The button did not even redirect to instagram when I was already logged in. Will keep you up to date with further notes. Is this an issue you came across in maybe earlier versions? I may need to update.

**Comment by jmgamboa** [comment]
So I'm going to post my code.  While I have a few concerns, my priority question still stands and is with over riding the proxy or redirect uri. I still get this error. The client id is unknown. Register your app credentials by visiting https//auth-server.herokuapp.com.

``` javascript
angular.module('ServiceProviderModel', ['BaseModel', 'LocalStorageFactory', 'ConstantProvider'])
.run(function(Constant) {
    hello.init(
        Constant.HELLO_JS_INIT,
        {
            response_type: 'code',
            display: 'page',
            force: true,
        }
    );
})
.factory('ServiceProviderModel', function(BaseModel, Constant, LocalStorageFactory){

    var ServiceProviderModel = _.clone(BaseModel);

    ServiceProviderModel.endpoint = 'serviceproviders/:slug/:detail/';
    ServiceProviderModel.name = 'service provider';

    var format_jwt_url = function(provider){
            return jwt_url;
    };

    ServiceProviderModel.addServiceProvider = function(provider){

        hello.login(provider, _.extend(
            Constant.HELLO_JS_PROVIDER_OPTIONS[provider],
            {
                oauth_proxy: [
                    '/api/v2/auth/shim/web/',
                    provider,
                    '/',
                    format_jwt_url(provider),
                ].join(''),
                redirect_uri: 'localhost:8000'
            }
        ));

    };

    return ServiceProviderModel;

});
```

**Comment by MrSwitch** [comment]
@jmgamboa works for me!

In the screenshot i've defined `oauth_proxy` to a dummy path "http://localhost/proxy". The popup has this as the expected path. I also tested it working when `display=page`.

![image](https://cloud.githubusercontent.com/assets/947163/12302672/46d40278-ba1e-11e5-98f7-239db317aafb.png)

**Comment by jmgamboa** [comment]
<img width="326" alt="screen shot 2016-01-13 at 1 20 36 pm" src="https://cloud.githubusercontent.com/assets/3579209/12303465/7b5a2bec-b9f8-11e5-99f0-d04fb29c3d8e.png">

after setting the params if you look at the authiroze url you still see addodson in the redirect url



instagram.com/accounts/login/?force_classic_login=&next=/oauth/authorize/%3Fscope%3Dbasic%26client_id%3De47d210f864c4b1ca94225ddab97205a%26response_type%3Dtoken%26**redirect_uri%3Dhttps%253A%252F%252Fadodson.com%252Fhello.js**%252Fmyproxyhost.com%26display%3D%26state%3D%257B%2522client_id%2522%253A%2522e47d210f864c4b1ca94225ddab97205a%2522%252C%2522network%2522%253A%2522instagram%2522%252C%2522display%2522%253A%2522popup%2522%252C%2522callback%2522%253A%2522_hellojs_1d5d5npc%2522%252C%2522state%2522%253A%2522%2522%252C%2522 **redirect_uri%2522%253A%2522https%253A%252F%252Fadodson.com%252Fhello.js** %252Fmyproxyhost.com%2522%252C%2522scope%2522%253A%2522basic%2522%257D

**Comment by MrSwitch** [comment]
You've given it a relative path, prefix with "http://"

**Comment by jmgamboa** [comment]
yup thats correct. with google, facebook, and twitter, it does accept the relative path though. thanks for clearing that up.

**Comment by MrSwitch** [comment]
Hmmm i can't replicate that issue with the other providers. Moreover the logic is in `hello.login` rather than the service modules, which are more just configs.

**Comment by jmgamboa** [comment]
set your oauth_proxy to this one your website /hello.js/redirect.html. and it works the same. also in my own code im only providing a relative path to my proxy and it works fine for my other providers.

**Comment by jmgamboa** [comment]
i will try and provide an example for how relative paths work. the issue is that i was providign query_params to the proxy.  for some reason if a query param is provided, your authserver name over rides the proxy param.
