### ISSUE TITLE
continue:using plugin for instagram 

### ISSUE THREAD

**Issue by cordova-android** [MrSwitch/hello.js#390]
continue issue No #382

after i checked and open pages in firefox not in emulator i find error in firebug says

Error: Permission denied to access property "_hellojs_93kh1lo8"
if (parent && cb && cb in parent) 

and redirect url page "http://adodson.com/hello.js/redirect.html"

**Comment by MrSwitch** [comment]
Please familiarise yourself with the same origin policy. This is why the redirect uri needs to have the same origin as your webpp.

**Comment by cordova-android** [comment]
but this will be the same error in cordova app as origion not same

**Comment by MrSwitch** [comment]
They are different environments.

**Comment by cordova-android** [comment]
i mean in android emulator parent.html path  will be file:*
and in Instagram client management not accept redirect url like file:*
 it need http or https
so how i can match android page with redirect url

**Comment by MrSwitch** [comment]
Same origin policy does not apply in cordova app.

**Comment by cordova-android** [comment]
can you give me link for full example using help.js in cordova app
i mean it include platform like ios or android

**Comment by cordova-android** [comment]
can you give me link for full example using help.js in cordova app
i mean it include platform like ios or android as i get error in Xcode out put says 
failed to load webpage with error :the operation couldn't be completed

**Comment by MrSwitch** [comment]
Please raise that issue on the demo application https://github.com/MrSwitch/hellojs-phonegap-demo
