### ISSUE TITLE
What are xhr: function( p, qs ) params ?

### ISSUE THREAD

**Issue by fyyyyy** [MrSwitch/hello.js#391]
from http://adodson.com/hello.js/modules.html#writing-your-own-module
what is p and qs ?

```javascript
hello.init( { ...
  xhr: function( p, qs ) {
  if (p.method !== 'get' && p.data) {

**Comment by MrSwitch** [comment]
p= The request object.

```
{
   method: 'get',
   data: [object],
   query: [object],
   url: 'https://asdasd/'
}
```

qs= Is just a reference to p.query for simplicity.

The function is invoked here https://github.com/MrSwitch/hello.js/blob/v1.10.0/src/hello.js#L1975

**Comment by fyyyyy** [comment]
Thanks :+1:
