### ISSUE TITLE
Can't login to twitter using hello.js 

### ISSUE THREAD

**Issue by beshad** [MrSwitch/hello.js#392]
Hi 

I think this subject has been discussed before and i have read it but i still can not resolve it. here is the hello.init script:

```javascript
hello.init({
   twitter: "API_KEY_HERE"
}, {
    redirect_uri: 'TO_MY_REDIRECT_PAGE',
    oauth_proxy: 'https://auth-server.herokuapp.com/proxy'
});
```
i have already registered my app in herokuapp.com but i still can't login to twitter. facebook, google, windows all are working flawlessly (many thanks to the hello.js developer) but i have not had any success with twitter. the login/signin popup window flashes for a second then disappears without giving me any option to do anything. is there something that i am doing wrong? 

any help would be really appreciated. 

cheers

Beshad

**Comment by MrSwitch** [comment]
Try printing out the response

**Comment by jmgamboa** [comment]
@beshad do you have implicit login turned on? it could be the case that you are logging in implicitly and getting the authenticated session. also, you can ensure your logged out by going to twitter directly and signing out.  This will default the login behavior to explicit (where a popup occurs and you have to enter your credentials)

**Comment by beshad** [comment]
Thanks for the reply and help. here is the code i used:


the other three (google, windows and Facebook) working fine but twitter is not doing anything, the login screen flashes and then disappears. how do i print out the response? i have logged out of the twitter. 

to me it appears the hello.init doesn’t recognise my twitter at all for some reason because even after i commented out the twitter line or even entered a random incorrect series of numbers/chars it does the exact same thing. 

thank you for your help again

**Comment by jmgamboa** [comment]
@beshad. Your code does not appear. Also are you saying your issue was resolved?

**Comment by beshad** [comment]
hello again, 

sorry here is the code again:

hello.init({
    //facebook: "214664312209827",
    //windows: "0000000040181399",
    //google: "555926502433-di46q440atl2vbkl47a9ulhe73eiu7ru.apps.googleusercontent.com",
    twitter: "NNxDWT64pUbbomqY4NAEWv5ka" //this is my consumer key
//}, {redirect_uri: 'index.html'});

}, {redirect_uri: 'index.html',
    oauth_proxy:"https://auth-server.herokuapp.com/proxy",
    oauth_version: '1.0a'
});

the issue is not solved yet. all other logins work fine i just can’t seem to get the twitter log in to work. cheers

**Comment by MrSwitch** [comment]
@beshad The client id 'NNxDWT64pUbbomqY4NAEWv5ka' is not registered at https://auth-server.herokuapp.com/proxy

**Comment by beshad** [comment]
i have been to https://auth-server.herokuapp.com/#-auth-server <https://auth-server.herokuapp.com/#-auth-server> and have saved the below:

reference: twitter
domain: http://127.0.0.1:63342/more_login_Practice/index.html
client_id: NNxDWT64pUbbomqY4NAEWv5ka
client_secret: UapDzHzerGLuzkGy0fWAuWqrgla6YxWG3nfPNkfMjd5adrecWZ
grant_utl: http://127.0.0.1/more_login_Practice/index.html


you are right, i did have a different client code at https://auth-server.herokuapp.com/proxy <https://auth-server.herokuapp.com/proxy> but i changed that to the correct one now. but that seems to never made any difference before. i do get redirected to the redirect_url but i don’t get a login prompt window or anything else at all.  

hello.init() appears to be completely ignores whatever code or numbers etc i enter in front of twitter: 

cheers

Beshad





hello.init({
    facebook: "508195812685952",
    windows: "0000000040181399",
    google: "555926502433-77d4pg1pvd1tv3dpsu8hapdi5vt6jf0j.apps.googleusercontent.com",
    twitter: "NNxDWT64pUbbomqY4NAEWv5ka"
}, {redirect_uri: 'map.html'
    ,oauth_proxy:"https://auth-server.herokuapp.com/proxy"
});

**Comment by MrSwitch** [comment]
Without seeing your full implementation its hard to tell. You haven't said what the results of catching errors was... 

> hello(network).login().then(console.log.bind(console),console.error.bind(console));

**Comment by beshad** [comment]
the error is: 
Uncaught ReferenceError: network is not defined
(anonymous function) @ script.js:39
fire @ jquery.js:3221
self.fireWith @ jquery.js:3351
jQuery.extend.ready @ jquery.js:3799
completed @ jquery.js:3809

i also get the second error:

Uncaught ReferenceError: hello is not defined
(anonymous function) @ script.js:30
j @ jquery.min.js:2
k.fireWith @ jquery.min.js:2
n.extend.ready @ jquery.min.js:2
I @ jquery.min.js:2

the hello.init(0 works because i can log in to other socials networks and can also get the user name email etc easily so not sure why i get an not defined error for hello

**Comment by MrSwitch** [comment]
Hmmm, well it looks like you haven't wired it up properly. And thats not what i meant by seeing your implementation.

**Comment by shahinsha1** [comment]
I too face the same issue as like beshad
Object {error: Object, network: "twitter"}error: Objectcode: "cancelled"message: "Login has been cancelled"__proto__: Objectnetwork: "twitter"__proto__: Object(anonymous function) @ hello.js:1029func @ hello.js:1010

Am using the same code from the github. I spend 2days till am not get any good solution.

**Comment by jmgamboa** [comment]
@shahinsha1 can you post your code?

**Comment by shahinsha1** [comment]
Am using the sample code in my app but still cant found any good solution. but demo app working perfectly in my device
hello.init({
                facebook : '160981280706879',                
                twitter: 'eQuyZuECKWPiv3D7E4qdg'
            }, {
                //
                // Define the OAuth2 return URL
                // This can be anything you like, as long as its the callback associated with the your provider-app client id.
                // It could even be localhost, e.g. http://localhost/somepath as phonegap is not run from a domain so SameOrigin breaks, instead we take advantage of being able to read the popups URL in PhoneGap
                redirect_uri : 'https://adodson.com/hello.js/redirect.html'
            });

            function login(network) {
                var hi = hello(network);

                hi.login()
                .then(function(r) {
                    log(r);
                    return hi.api('me');
                })
                .then(log, log);
            }

            function log(r){
                var s = document.createTextNode(JSON.stringify(r, null, "\t"));
                var pre = document.getElementsByTagName('pre')[0];
                pre.insertBefore(s, pre.firstChild);
            }

**Comment by shahinsha1** [comment]
Hey I found the solution that was my mistake. InApp browser is the victim

**Comment by jmgamboa** [comment]
@beshad. did you try going to twitter manually, and logging out. then trying to login through your app via twitter. also, you say that the popup occurs. does the popup always occur? or only the first time you try to auth with twitter.  the fact the popup occurs tells me that configuration is correct and that its something other than that. if you can try, and copy and paste the pop up url.

**Comment by beshad** [comment]
Hi Joaquin,

my twitter log in finally works. i still don't know what i exactly did to
fix this issue but it is working in my app now. although i am having the
same issue with the second app now and i will finding out what causing it.
the pop-up screen appears and disappears regardless of if i am already
logged in twitter or not. it totally ignores the twitter app-id line in
hello.init and skipped to redirect line. i noticed taking the hello.js
script out of the $(document).ready(function({}) block also makes a
difference. it clashed with my Google maps app and one of them wasn't
working depending on which one was at the top of my code! pretty strange
problem.

as i said i do have a fully working hello.js with all logins functioning
now and i will find out what causing the initial problem and post my
feedback here again for others
cheers
Beshad

**Comment by MrSwitch** [comment]
@beshad, thanks please provide more information. Thanks

**Comment by MrSwitch** [comment]
inactive
