### ISSUE TITLE
Share Link Dropbox

### ISSUE THREAD

**Issue by nickeskan** [MrSwitch/hello.js#393]
Hi.
I like to know if there is a way to share links to Dropbox files with or without permission and expiration dates.
Thanks,
-Nick

**Comment by MrSwitch** [comment]
That's more of a Dropbox api question. Please head over too https://www.dropbox.com/developers-v1/core/docs

**Comment by nickeskan** [comment]
I followed the link you sent me, and found my answer in the json that Dropbox returns.
Thank you very much for your pointer.
-Nick
