### ISSUE TITLE
Explicit Grant Scenario: Handle Authorization Code manually.

### ISSUE THREAD

**Issue by PsyGik** [MrSwitch/hello.js#394]
I'd like to manually handle the Authorization Code when using Explicit Grant method.

Use Case:
I specify `response_type: code` and do not specify `oauth_proxy`, _then response should be the object containing the Authorization Code from the provider_. Then I can use the Authorization Code as I please.

Current Implementation: If I specify `response_type: code` and do not specify `oauth_proxy`, then it defaults to herokuapp. 

I understand that hello.js was built to have pure client-side implementation, but it'd be nice to have some flexibility.

Thanks!

**Comment by MrSwitch** [comment]
So if you want your redirect_uri is capable of exchanging the Authorization Code for an Access Token. All you then need to do is redirect that to a page with the HelloJS library (+ same origin), with the parameters. `access_token=[token]&state=[state]&expires_in=[token_expires_in]`.

In this scenario your not actually using the OAuth Proxy, just a typical OAuth2 Explicit Grant Flow.

There is a demo [HelloJS signin demo](https://github.com/MrSwitch/hellojs-signin-demo/blob/master/public/script.js). Whereby the `/redirect` has some server logic behind it. Whilst `oauth_proxy` is still defined for signing OAuth1 requests.

I hope this helps. Sorry this scenario isn't really documented.

**Comment by cabnnt** [comment]
@MrSwitch This was recently a source of a fair amount of confusion for me and I was lucky enough to stumble across this issue. Are there any plans to update the documentation to reflect this scenario?
