### ISSUE TITLE
Don't compare functions for equality

### ISSUE THREAD

**Issue by jonsterling** [MrSwitch/hello.js#396]
I was a bit surprised to see that `hello.off` actually looks up the stored callbacks and finds the one which is "equal" to the one the user supplied, if I am understanding the code properly. This could be problematic for a number of reasons...

The notion of equality that is used in this code is not a good one; I played around on my machine and was able to convince myself that it was reference equality (not to be confused with "equality of reference" as an extensional equality, which cannot be decided). So, it is not the case that `function(x) { return x; }` is equal to itself in this sense, but if you assign that function to some variable `f`, then we at least do have `f === f`.

This is going to lead to trouble in a lot of situations, though. At my work, for instance, we use PureScript (a language that compiles to JavaScript), and it is plausible that the compiler may choose to inline definitions (whether it actually does is beside the point). Therefore, I might write `hello.off('auth', f)` but this could get compiled to `hello.off('auth', function () { ... })`, and then in the resulting code the callback would not be unregistered.

Even if one is not using a compiler that might inline things, I would say that it is best practice to support equational reasoning up to extensional equality wherever possible. That is to say, it should be possible to replace code with code that "does the same thing" and not have behavior change; this won't be possible in every case, but it's something to strive for.

A more production-ready approach would be to generate unique tokens to represent each subscription. So, I am envisioning something like this:

```javascript
var subscriptionToken = hello.on('auth', function () { ... });
// do some stuff
hello.off(subscriptionToken);
```

An added benefit of this approach is that there is no need to specify which event is being unsubscribed from in `hello.off`, because the token can be used to uniquely identify both the event and the callback.

How would you feel about an approach like this?

**Comment by MrSwitch** [comment]
Yes, that approach is certainly in keeping with clearTimeout, clearInterval. There's no reason i can think of that prevent both approaches from being supported. I would hesitate if it were not backwards compatible.

Are you offering to work on this?

**Comment by jonsterling** [comment]
@MrSwitch Hi! I might be able to carve out some time to work on this. How would you feel about adding two new methods, `subscribe` and `unsubscribe` (or otherwise named) that behave in the way I described? That way, `on` and `off` can be kept (and made to work in the same way they do now) for as long as is needed to ensure a smooth transition to the safer API.

**Comment by MrSwitch** [comment]
No, that would be confusing for the layman.

**Comment by jonsterling** [comment]
@MrSwitch Hmm; it's a non-starter to implement the new behavior compatibly within the existing methods (it would complicate the correctness conditions of these methods to what I consider an unacceptable degree). Do you have any other suggestion?

**Comment by MrSwitch** [comment]
Create a patch file to create the functions you want, say...

```javascript
hello.subscribe = () => {...};
hello.unsubscribe = () => {...};
hello.trigger = () => {...};
```

In the patch file also overwrite the core method `hello.emit`.

e.g.
```javascript
{
  let emit = hello.emit;
  hello.emit = (a, b) => {
     // Trigger the default
     emit.call(hello, a, b);
     // then trigger your custom handler
     hello.trigger(a, b);
  };
```

That might be a good place to start.

Please share it so i can look over it. Thanks

**Comment by jonsterling** [comment]
@MrSwitch Hi there, I just wanted to let you know that our needs have changed and we will not be requiring this library after all, so I probably will not be able to allocate any time to work on it. Feel free to close this issue if you like, though I still think that users of the library would benefit from the approach I outlined.

Peace,
Jon

**Comment by MrSwitch** [comment]
@jonsterling Ok, if its a good idea then someone will raise the issue again. Thanks for your feedback.
