### ISSUE TITLE
Logout any session before authenticating or always ask for UN and pass

### ISSUE THREAD

**Issue by jmgamboa** [MrSwitch/hello.js#397]
Hey again, so I want the user to be able to authenticate multiple accounts explicitly using username and password for that network. is it possible to ensure they always use username and password?  I proposed potential solutions in the title

**Comment by MrSwitch** [comment]
A few modules support [`force:true` login option](https://adodson.com/hello.js/#helloinit). i.e.

```javascript
hello('google').login({force:true}).then(handler);
```

**Comment by jmgamboa** [comment]
alright cool. maybe this will prevent issues with multiple auth with the same provider? i did see other work arounds in issues. otherwise i'll just have to log out their session before the user tries to reauthenticate? i'll have to see but will close this issue as it addresses the original one. thanks again.
