### ISSUE TITLE
 Explicit Grant flow example request

### ISSUE THREAD

**Issue by elhamsarikhani** [MrSwitch/hello.js#398]
Hi,
This is request is related to [https://github.com/MrSwitch/hello.js/issues/344#issuecomment-169465516](url)
Is it possible for you to provide a sample of refresh token and registration in https://auth-server.herokuapp.com/ ?
I would like to know for example after registration should we provide a reference in code as well and would that work with any redirect uri or just `'http://adodson.com/hello.js/redirect.html'`

**Comment by MrSwitch** [comment]
- reference: is for your own management, its not used.
- domain: optional list of restricted protocols/hosts/paths which can use this. E.g. "adodson.com https://adodson.com https://adodson.com/path" are all valid
- client_id: synonymous with consumer key
- client_secret: synonymous with consumer secret
- grant_uri: can be omited, but on first use will default to the settings given by hello.js. This is used to say where OAuth2 can go to exchange a Authorization Code for an access token. If you dont know leave it blank.

![image](https://cloud.githubusercontent.com/assets/947163/13093099/4b6cf400-d4fb-11e5-8adc-2f7c2aa45a8b.png)

**Comment by elhamsarikhani** [comment]
Thanks! I did fill the form to register my app but should I change something also in the code as well?
in the core library the settings is already there:
oauth_proxy: 'https://auth-server.herokuapp.com/proxy' 
am I right? I'm asking because still after an hour, my session gets expired and I have to login again. It will have issue with push notifications or daily schedules alerts from app which should be according to the data on Live.

**Comment by MrSwitch** [comment]
Please see the documentation on [refreshing the access token](https://adodson.com/hello.js/#refresh-access-token)
