### ISSUE TITLE
[Feature Request] Implement API for GitHub

### ISSUE THREAD

**Issue by julmot** [MrSwitch/hello.js#399]
I just had a look at the API that it has for GitHub. I don't see any use case where it would make sense to use hello.js for GitHub. It just comes with the basics like for a social network. The API does not provide any option to use GitHub specific things like:
- Access repositories with details (issues, branches, files, commits, traffic, etc.)
- Access Gist
- Accesss notifications
- Access follower feed
- ...

**Comment by MrSwitch** [comment]
Hi @julmot, the mapped endpoints are just ones which can be standardized. You can still you HelloJS to access other endpoints. For example here is an exampled of getting the repos belonging to a user https://adodson.com/hello.js/demos/github.html#list-user-repos

I hope that helps. And sorry for the confusion, I realise its perhaps not apparent that this is possible from the documentation.
