### ISSUE TITLE
redirect_uri is encoded

### ISSUE THREAD

**Issue by denzo** [MrSwitch/hello.js#400]
The redirect_uri is encoded using encodeURIComponent and therefore I get the following error from Instagram.

{"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered redirect URI"}

**Comment by denzo** [comment]
Just realised that this is not the case. However, redirect_uri gets a forward slash at the end by doing utils.url(opts.redirect_uri).href

**Comment by MrSwitch** [comment]
My console...

> hello.utils.url('/asd').href
> "https://adodson.com/asd"

 What browser are you on? What's the value of opts.redirect_uri?

**Comment by denzo** [comment]
hello.utils.url('https://adodson.com')

**Comment by MrSwitch** [comment]
Not sure that's necessarily wrong. Afterall this util is a shim of the browser function `URI` (in Chrome and Firefox) so if you run `(new URL('https://adodson.com')).href` you also get the backslash.

How does this affect your application? Is this causing problems with an OAuth provider?

**Comment by denzo** [comment]
Easily fixable by adding a slash on the provider side. I was bedazzled for a while though. Maybe worth a mention in the docs.

**Comment by MrSwitch** [comment]
Not sure, this is really an issue. Most callbacks should be blank pages just to proxy sessions. Root pages are bad choices IMHO.
