### ISSUE TITLE
After Login to twitter Window not closing Showing "Please close the window to continue"

### ISSUE THREAD

**Issue by rashnk** [MrSwitch/hello.js#401]
I am trying a twitter login, in my twitter app i set callback Url  : https://adodson.com/hello.js/redirect.html
and in the app.js of angular sample code i set 

 ```
hello.init({
                    // replace this with your own Facebook App ID                                     
                    twitter: 'XXXXXXXXXXXXX',                   
                }, {
                    scope: 'follower_list',
                    redirect_uri: 'https://adodson.com/hello.js/redirect.html'

                }
                );

```
after i entered the credential in twitter login popup, i cliked 'authorize app' and shows the window 
saying  please close the window to continue

the url is https://adodson.com/hello.js/redirect.html#oauth_token=xxxxxx&oauth_token_secret=xxxxx&user_id=xxx&screen_name=xxxx&x_auth_expires=0&access_token=xxxxxx&state=%7B%22client_id%22%3A%22Xl1fooZAniafv2cg8UyV9EwzF%22%2C%22network%22%3A%22twitter%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_9523g7ed%22%2C%22state%22%3A%22%22%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%2C%22scope%22%3A%22follower_list%2Cbasic%22%2C%22oauth%22%3A%7B%22version%22%3A%221.0a%22%2C%22auth%22%3A%22https%3A%2F%2Ftwitter.com%2Foauth%2Fauthorize%22%2C%22request%22%3A%22https%3A%2F%2Ftwitter.com%2Foauth%2Frequest_token%22%2C%22token%22%3A%22https%3A%2F%2Ftwitter.com%2Foauth%2Faccess_token%22%7D%7D

**Comment by MrSwitch** [comment]
The callback URL `https://adodson.com/hello.js/redirect.html` is only registered within Twitter and Auth-Server to my domain 'https://adodson.com'.
You will need to register your own application path to a Callback URL (redirect_uri)
