### ISSUE TITLE
Generic OAuth2.0 implementation (retrieve token)

### ISSUE THREAD

**Issue by maslick** [MrSwitch/hello.js#402]
I am developing a simple html5 application that retrieves an OAuth2.0 access token from a generic OAuth 2.0 provider (e.g. Keycloak and alike). Assuming the user has previously created a client and user on the authentication server (e.g. Keycloak) he then provides the following parameters on my application web page:
* Authorization URL
* Access token URL
* Client ID
* Client secret

How can I set up hello.js to implement the Authorization code flow in this case?
Thanks!

**Comment by jmgamboa** [comment]
@masclick authorize url occurs server side. this can be generated via @MrSwitch 's  https://www.npmjs.com/package/oauth-shim. That you can host. He also hosts his own public shim server https://auth-server.herokuapp.com/. You must pass the oauth_proxy param in your request. 

Your other option is to build and host one on your own. This will differ in which language you choose but the flow is still the same.

**Comment by maslick** [comment]
As a small addition to my inquiry: 
```
Can it be done in the same way as in the Postman OAuth2.0 client? 
That's basically what I want to implement with hello.js. 
Instead of hardcoding the ClientId and Client secret in the web application 
(which is insecure as everybody can see the javascript code), 
the user provides them in the web-form and 
then you use the standard OAuth2.0 Authorization code workflow, 
which I believe is supported by hello.js?
```
![screen shot 2016-02-22 at 17 49 45](https://cloud.githubusercontent.com/assets/5644706/13225347/bcc43c9a-d98c-11e5-89cb-bee4933f040c.png)

**Comment by jmgamboa** [comment]
hellojs supports oauth two authentication flow. you just have to set your client id key in your code. if your trying to get a raw access token you will need a custom back end. if you just want an authenticated session by network hellojs by itself would work.

**Comment by maslick** [comment]
@jmgamboa sorry I don't quite get you point here - what do you mean by a custom backend? Can you elaborate, please?

**Comment by maslick** [comment]
@jmgamboa I don't think I am exposing the ClientId or Client Secret here, so there is no point in a custom backend. Is that what you meant?

**Comment by jmgamboa** [comment]
some providers allow you to get 'raw access tokens' (an access token that is coupled with a refresh token) these tokens can be used to renew the access token before it expires. if you feel the need for this functionality; you need a custom back end.

**Comment by maslick** [comment]
I don't actually need this functionality. The token in my case shall be either long-lived (several weeks to months), or will be used only once right after it's obtained from the Auth server (short-live). Can hello.js help?

**Comment by jmgamboa** [comment]
yes then hellojs without a backend will still work. have you tried implementing it?

**Comment by MrSwitch** [comment]
inactive
