### ISSUE TITLE
In version 1.11.0 bug appeared when the authorization through vk.com

### ISSUE THREAD

**Issue by sinkill** [MrSwitch/hello.js#405]
In version 1.11.0 bug appeared when the authorization through vk.com. In version 1.10.1 it is not.

**bower.json:**
![2016-02-26 12 42 17](https://cloud.githubusercontent.com/assets/6913231/13349189/5ab8d4ca-dc89-11e5-942e-08fd0dc8e12e.png)

**initialization:**
![2016-02-26 12 42 38](https://cloud.githubusercontent.com/assets/6913231/13349211/6d82a680-dc89-11e5-9653-7dfdb5704c08.png)

**authorization request in version 1.11.0:**

`https://oauth.vk.com/authorize?client_id=[client_id]&response_type=token&redirect_uri=http%3A%2F%2Fff.local%3A3000%2Fredirect.html&display=popup&state=%7B"client_id"%3A[client_id]%2C"network"%3A"vk"%2C"display"%3A"popup"%2C"callback"%3A"_hellojs_c7gne49p"%2C"state"%3A""%2C"redirect_uri"%3A"http%3A%2F%2Fff.local%3A3000%2Fredirect.html"%2C"scope"%3A"photos%2Cemail%2Cshare"%7D&scope=email`

![-2016-02-26-12 44 50](https://cloud.githubusercontent.com/assets/6913231/13349230/89b4ca68-dc89-11e5-915e-502c3ae030d5.png)

**authorization request in version 1.10.1:**

`https://oauth.vk.com/authorize?client_id=[client_id]&response_type=token&redirect_uri=http%3A%2F%2Fff.local%3A3000%2Fredirect.html&display=popup&state=%7B"client_id"%3A[client_id]%2C"network"%3A"vk"%2C"display"%3A"popup"%2C"callback"%3A"_hellojs_4sjyuvlv"%2C"state"%3A""%2C"redirect_uri"%3A"http%3A%2F%2Fff.local%3A3000%2Fredirect.html"%2C"scope"%3A"photos%2Cemail%2Cshare"%7D&scope=photos,email,share`

![-2016-02-26-12 46 59](https://cloud.githubusercontent.com/assets/6913231/13349233/92b6f730-dc89-11e5-8661-0dfad77d00ba.png)

**Comment by MrSwitch** [comment]
@sinkill thanks!

**Comment by MrSwitch** [comment]
Released in v1.11.1
