### ISSUE TITLE
Cannot login in twitter using display = none

### ISSUE THREAD

**Issue by lordgreg** [MrSwitch/hello.js#407]
Hi. I'm saving credentials in localstorage from `hello` for every account I made. After switching account, I want to silently login with data I already had from previous session. However, using `options.display = "none";` in chromium gives me next error:
```
Refused to display 'https://api.twitter.com/oauth/authenticate?oauth_token=xxxxxxxxxxxxx#' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://tweetdeck.twitter.com https://tdapi-staging.smf1.twitter.com https://tdapi-staging.atla.twitter.com https://tweetdeck.localhost.twitter.com".
```

Is this auth-server issue? If so, the url `htts://api.twitter.com/` should also be whitelisted.

I've also tried to update my Content-Security-Policy with:
```
  <meta http-equiv="Content-Security-Policy" 
    content="
      frame-ancestors https://auth-server.herokuapp.com;
      frame-src https://auth-server.herokuapp.com https://api.twitter.com;
      media-src *; 
      img-src *;
      default-src *; 
      style-src 'self' 'unsafe-inline'; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
      https://auth-server.herokuapp.com 
      https://api.twitter.com 
      http://localhost:*
  ">
```

But that didn't brought much either.

Any help?

**Comment by MrSwitch** [comment]
I am a little confused HelloJS maintains session state for you. Register a listener `hello.on('auth.login', sessionHandler)` before calling `hello.init`. Then everytime you visit the page this should be fired.

I think the docs on [refreshing the tokens](https://adodson.com/hello.js/#refresh-access-token) might be a bit misleading . HelloJS will renew expired tokens automatically if the provider permits it.

Twitter uses OAuth1, which has rather long expiration times on tokens (days). But no concept of a `refresh_token`.

**Comment by lordgreg** [comment]
That would be great. But I'm trying to do multi-account app. Which means, everytime I login with different user, I store his data from `getPersonalData()`. Let's say, I have 3 users and their `PersonalData` stored. Currently `User A` is logged in. What am I now trying to do is, first, hello.logout so current user is gone, then, silently login `User B` with stored data.

**Comment by MrSwitch** [comment]
This might be of interest https://github.com/MrSwitch/hello.js/issues/348

**Comment by MrSwitch** [comment]
inactive
