### ISSUE TITLE
Twitter response from GET /me with scope: email does not include email

### ISSUE THREAD

**Issue by pdme** [MrSwitch/hello.js#408]
In order for this to work, I think you need to pass in the option: include_email: true

See https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by MrSwitch** [comment]
OAuth2 scope at login for Twitter's OAuth1 endpoint does not mean anything.

Use...

```es
hello('twitter').api('me', {include_email: true}).then(successHandler)
```

Thanks

**Comment by pdme** [comment]
Thanks for your answer.

I tried that, and it still doesn't work for me. Does it for you?

**Comment by MrSwitch** [comment]
No, my app has not been whitelisted so it always says null.
