### ISSUE TITLE
Single user authentication 

### ISSUE THREAD

**Issue by aelallam** [MrSwitch/hello.js#409]
does hello.js provide a single user oauth. The application does not want to log in, rather run on the background of the app and send tweets accordingly to the applications timeline?

**Comment by MrSwitch** [comment]
If you mean https://dev.twitter.com/oauth/application-only, then no, it doesn't.

**Comment by aelallam** [comment]
@MrSwitch I meant this sir, https://dev.twitter.com/oauth/overview/single-user !

**Comment by MrSwitch** [comment]
Sort of. You could register your apps credentials (consumer key, consumer secret) with the node_oauth_shim (or https://auth-server.herokuapp.com)

Then in the client create the access_token from `token_key:token_secret@consumer_key`. Obviously this is tedious and only runs in the browser at the current time.

I dont mind giving you some more pointers if you want to continue using HelloJS but something else might fit your use case better, like passport.js etc..

Thanks

**Comment by aelallam** [comment]
Thank you @MrSwitch , however, I am using cordova in msvs and all my work is from the client side. I dont know how (or if it is possible) to include node modules in my javascript. What I really want is to make an update requests to the twitter api for and on behalf of the applications account. I do not want to open the browser. just silent post methods. Can you give me any pointers sir? Thank you!

**Comment by MrSwitch** [comment]
Umm, i dont think you understand the concept of OAuth, it can't be on the client, because it contains a secret and we aren't able to secure information in a web app.

Please read the documentation. Perhaps start with modifying the cordova demo to post to Twitter. https://github.com/MrSwitch/hellojs-phonegap-demo

Thanks

**Comment by MrSwitch** [comment]
inactive
