### ISSUE TITLE
Hello.js not working in new mobile safari 9.3 (iPhone)

### ISSUE THREAD

**Issue by sergiferran** [MrSwitch/hello.js#414]
Hey, I'm testing my web integrated with hello.js and doesn't work. Then i tried in `https://adodson.com/hello.js/#hellojs` in my iPhone and is not working. I've been debugging a little bit and it seems that the new safari get stacked in `window.location.assign(oaut_redirect_hash)` in the `responseHandler` function in the redirect page. Could you take a look please? My iOS version is 9.3.
Thanks

**Comment by sergiferran** [comment]
It seems to be related with the new update of iOS to 9.3 (http://9to5mac.com/2016/03/27/some-users-reporting-iphone-crashes-on-ios-9-3-when-tapping-links-in-safari-and-other-apps/)

**Comment by MrSwitch** [comment]
I believe this is a known bug in the latest OS release. And has been fixed http://techcrunch.com/2016/03/31/apple-releases-ios-9-3-1-with-fix-for-bug-that-causes-tapping-links-to-crash-iphones/
