### ISSUE TITLE
SurveyMonkey authorize requests fail due to presence of display parameter

### ISSUE THREAD

**Issue by zachelrath** [MrSwitch/hello.js#418]
SurveyMonkey does not permit non-standard query string parameters in requests to the auth url, so the presence of the "display" parameter, which appears to only be necessary for Facebook (others as well?) causes auth requests to SurveyMonkey using hello.js to fail with the following error:

> The authorization request failed:
> 
> Unsupported Parameter(s): display

https://d2r1vs3d9006ap.cloudfront.net/s3_images/1395272/RackMultipart20160407-66782-sitjnv-surveymonkey_api_error_1_inline.PNG?1460054537

Since "display" is a non-standard query string parameter, it seems like this should only be added for Facebook rather than being included for all services by default.

**Comment by MrSwitch** [comment]
```javascript
login: function(p) {
    delete p.qs.display;
}
```

**Comment by zachelrath** [comment]
@MrSwitch Agreed, that approach would work but I think this may affect other modules as well, so it seems like it would be better to fix it in core by only adding the display parameter for the module(s) that need it, which as far as I can tell is only Facebook.

I've got a pull request nearly ready to go, but I'm working on a unit test.

Are there other services other than Facebook that you know of that expect display? I think hello.js' default behavior should be to conform to standards, and make exceptions as needed at a module level rather than including exception behavior as the default.
