### ISSUE TITLE
NPM Support

### ISSUE THREAD

**Issue by CVarisco** [MrSwitch/hello.js#420]
Hi!
It would be great if I could install using npm.

Thanks a lot and have nice day :)

**Comment by CVarisco** [comment]
I found on npm the package, sorry :)
But update your documention :)

Thanks man!

**Comment by Sn3b** [comment]
What's the name of the package on NPM? There are so many packages containing the word hello, it makes me feel dizzy...

**Comment by albertonaperijr** [comment]
@Sn3b ```hellojs```

**Comment by Sn3b** [comment]
Thanks :)
