### ISSUE TITLE
How to exclude redundant social providers?

### ISSUE THREAD

**Issue by iamyardem** [MrSwitch/hello.js#422]
Minified bundle size is 60kb. The one way to reduce it is to exclude redundant social providers from bundle and add them on demand. For most cases 3 most popular providers are quite enough (google, twitter, facebook).

**Comment by MrSwitch** [comment]
I do agree, there are a few things you can do now too bundle your own. When i get round to documenting them i'll update this comment. Thanks

btw: long term plan is to support ES modules

**Comment by jalieven** [comment]
@MrSwitch And have you documented the few things that can be done to reduce the bundle size?
