### ISSUE TITLE
Calling init() multiple times, is it ok?

### ISSUE THREAD

**Issue by Sn3b** [MrSwitch/hello.js#423]
I am saving the details of the social networks (name and id) I wish to use in my database, so my frontend retrieves them through a webservice call, creates a json object (similar to: {google:"clientid"}) and calls hello.init() with this object. The result is that init() is called multiple times, once per network.

It seems to work fine, but is it ok? Or should I instead construct an object with all networks and then call init()?

**Comment by MrSwitch** [comment]
whichever, it doesn't really matter.
