### ISSUE TITLE
Dropbox only opening with oauth 1.0, not oauth 2.0.

### ISSUE THREAD

**Issue by Travo100** [MrSwitch/hello.js#428]
Hello there!

First off, thank you for this awesome bit of javascript! It has saved me so much time with my project. However, I am trying to integrate dropbox oauth 2.0 for my current setup and I am only able to only open the 1.0 version of the oauth when calling the hello('dropbox').login() function. Also for the grant url I am telling it to be https://www.dropbox.com/1/oauth2/authorize. My app's current public key is unbd2h89c5vchdn. Also I'm using v1.12.0 of hello. Thank you for you help!

**Comment by MrSwitch** [comment]
The Dropbox module will use OAuth2 if your domain is on HTTPS, or fallback to OAuth1.

See switch https://github.com/MrSwitch/hello.js/blob/master/src/modules/dropbox.js#L34

Https callback is required by the Dropbox OAuth2 API

**Comment by Travo100** [comment]
Thank you! That was the issue for me 100%. Switch my local to be https over http and now I'm getting back what I need. I'm closing this issue now.
