### ISSUE TITLE
Bad npm release

### ISSUE THREAD

**Issue by artichokes** [MrSwitch/hello.js#436]
Version 1.13.2 was released with the Facebook popup "fix"; however, the dist files were not rebuilt.

Also the query option `display=popup` should be added if the display setting is set to option:
```
var prefix = '?display=popup';
this.oauth.auth = this.oauth.auth + (p.options.display === 'popup' ? prefix : '');
```

**Comment by MrSwitch** [comment]
@artichokes i've update the PR, thanks :)

Can you create a separate ticket around the other issues. Thanks
