### ISSUE TITLE
Popup too small

### ISSUE THREAD

**Issue by jarodium** [MrSwitch/hello.js#440]
Hello

When I try to facebook login, I have the "popup is too small..." error.
I am running the website with a Desktop with a 1920x1080 display.

Image below:
![notitle](https://cloud.githubusercontent.com/assets/1470446/17030078/c8431fa6-4f65-11e6-99ca-86690fafa185.png)

In the hello.js website the window seems to be working properly, but maybe its because I'm running the minified version? I am using version 1.13.1

Does the 1.13.3 contains any fix for the window size?

Regards

**Comment by BlakeTurner** [comment]
👍  Same issue
