### ISSUE TITLE
auth-server returns old redirect url

### ISSUE THREAD

**Issue by daveoloughlin** [MrSwitch/hello.js#460]
I've changed the Callback URL for my application several days ago at twitter.com. auth-server returns the old one. I get the error "Redirect URL \"http://wsnet.renci.org/htmlNew/group_form/index.html\" must match \"http://wsnet.renci.org/group_form/index.html\" from the first HTTP request below. I can login to twitter from the example app (the second HTTP request below). What am I missing?

https://auth-server.herokuapp.com/proxy?client_id=M6spFniegELbLFkarxJJp0SwN&response_type=token&redirect_uri=http%3A%2F%2Fwsnet.renci.org%2FhtmlNew%2Fgroup_form%2Findex.html&display=popup&scope=&state=%7B%22client_id%22%3A%22M6spFniegELbLFkarxJJp0SwN%22%2C%22network%22%3A%22twitter%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_2254sit1%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22http%3A%2F%2Fwsnet.renci.org%2FhtmlNew%2Fgroup_form%2Findex.html%22%2C%22scope%22%3A%22basic%22%2C%22oauth%22%3A%7B%22version%22%3A%221.0a%22%2C%22auth%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Fauthenticate%22%2C%22request%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Frequest_token%22%2C%22token%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Faccess_token%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D

https://auth-server.herokuapp.com/proxy?client_id=eQuyZuECKWPiv3D7E4qdg&response_type=token&redirect_uri=https%3A%2F%2Fadodson.com%2Fhello.js%2Fredirect.html&state=%7B%22client_id%22%3A%22eQuyZuECKWPiv3D7E4qdg%22%2C%22network%22%3A%22twitter%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_680u7hgm%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fadodson.com%2Fhello.js%2Fredirect.html%22%2C%22scope%22%3A%22basic%22%2C%22oauth%22%3A%7B%22version%22%3A%221.0a%22%2C%22auth%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Fauthenticate%3Fforce_login%3Dtrue%22%2C%22request%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Frequest_token%22%2C%22token%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Faccess_token%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&scope=

**Comment by MrSwitch** [comment]
Sorry for the belated response, you can sign into https://auth-server.herokuapp.com/ and edit this under the grant_url column. Its automatically inserted when you run the application for the first time to lock down which endpoint can receive the authenticated response.

**Comment by daveoloughlin** [comment]
When I sign into https://auth-server.herokuapp.com to do the edit, no rows are shown in the Manage apps table. I'm signed in as the owner of the application on twitter.com. When I try to add the app credentials again to the table, I hit save and get the error "The client_id has already been set".

**Comment by MrSwitch** [comment]
@daveoloughlin that suggests its already registered under another account. What's the Client ID? I can probably tell you the account to signin with if i know that.

**Comment by daveoloughlin** [comment]
M6spFniegELbLFkarxJJp0SwN
Thanks

**Comment by MrSwitch** [comment]
A Google ID was used to create that record.



Andrew Dodson | +44 7752 794 792 | https://adodson.com

**Comment by daveoloughlin** [comment]
Thanks. A miscommunication on our part. Should have tried that.

**Comment by daveoloughlin** [comment]
Done.
