### ISSUE TITLE
Regarding logout status & session data

### ISSUE THREAD

**Issue by isteven** [MrSwitch/hello.js#462]
Hi, 

Thanks for the great library, it saves a lot of time.

I'm new to social media app logins, and I have a question regarding the logout process:

1) Say I login into my website using my Facebook account, using your library. Login success, all good.
2) I then open facebook.com in a new browser tab, and naturally, I'm already logged in into Facebook as well. I then logout from facebook.com
3) However, when I switch tab to my website, I found that I'm still logged in. hello.getAuthResponse('facebook') still gives me data.
4) I'm properly logged out from my website only when I call the hello.logout() method.

My question is, is this the correct behavior? Or, when you logout in facebook.com, should you be logged out from your web / app as well?

**Comment by Senglejan** [comment]
Hi,

You have to set force to true in the options passed to the logout function

`function logoutForce(network){
	hello( network ).logout({force:true},function(e){
		log("logout-force",e);
	});
}`

**Comment by isteven** [comment]
Thanks, further testing & docs reading gave me more info on those. 

Closing the issue.
