### ISSUE TITLE
Redirect uri in hello js 

### ISSUE THREAD

**Issue by kmurugesan83** [MrSwitch/hello.js#466]
Hi,

I'm new to OAuth and hello.js. First of all , I like the library and is a very creative thought. Thanks for sharing it with others. I'm trying to use hello.js to authenticate with Windows and Google and it works!! But the problem is,  when I want to have a redirect uri(separate page) to parse access token, it doesn't seem to do nothing. Here is what I did,

Created 2 pages - login.html and redirect.html. The redirect.html code was taken from here https://adodson.com/hello.js/redirect.html

I have everything defined as per documentation and from fiddler, I see the request is getting redirected to redirect.html, but immediately from there is going back to login.html. I'm not sure what is causing the second redirect. I would expect to stay in redirect.html and parse and display the user information. Please let me know what is wrong.

Login.html
____________

 hello.init({	
	google: 'XXXXXX', // I have replaced this with client id in original code
	windows: 'XXXXXX',
},{
    display:'page',
	scope : 'email',
	redirect_uri: '/redirect.html',
	force:false
});

  // Listen to signin requests
	hello.on('auth.login', function(r) {
	// Get Profile
	hello( r.network ).api( '/me' ).then( function(p) {
		var label = document.getElementById(r.network);
		label.innerHTML = "Connected to "+ r.network+" as " + p.name + ", email: " + p.email;	
	});
});

redirect.html
_________________

<body>

	<div class="loading"><span>&bull;</span><span>&bull;</span><span>&bull;</span></div>

	<h2>Please close this window to continue.</h2>
	<script>	
		window.onbeforeunload = function(){
			document.getElementsByTagName('h2')[0].innerHTML="Redirecting, please wait";
		}
	</script>
		<script src="./hello.all.js"></script>

</body>

**Comment by MrSwitch** [comment]
I think your looking for `display: 'page'` in the options to navigate the whole window, and then `page_uri: url` to define the page to show afterwards. See https://adodson.com/hello.js/demos/login.html#hellologin-displaypage

`redirect_uri` is merely a lightweight page to enable the transfer of the token

**Comment by kmurugesan83** [comment]
I already got the display:'page' and I guess just need to set the page_uri...  That makes sense!!  One quick suggestion, I think the documentation for redirect_uri maybe slightly confusing. See below. when I first read, I thought the redirect page is the one going to process the response and set session data. See if you can rephrase it a bit. Overall, it does a great job!! Thanks a lot.

"The redirect_uri is always a full URL. It must point to a Redirect document which will process the authorization response and set user session data. In order for an application to communicate with this document and set the session data, the origin of the document must match that of the application - this restriction is known as the same-origin security policy."
