### ISSUE TITLE
Auth response not correct

### ISSUE THREAD

**Issue by riyazbhanvadia** [MrSwitch/hello.js#471]
Hi,

I used window to login on my web once i given access. i go to my setting and remove access permission for my web.

Still getAuthResponse is giving response of token  instead of that it should return null.

**Comment by MrSwitch** [comment]
`hello.getAuthResponse` is not sync'd, its recommended to wrap requests with `hello.login`. See bulletproof requests https://adodson.com/hello.js/#refresh-access-token
