### ISSUE TITLE
hello('windows').login({ display: 'none' }) makes redirect to outlook authorizations

### ISSUE THREAD

**Issue by riyazbhanvadia** [MrSwitch/hello.js#472]
Hi  @MrSwitch ,

I tried below code but if user has not subscribed to app then hello.js is redirecting to outlook for authorization app.
While i want hello.js to be returned to error part if user has not subscribed to app.

hello('windows').login({ display: 'none' }).then((res) => {
console.log('sucess');
            }, (e) => {
console.log('error');
            });

can any one help me.

**Comment by MrSwitch** [comment]
This is not recommended, the login needs to be triggered by a user action, display:none is used in  by the app to refresh tokens in the background. So dont use it.
