### ISSUE TITLE
 Use twitter without using a proxy.

### ISSUE THREAD

**Issue by wcontreras** [MrSwitch/hello.js#477]
Good, these days I have been developing an access login using social networks with helloJS, but at the time of using twitter I am redirected to a proxy page.

The truth is I do not know why it takes me there because I have not set up using proxy for twitter.

My hello.init code is as follows.

`			hello.init( {
				twitter:'1UOSV0n4fsFzEig1MuVbEV4Kf',
				facebook:'1158784587547138',
				google:'997135067171-sp6tscl6je11s1olad659ffmdv55n5bn.apps.googleusercontent.com',
				instagram:'8df2a8488d3c4f37a3ac9accd6a89c60'
			},{
				redirect_uri: redirect_uri
			});`

When I redirected back to the page it tells me invalid credential

**Comment by MrSwitch** [comment]
Please read https://adodson.com/hello.js/#oauth-proxy

**Comment by MrSwitch** [comment]
Also i note that the Client ID '1UOSV0n4fsFzEig1MuVbEV4Kf' is registered with a http://localhost endpoint on the //auth-server.
