### ISSUE TITLE
Cordova / Redirect / hello.on

### ISSUE THREAD

**Issue by gs9999** [MrSwitch/hello.js#478]
Hello there everyone.

I am developing an app in Cordova using xcode, and I have the hello.login() working--it loads up the facebook login credential page, for collecting the user's credentials.  However, I am having a problem with the javascript continuing on with the login process in my app.  

For example, I tried running a trigger script upon login using hello.on() to do something with the newly collected information from facebook.  I tried running a script conditional upon successful login using hello.login('facebook', function (auth) { <logic here>});, -AND-

I tried looking up where the redirect.html actually lives in the cordova app filesystem (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html),  so perhaps hello.js could load it up and complete some logic.  I tried https://localhost/appname.app/www/redirect.html and registered that with accepted facebook uri redirect.  The redirect is valid with facebook, thus the appearance of the facebook login screen.

However, I'm running to a bug whereby I can't complete any logic with the information gathered from facebook.

I am getting a 'Load Error' displayed in the in-app-browser after giving correct login information to facebook.

Any direction on this matter?  

Much Appreciated,

GS

**Comment by MrSwitch** [comment]
The demo README https://github.com/MrSwitch/hellojs-phonegap-demo#faqs explains about the redirect_uri in the concept of cordova...

- It has be to a web url
- It doesn't have to actually exist
