### ISSUE TITLE
Token secret in localstorage

### ISSUE THREAD

**Issue by helzgate** [MrSwitch/hello.js#483]
Why is hello.js throwing the twitter token and secret into localstorage?  Isn't this a huge security risk?  If it's ok i'll leave it there, but if not, is there a way to disable it.  By the way, i'd rather leave it there because I can use it and plan to.  I just want to know if this is safe because this seems like a huge vulnerability.

**Comment by MrSwitch** [comment]
So OAuth1a oauth_token and oauth_token_secret together with the oauth_consumer_key represent the users session tokens which is exposed to the client. The oauth_consumer_secret is required to make a verifiable signed request and that is kept sfely on the proxy server. So really this is no different than a Session token which works on the client. The only point i would concede is the seemingly limitless lifetime of the OAuth1 Credentials which makes it vunerable over time, fyi: regular sessions/oauth2 access_tokens typically have short life, about an hour.
