### ISSUE TITLE
Allow for custom fields

### ISSUE THREAD

**Issue by chris-kruining** [MrSwitch/hello.js#503]
Case::
For my application I use hello to enable authentication via social media platforms. however for maintenance reasons I use only 1 registered app at in this case Google. since the return uri cannot be dynamic I need to  reroute on my server, good and all, however, it is not possible to add custom fields to the return uri(to my understanding), right now I piggybacked it on the state setting(fairly certain this is an internally user setting not really meant for this use). 

So my request is to either update the documentation for hello.init to mention that state can bu used to pass parameters or create a state that allows for custom fields.

Thanks in advance :D

**Comment by MrSwitch** [comment]
Hellojs honours the passing of a bespoke `state` property, by preserving it within its own state object. e.g...

```
hello('google').login({state: 'just-set-this'}).then((resp) => {
  console.log(resp.authResponse.state); // ijustsetthis
});
```

**Comment by chris-kruining** [comment]
alright, awesome, that's how I used it. Do you mind adding this to the hello.init documentation, I believe that will save a lot of people time in the future ;)
