### ISSUE TITLE
api('me') not working for Facebook&Github in Firefox

### ISSUE THREAD

**Issue by thorge** [MrSwitch/hello.js#516]
Hello,

when I use hellojs and auth with google in Mozilla Firefox, `api('me').then()` succeeds and I can append email and name to DOM.

But when I auth with facebook or github, both auth flows work well but afterwards in my `on('auth_login')` handler the `api('me')` fails with error code "Access denied" and message "Could not get ressource".

I think I'm doing something wrong, but when I try your demo, I have the same problem. Your demo tells me I'm connected with google, but facebook fails.

**Comment by MrSwitch** [comment]
Hi @thorge can you point to the demo your referfing too, and also if you could show your implementation that would be great, thanks.

**Comment by rommyusa** [comment]
Hello @MrSwitch!

I encountered the same error as @thorge. Seems that the demo on your site itself is not working with facebook and firefox. It works fine in chrome.

![2017-09-03_14h24_43](https://user-images.githubusercontent.com/3459890/30006719-af81ac40-90b3-11e7-996a-af5fbab9ce8e.png)

**Comment by MrSwitch** [comment]
I can't recreate

<img width="1017" alt="screen shot 2017-09-04 at 10 22 35" src="https://user-images.githubusercontent.com/947163/30020217-0888ab7a-915b-11e7-9fd4-68281a7a379c.png">

Can include the XHR request/response please (blur out any sensitive data including tokens)

**Comment by rommyusa** [comment]
Just realized what was the problem. I had the "Privacy Badger" add-on installed. That must have prevented something from being transferred. After disabling the plugin, everything works well. Sorry for the alarm. And thanks for all your great work!

**Comment by thorge** [comment]
It must be a problem with my environment.. Didnt figure it out yet, but I tested different other devices without any problems. So thanks for your fast reply and sorry for the alarm.
