### ISSUE TITLE
Login failing with Firefox 57

### ISSUE THREAD

**Issue by tremby** [MrSwitch/hello.js#523]
Since Firefox 57 I've noticed the login function isn't working properly.

I get as far as the auth response coming back from Google or Facebook or the Twitter proxy, and then when this is passed on to the parent window (the one which called hello.login), an error is hit.

```
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
Stack trace:
login/callbackId<@webpack-internal:///../node_modules/hellojs/dist/hello.all.js:375:11
globalEvent/window[guid]@webpack-internal:///../node_modules/hellojs/dist/hello.all.js:1372:9
self@webpack-internal:///../node_modules/hellojs/dist/hello.all.js:1688:6
```

I placed some breakpoints and found that the problem comes in the equivalent of (source) hello.js line 222, in this callback:

```js
		// Create a global listener to capture events triggered out of scope
		var callbackId = utils.globalEvent(function(str) {

			// The responseHandler returns a string, lets save this locally
			var obj;

			if (str) {
				obj = JSON.parse(str);
			}
			else {
				obj = error('cancelled', 'The authentication was not completed');
			}

			// Handle these response using the local
			// Trigger on the parent
			if (!obj.error) {

				// Save on the parent window the new credentials
				// This fixes an IE10 bug i think... atleast it does for me.
				utils.store(obj.network, obj);

				// Fulfill a successful login
				promise.fulfill({
					network: obj.network,
					authResponse: obj
				});
			}
			else {
				// Reject a successful login
				promise.reject(obj);
			}
		});
```

That's the obj = JSON.parse(str) line.

At this point str is already an object, so JSON.parse is failing.

I do not have this problem in Chrome. I'm running both browsers on OS X Sierra.

Any idea what's happening?

**Comment by MrSwitch** [comment]
I can't reproduce this :( 


<img width="777" alt="screen shot 2017-11-22 at 13 57 11" src="https://user-images.githubusercontent.com/947163/33130987-11b73304-cf8d-11e7-8325-e3afd4d48034.png">

**Comment by tremby** [comment]
Hm, nor can I from home; I saw this in the office. I'll reopen if I see it again. Sorry for the noise otherwise.
