### ISSUE TITLE
Query param values from `oauth_proxy` are not merged.

### ISSUE THREAD

**Issue by moltar** [MrSwitch/hello.js#526]
If `oauth_proxy` value has a URL with query params (e.g. `http://www.example.com/foo?bar=baz`), the resulting redirect URL is broken and results in `http://www.example.com/foo?bar=baz?state=...`. Note the two `?`.

This is the offending piece of code: https://github.com/MrSwitch/hello.js/blob/897b3d0d3dbc01d66c4f0acbc731683ee6f3eb93/src/hello.js#L1305

The solution could be to parse the value from `oauth_proxy` and merge it with the rest of the query string.

**Comment by MrSwitch** [comment]
Yes that is an issue. Can just be wrapped in `utils.qs(state.oauth_proxy, p)` i believe. Wanna give that a stab, @moltar ?

**Comment by moltar** [comment]
Do I need BrowserStack to run tests from `tests/specs/unit/utils/responseHandler.js`?

**Comment by MrSwitch** [comment]
Not necessary. If you create a PR it'll run the test suite.

**Comment by moltar** [comment]
Done!
