### ISSUE TITLE
Unable to register the app credentials in https://auth-server.herokuapp.com

### ISSUE THREAD

**Issue by venkateshparuchuri8** [MrSwitch/hello.js#529]
HI MrSwitch,

I am unable to register my app credentials on [https://auth-server.herokuapp.com].can u pls please assist me  to move further

**Comment by MrSwitch** [comment]
This is a broken dist/ build of v1.16, which auth-server links too, patching now

**Comment by MrSwitch** [comment]
Resolved in v1.16.1
