### ISSUE TITLE
Login with Amazon with redirect

### ISSUE THREAD

**Issue by mark-ellul** [MrSwitch/hello.js#539]
Hi,

I have been trying the Login with Amazon from the hello.js/src/modules/amazon.js module. After the successful login with Amazon, the popup redirects to the "redirect_url" and the main page doesn't seem to respond to the successful login.

How can I make it work like facebook, which closes the popup and calls the event handler with the authResponse?

Any help would be very appreciated

Regards

Mark

**Comment by MrSwitch** [comment]
Hi @mark-ellul 

There appears to be an issue with the Amazon response. Namely it is not returning the state parameter correctly. [example response](https://adodson.com/hello.js/redirect.html#access_token=ACCESS_TOKEN&token_type=bearer&expires_in=3600&scope=profile&state=%7B%26%2334%3Bclient_id%26%2334%3B%3A%26%2334%3Bamzn1.application-oa2-client.5ac60070ee744ae7a241e10e48eae7ff%26%2334%3B%2C%26%2334%3Bnetwork%26%2334%3B%3A%26%2334%3Bamazon%26%2334%3B%2C%26%2334%3Bdisplay%26%2334%3B%3A%26%2334%3Bpopup%26%2334%3B%2C%26%2334%3Bcallback%26%2334%3B%3A%26%2334%3B_hellojs_cepik88m%26%2334%3B%2C%26%2334%3Bstate%26%2334%3B%3A%26%2334%3B%26%2334%3B%2C%26%2334%3Bredirect_uri%26%2334%3B%3A%26%2334%3Bhttps%3A%2F%2Fadodson.com%2Fhello.js%2Fredirect.html%26%2334%3B%2C%26%2334%3Bscope%26%2334%3B%3A%26%2334%3Bbasic%26%2334%3B%7D)

You get get this also in your popup too, just grap the URL from the popup address bar and then run that URL in regular window, you can see in the debugger an error...

<img width="358" alt="screen shot 2018-02-17 at 19 52 04" src="https://user-images.githubusercontent.com/947163/36345061-1c137a50-141c-11e8-9bc9-4a970b5b4f29.png">

This seems to be a fault with Amazon's implementation messing up the request `state`, appears to encode it into HTML Entities, i.e. `"` becomes `&#34;`.

**Comment by mark-ellul** [comment]
thanks @MrSwitch with a patch to my version of the hello.js (doing a a simple replace) and it resolved that issue. Is there a better way to use the amaozon.js to do it? I can see there are ways that the provider javascript files can override methods, but it wasn't obvious if it was possible in this case?

**Comment by MrSwitch** [comment]
Hi @mark-ellul it would be great to have a function as you describe.  For a popup that would work - the initiator could hold a reference to the popup and format the response. However with a full page reload aka `display:page` the initiator is destroyed so different solution required - i.e. caching data in the client. But for the best part neither of these are great solutions to something which shouldn't be a problem if Amazon respected the specs.

The best solution i can think of is to Base64 encode/decode the scope prop. That way it's more URI safe, albeit a little longer...

```
eyJjbGllbnRfaWQiOiJhbXpuMS5hcHBsaWNhdGlvbi1vYTItY2xpZW50LmFuZHJldyIsIm5ldHdvcmsiOiJhbWF6b24iLCJkaXNwbGF5IjoicG9wdXAiLCJjYWxsYmFjayI6Il9oZWxsb2pzX2NlcGlrODhtIiwic3RhdGUiOiIiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2Fkb2Rzb24uY29tL2hlbGxvLmpzL3JlZGlyZWN0Lmh0bWwiLCJzY29wZSI6ImJhc2ljIn0i
```

**Comment by mark-ellul** [comment]
Hi @MrSwitch would the base64 encode/decode resolve this issue? If it does it could be worth adding in the try/catch of the JSON.parse. That way it's not being used in all cases, only when the initial JSON.parse doesn't work.

**Comment by mark-ellul** [comment]
`if (p && 'state' in p) {

			// Remove any addition information
			// E.g. p.state = 'facebook.page';
			try {
				if (p.state.includes("&#34;")) {
					p.state = p.state.replace(/\&\#34\;/g, '"');
				}

				var a = JSON.parse(p.state);
				_this.extend(p, a);
			}
			catch (e) {
				var stateDecoded = decodeURIComponent(p.state);
				try {
					var b = JSON.parse(stateDecoded);
					_this.extend(p, b);
				}
				catch (e) {
					console.error('Could not decode state parameter');
				}
			}
`

This is my patch to hello.js to make it work
