### ISSUE TITLE
Error when retrieving non-album photos from Google

### ISSUE THREAD

**Issue by iFiz** [MrSwitch/hello.js#550]
Hi!

Calling 'me/photos' on Google will result in a Javascript error. It looks like the response lacks the 'entry' key whenever no photos are returned. The assumption is made that this key always exists when parsing the return data.

`function formatPhotos(o) {
    o.data = o.feed.entry.map(formatEntry);
    delete o.feed;
}`

I was able to consistently reproduce this on the Hello.js homepage by logging in to my Google account and then clicking the 'me/photos' button. 

> hello.all.js:4161 Uncaught TypeError: Cannot read property 'entry' of undefined
    at Object.formatPhotos [as me/photos] (hello.all.js:4161)
    at hello.all.js:2001
    at XMLHttpRequest.r.onerror (hello.all.js:2287)

Sample response (with stripped data): 
`{
    "version": "1.0",
    "encoding": "UTF-8",
    "feed": {
        "xmlns": "http://www.w3.org/2005/Atom",
        "xmlns$openSearch": "http://a9.com/-/spec/opensearchrss/1.0/",
        "xmlns$gphoto": "http://schemas.google.com/photos/2007",
        "id": {
            "$t": "https://picasaweb.google.com/data/feed/api/user/default"
        },
        "updated": {
            "$t": "1970-01-01T00:00:00.000Z"
        },
        "category": [
            {
                "scheme": "http://schemas.google.com/g/2005#kind",
                "term": "http://schemas.google.com/photos/2007#user"
            }
        ],
        "title": {
            "$t": "#",
            "type": "text"
        },
        "subtitle": {
            "$t": "",
            "type": "text"
        },
        "icon": {
            "$t": "#"
        },
        "link": [
            {
                "rel": "http://schemas.google.com/g/2005#feed",
                "type": "#",
                "href": "#"
            },
            {
                "rel": "alternate",
                "type": "text/html",
                "href": "#"
            },
            {
                "rel": "http://schemas.google.com/photos/2007#slideshow",
                "type": "application/x-shockwave-flash",
                "href": "#"
            },
            {
                "rel": "self",
                "type": "application/atom+xml",
                "href": "#"
            }
        ],
        "author": [
            {
                "name": {
                    "$t": "#"
                },
                "uri": {
                    "$t": "#"
                }
            }
        ],
        "generator": {
            "$t": "Picasaweb",
            "version": "1.00",
            "uri": "http://picasaweb.google.com/"
        },
        "openSearch$totalResults": {
            "$t": 0
        },
        "openSearch$startIndex": {
            "$t": 1
        },
        "openSearch$itemsPerPage": {
            "$t": 1000
        },
        "gphoto$user": {
            "$t": "#"
        },
        "gphoto$nickname": {
            "$t": "#"
        },
        "gphoto$thumbnail": {
            "$t": "#"
        },
        "gphoto$maxPhotosPerAlbum": {
            "$t": 0
        },
        "gphoto$organization": {
            "name": "#",
            "canSilo": "#",
            "canUnsilo": "#",
            "canUnsiloWithWarning": "#"
        }
    }
}`

There are many ways to fix this, I could make a pull request if you can tell me how you'd like to see it fixed. Thanks in advance!

**Comment by MrSwitch** [comment]
Yeah please just just write a PR. Will checking the existance of a `entry` suffice?
