### ISSUE TITLE
Auth server not working

### ISSUE THREAD

**Issue by xaiamedia** [MrSwitch/hello.js#552]
When I try to login with my twitter account at https://auth-server.herokuapp.com/, I can succesfully authenticate but then afterwards the redirect calls a page with the message "Error", just that word.

Same goes for facebook.

Is the service not working anymore? :)

**Comment by MrSwitch** [comment]
Can you provide more information, Response Headers and Body

**Comment by xaiamedia** [comment]
There are non? When I click on login, a pop-up window opens, I try to connect with twitter.. the twitter page opens succesfully. After that I get a big grey H2 tag with the word Error. The pages contains nothing else?

**Comment by xaiamedia** [comment]
Steps to reproduce:

1. Go to https://auth-server.herokuapp.com
2. Click signin
3. Choose 'Twitter connect'
4. Redirect to twitter, auth is successful
5. Redirect back
6. A big H1 tag shows up with error, no other messages

The HTML code of that page:
`<html><head><title>Authentication Error</title><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><link rel="icon" href="//adodson.com/favicon.ico"><link rel="stylesheet" href="//adodson.com/adorn/adorn.css"></head><body><h1>Error</h1></body></html>`

**Comment by MrSwitch** [comment]
Which browser/device are you using?

**Comment by xaiamedia** [comment]
I have tried Chrome and Firefox

**Comment by MrSwitch** [comment]
Please provide screen shots, URL of the broken page etc...

**Comment by xaiamedia** [comment]
Okay here are three screens of the proces:
http://weareinvision.nl/files/screen-1-auth.jpg
http://weareinvision.nl/files/screen-2-auth.jpg
http://weareinvision.nl/files/screen-3-auth.jpg

The url on the error page:
https://auth-server.herokuapp.com/auth/redirect?proxy_url=http%3A%2F%2Fauth-server.herokuapp.com%2Fredirect&state=twitter&client_id=Yqwglej50P9C8JgKGfnJisFBP&oauth_token=bR66fwAAAAAAjSynAAABY7UKlD4&oauth_verifier=1KIyhvgfPfKm5wMQwVyL1Y4g7FzTyMmU

**Comment by MrSwitch** [comment]
That's really strange, i can't replicate that at all. Anything else you can think of?

**Comment by MrSwitch** [comment]
@xaiamedia @mark-ellul please verify again.

The application exceeded Heroku's Postgres row limit, that's resolved now.

**Comment by xaiamedia** [comment]
@MrSwitch yes that fixed the problem :)

**Comment by MrSwitch** [comment]
Great, @xaiamedia that sounds about right
