### ISSUE TITLE
hello.js doesn't work with Google accounts without Google+ enabled

### ISSUE THREAD

**Issue by rcook** [MrSwitch/hello.js#556]
I would like to use hello.js for authentication without access "advanced" Google+ features enabled on them. Really, all I need is basic profile information (such as account ID). For such accounts, calls to `me` API fail as follows:

Request: `https://www.googleapis.com/plus/v1/people/me?access_token=REDACTED`
Response:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Project REDACTED is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=REDACTED then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=REDACTED"
   }
  ],
  "code": 403,
  "message": "Project REDACTED is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=REDACTED then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
}
```

I do not control the target account so I cannot enable Google+ on it. However, if I modify the [`google.js` module](https://github.com/MrSwitch/hello.js/blob/master/src/modules/google.js) to replace the base URI for `me` with the old (deprecated) value `oauth2/v1/userinfo?alt=json`, my API succeeds.

I would like to propose adding a `google_deprecated.js` module that uses this old API instead of the new API for people who want to us hello.js without requiring access to Google+ features. If I put this module together, would such a pull request be likely to be accepted?

**Comment by rcook** [comment]
If this looks like a reasonable pull request, please accept https://github.com/rcook/hello.js/commit/42876a7de10253c4787667f687ddc8cf8a1e0e2c and _not_ https://github.com/rcook/hello.js/commit/d20c68548d254b4f91eb99e641ab74870d2caec9. Thanks!

**Comment by rcook** [comment]
I have a reasonable workaround.

**Comment by MrSwitch** [comment]
Hi rcook. It sounds like the better approach as you say. I would like to update the existing google module if you want to work on that please let me know
