### ISSUE TITLE
https://auth-server.herokuapp.com/ is unhealthy

### ISSUE THREAD

**Issue by rcook** [MrSwitch/hello.js#562]
Hi,

https://auth-server.herokuapp.com/#monitoring indicates an increased error rate in the OAuth proxy at https://auth-server.herokuapp.com/. Furthermore, attempting to sign in to manage my registered apps results in a database error.

-Richard

**Comment by sleman** [comment]
Can't log into twitter. 

![authentication error - google chrome 2018-06-22 15 57 46](https://user-images.githubusercontent.com/976380/41796601-36711918-7635-11e8-8bba-0b67a59d0c1f.png)

**Comment by MrSwitch** [comment]
Thanks both, restarted the dynos and it appears to be back.

**Comment by rcook** [comment]
Perfect! Thanks, Andrew.
