### ISSUE TITLE
I have some solutions to the new FB Graph API v2 friends issue

### ISSUE THREAD

**Issue by TeknoloGenie** [MrSwitch/hello.js#57]
This applies to all apps created after May 1st and apps that have migrated to the new Facebook Graph API. 

Recently due to Facebooks new graph api that was released April 30th some new rules have been made that restrict access to a users friends list. Now the required scope `user_friends` is required. Also as a result even if a user grants this permission, the only friends that will be shown are friends that are also using the same app, for example a person who plays Clash of Clans can only see friends who are also playing Clash of Clans

There are some upsides, GAMES ONLY utilizing Canvas Games in Facebook are allowed to get an `me/invitable_friends` however this is for approved games only.

Even though this is a major disadvantage to developers now i have found one way to at least get some of the users friends, being all the users family members, this requires going to the `me/family` and having the scope `user_relationships` added. 

This is more a solution then a issue really. I propose HelloJS users use

`hello("facebook").api("me/family", "get", {limit: 100}, function(json){console.log(json);});`

However even with this it does not format the response with a user thumbnail so im not sure how to resolve that part.

Any other feedback and solutions is greatly appreciated as far as the thumbnail goes

EDIT: i wanted to add this link for reference because i think it may help us build a VIEWABLE only list of friends, however we would not be able to do anything else but have a list of friends, couldn't invite them to the app, could possibly do a share this app with friends thing and do a share api post coupled with this `me/taggable_friends` endpoint just a random thought though. But the app has to be approved to use this endpoint so Facebook not might light that very much. I suppose as long as the user understands they are sharring the app publicly and tagging those friends they should not have a problem but who knows. Facebook's lame now a'days but we put up with them because mass amount of the world uses it. Anyways,  heres the link
https://developers.facebook.com/docs/graph-api/reference/v2.0/user/taggable_friends/

**Comment by yomanx** [comment]
hi, so anybody tested taggable_friends? Can we use it in our games?
