### ISSUE TITLE
X-Frame-Options exception when using login

### ISSUE THREAD

**Issue by edgargaza** [MrSwitch/hello.js#573]
I have a problem when dealing with the login. This is my code:

```
hello("google").login().then(function(auth) {
    console.log(auth);
}, function(error) {
    console.log(error);
});
```

And this is giving the "Load denied by X-Frame-Options" exception, idk why. I've tried also this way:

```
hello("google").login().then(function(auth) {
    console.log(auth);
}).catch(function(error) {
    console.log(error);
});
```

In my console are these 3 warnings:

![imagen](https://user-images.githubusercontent.com/40411222/45787526-22c07080-bc76-11e8-9cbc-52ef5c3a7a3b.png)

I've searched yesterday at night and full-day today, and I didn't find anything, so I ask help here... Do you know how could I solve this? And why this is happening?

Thx in advance!

**Comment by edgargaza** [comment]
Lol ok I restarted yesterday my computer a few times, and it didn't work. Now, all errors are gone (including the CSP warnings) and this works like a charm... sorry for this issue ticket, sometimes computers do dumb things also...

**Comment by MrSwitch** [comment]
The `.catch` is not supported, please use the `.then(null, failure)` approach.

v2, when it gets worked on will resolve this.
