### ISSUE TITLE
Google+ APIs being shutdown on March 7, 2019

### ISSUE THREAD

**Issue by Elointz** [MrSwitch/hello.js#586]
Any plans to update for support of Google Sign-In? (https://developers.google.com/identity/) 
The current implementation is for Google+ Sign-In which will be deprecated. 
https://developers.google.com/identity/sign-in/web/quick-migration-guide

**Comment by thomasmichaelwallace** [comment]
For information: PR #451 looks like it deals with this.

**Comment by ptrwtts** [comment]
Any update on this? Or has anyone figured out a way to update the library to support the new system?

**Comment by MrSwitch** [comment]
Hi all 

If you can test the proposed PR #451 and endorse it i will merge it in.

Thanks

**Comment by thomasmichaelwallace** [comment]
Hi @MrSwitch - unfortunately that PR does not address this issue as it still uses the G+ api

For example:https://github.com/MrSwitch/hello.js/blob/432b34eff639ec89a80e38e8ca08af0274746a0f/src/modules/google.js#L60

**Comment by Elointz** [comment]
One week left. Any update on this or suggestion on alternative libraries that will work?

**Comment by MrSwitch** [comment]
https://github.com/MrSwitch/hello.js/pull/590 was merged into v1.18.1 thanks.

I haven't tested this extensively so please do, i'll leave this open for now

**Comment by thomasmichaelwallace** [comment]
Just a note to say that v1.18.1 is working fine for us. 💯

**Comment by Elointz** [comment]
Working fine for me too. No more calls seen in Google Console.
