### ISSUE TITLE
Snap! There has been an error authenticating your request, we're working to fix it. Please try refreshing this page in a moment.

### ISSUE THREAD

**Issue by blairg23** [MrSwitch/hello.js#592]
**Window error:**
![image](https://user-images.githubusercontent.com/6225764/52878329-8feb0b80-3119-11e9-958b-6ad68fc4f594.png)

**Console:**
![image](https://user-images.githubusercontent.com/6225764/52878394-bad55f80-3119-11e9-9dec-54369b726de8.png)

**Comment by MrSwitch** [comment]
Restarted the dynos and all seems normal again.

Thanks
