### ISSUE TITLE
Promise polyfill overwrites Promise built-in on firefox

### ISSUE THREAD

**Issue by chris-kruining** [MrSwitch/hello.js#594]
I've been using your library (v 2.0.0-4) for quite a while now, but I discovered now that I load my js files with es6 modules that your Promise object (I assume functions as a polyfill) overwrites the built-in Promise object on Firefox. I do not experience this issue in Chrome (have not tested other browsers). Could you fix this issue, so it no longer overwrites the built-in Promise object?

**Comment by MrSwitch** [comment]
Oh, sorry to hear that, i guess it's a polyfill thing. How are you importing the module?

**Comment by chris-kruining** [comment]
```es6
    import 'https://cdnjs.cloudflare.com/ajax/libs/hellojs/2.0.0-4/hello.all.js';
```
I have my modules loaded with crossorigin so I am not limited by incorrect CORS headers

If possible it would be very very nice and awesome if you could manage to distribute a module version, then I could utilize the full power of es6! (no worries if not possible ;) )

**Comment by MrSwitch** [comment]
Ah ok, yes that comes bundled with the Polyfill. I'll update it soon and hopefully the next version will work.
