### ISSUE TITLE
Visual Studio emulator's Internet Explorer - Permission Denied

### ISSUE THREAD

**Issue by mgibas** [MrSwitch/hello.js#61]
Hello,

Recently I'm getting Permission Denied on IE10, IE11, WP8 IE, WP8.1 IE - from my quick investigation it's because of some kind of security path (can not access popup from other domain).

Exception throws on [line1202 of hello.all.js](https://github.com/MrSwitch/hello.js/blob/master/dist/hello.all.js#L1202)

**Comment by MrSwitch** [comment]
inactive
