### ISSUE TITLE
Potential XSS Security Vulnerability

### ISSUE THREAD

**Issue by kaykhan** [MrSwitch/hello.js#617]
**Problem**

A user is able to inject javascript into the `state.page_uri` query parameter and it will be executed

**Steps to reproduce**

[https://adodson.com/hello.js/?state={"page_uri":"javascript:alert(document.cookie);"}](https://adodson.com/hello.js/?state=%7B%22page_uri%22:%22javascript:alert(document.cookie);%22%7D)

**Investigation**

Upon investigation it occurs on line `1536` of 
https://raw.githubusercontent.com/MrSwitch/hello.js/master/dist/hello.all.js

```
if (p.page_uri) {
  location.assign(p.page_uri);
}
```

`location.assign` will accept and execute any `javascript:` scheme as it is a valid URI scheme https://en.wikipedia.org/wiki/List_of_URI_schemes

**Potential Solution**

A simple solution would be to sanity check the input to see if it is a valid http uri. But, I don't know what other implications this might have.

```
if(isValidHttpUrl(p.page_uri)) {
  location.assign(p.page_uri)
}
```

**Comment by MrSwitch** [comment]
Hmmmm please create a PR.

**Comment by MrSwitch** [comment]
Thanks @kaykhan for spotting this and reporting it.
