### ISSUE TITLE
Problem while getting oauth with linkedin working

### ISSUE THREAD

**Issue by jaydeep98** [MrSwitch/hello.js#67]
It is very good liabrary to implement ouath. 
I am having some problem getting login with linkedin working. When I run linkedin,html in demo's with mine linkedin api key (in client_id file). It authenticates successfully but does not do anything after login pop closes.  Also I tried to put alert to detect if returns to function on main html page

hello.on('auth.login', function(r){
    // Get Profile
    hello.api(r.network+':/me', function(p){
        document.getElementById('login').innerHTML = "<img src='"+ p.thumbnail + "' width=24/>Connected to "+ r.network+" as " + p.name;
    });
});

I am doing any thing wrong.

With facebook I got success.

**Comment by vclteam** [comment]
hi

for some reason im not getting auth.login on linkedin
i registered the application but nothing

am i missing something?
