### ISSUE TITLE
Real logout not working on Phonegap

### ISSUE THREAD

**Issue by sunshineo** [MrSwitch/hello.js#69]
I followed the sample. And here https://github.com/MrSwitch/hellojs-phonegap-demo/blob/master/index.html#L54 it says the redirect_url can be anything. So I used http://localhost/index.html and I configured my facebook app to list that as one of the 'Valid OAuth redirect URIs'
It works fine when login. But does not work when logout for real like this:
        hello("facebook").logout({force:true},function() { alert("logged out"); });
The url it will try to open in a iframe is:
https://www.facebook.com/logout.php?next=http%3A%2F%2Flocalhost%2Findex.html%3Fcallback%3D_hellojs_8o4euzh5%26result%3D%257B%2522force%2522%253Atrue%257D%26state%3D%257B%257D&access_token=****

This does NOT log the user out at all. It goes to facebook homepage.
I used to use 'https://www.facebook.com/connect/login_success.html' as the recirect_url when using a library called OpenFB. When try to logout the url it will try to open in a iframe is:
https://www.facebook.com/logout.php?next=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html%3Fcallback%3D_hellojs_1etpgwvu%26result%3D%257B%2522force%2522%253Atrue%257D%26state%3D%257B%257D&access_token=****

This does log the user out from facebook but the global event handler does not work and my callback function does not get called.
Code here https://github.com/MrSwitch/hello.js/blob/master/src/modules/facebook.js#L64 creating a global event handler and add the callbackId to the url does not seems to work. 

Please help!

**Comment by MrSwitch** [comment]
Only a few providers let you actually logout. See the `hello.logout` api
